### ISSUE TITLE
Shell in Alt-Tab Menu

### ISSUE THREAD

**Issue by gaberade** [cairoshell/cairoshell#1]
Running Cairo on Win7, the shell shows up as an untitled icon in the Alt-Tab menu four times. If you select the shell in the alt tab menu, desktop icons change z-level and will 'sandwich' windows between them and the desktop background.

Not sure if this is the place to report something like this, but the "Report a Bug" link on the http://cairoshell.github.com/download/ page is broken, the "Community Forum" link on the same page 404's, and the "Contact Us" link on the 404 page links to a non-existent page.

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
