### ISSUE TITLE
Make Windows key open "Programs panel"

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#100]
...when explorer.exe is terminated to ensure nothing would conflict.

Also, there need to be other windows key shortcuts to be implemented. For me, especially Win+D to minimizing all windows.

**Comment by mdmk** [comment]
@Gentle888
Concerning your second statement, and for your information, as mentioned in #82, new shortcuts and shortcut customisation are planned but not yet implemented.

**Comment by dremin** [comment]
Good idea! I hadn't thought about doing this before but I will look into it.

**Comment by Gentle888** [comment]
@dremin Hope to see this feauture in the future! ;)

**Comment by dremin** [comment]
This will be available in the next build.

**Comment by dremin** [comment]
This is now available in the latest release.
