### ISSUE TITLE
Option in settings to re-enable Explorer+Cairo without relaunching installer

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#101]

**Comment by mdmk** [comment]
Indeed, that would be good, especially for testing purposes.

**Comment by Gentle888** [comment]
Or switching WiFi networks in Win10 😄

**Comment by dremin** [comment]
This feature will be available from the Settings > Advanced tab in the next build.

**Comment by dremin** [comment]
This is now available in the latest release.
