### ISSUE TITLE
Feature Request: Add an option to hide some of notification icons

### ISSUE THREAD

**Issue by simonporte** [cairoshell/cairoshell#102]
Currently there is no control over what is shown: all or nothing.
I'd like to add that this feature would provide a workaround for mactype mactray bug.
With icon hidden, mactray would launch and not crash, at least it is what I think.

**Comment by Gentle888** [comment]
Tried to workaround this with using MacType in Service Mode, but after restart Cairo nor anything on the system we're affected by MacType. 

Yes, I can confirm that we really need this.

**Comment by dremin** [comment]
I'd like to implement this. To start, we can "pin" the standard Windows notification icons, then expand this later with a UI in settings to selectively pin any icon.

**Comment by dremin** [comment]
This should be available in the next release!

**Comment by dremin** [comment]
This is now available.
