### ISSUE TITLE
Top panel hids itself randomly

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#104]
Cant reproduce. It's totally random.

**Comment by dremin** [comment]
Have you been able to find reproduction steps? For example, seeing if it happens without other apps running, happening only with Cairo or Explorer as shell, etc. Otherwise, I will have to close this since I am unable to reproduce this (haven't seen it happen to be honest)

**Comment by dremin** [comment]
Closing due to lack of reproduction steps. Please re-open if you are able to figure out what steps causes this to happen on your machine.
