### ISSUE TITLE
[BUG] Cairo overlaps Windowed Fullscreen programs

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#105]
![image](https://user-images.githubusercontent.com/32046895/37427286-c3f02c28-27ea-11e8-8cc2-1c531784b01c.png)

**Comment by mdmk** [comment]
Did you set Cairo to replace explorer or not ?
Issue similar to #30
Are you video drivers up to date ?
Does alt + tab bring the game to front ?

**Comment by dremin** [comment]
Does it happen in all games on your system or just HOTS? I am unable to reproduce this in any game I play.

**Comment by Gentle888** [comment]
@mdmk 
Cairo is not replacing explorer
Drivers up to date
Alt-tab not solving issue

@dremin 
Same thing with OW, SC2 and Destiny 2, all set to borderless windowed

**Comment by mdmk** [comment]
Perhaps you could try replacing explorer
You can do this by reinstalling.
Or else wait for the next release, @dremin announced there will be an option in settings.

You can also try true full screen mode as a workaround.
True full screen will be on top, but alt + tab will minimise game wich is not very convenient.

**Comment by mdmk** [comment]
Said option to replace shell has been added to the latest release.

**Comment by dremin** [comment]
This is fixed in the latest release.
