### ISSUE TITLE
Create an issue template for the repository

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#106]
@dremin
[Here](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) the official howto.
It think it would save a valuable amount of time for the future issues.

I think there should be a list of prerequisite information with checkboxes to check.
Eg.:
Prerequisite :

[ ] Windows version
[ ] 32/64bit Windows
[ ] Cairo version
[ ] 32/64bit Cairo
[ ] Cairo set as a shell

With hyperlinks with howto to explain how to check each step

If you want I can spend some time on it, perhaps the next week, and do a pull request if it works for templates.

**Comment by dremin** [comment]
I agree this would be very helpful! Feel free to take this if you'd like.

One thing I would like is a Troubleshooting page on the GitHub Wiki. That could also include instructions on how to obtain the items requested.

While it would need an affordance for feature requests as well, I think these items at a minimum should be included in the template for issues:
- Windows version & architecture
- Cairo version & architecture
- Is Cairo set as shell
- Steps to reproduce
- Desired vs actual outcome

**Comment by dremin** [comment]
@mdmk - were you wanting to do this? Let me know, I can do it if not. Thanks!

**Comment by mdmk** [comment]
@dremin I wanted to do this but I lack some time to do writing at the moment.
So take the isssue if you want to.

But I searched through the documentation and I think the best thing to use is the default web graphical tool to create issue templates.
The result should be this header on top of issue list:


![](https://help.github.com/assets/images/help/issues/new-issue-page-with-multiple-templates.png)

So two buttons, one for bug, one for issue, and one link for everything else.
And so three different templates for the three use cases (good for separation as you asked).

Only the repository owner can create them this way.
The documentation is [here](https://help.github.com/assets/images/help/issues/new-issue-page-with-multiple-templates.png).
I think the direct link to the feature is [here](https://github.com/cairoshell/cairoshell/issues/templates/edit), only accessible by you.
If it doesnt work, go 
[here](https://user-images.githubusercontent.com/32496803/40278879-85046dde-5c39-11e8-8018-83e6d3a39325.jpg) then [there](https://user-images.githubusercontent.com/32496803/40278880-8ac61434-5c39-11e8-819c-ff79d853b7d5.jpg).

**Comment by dremin** [comment]
Thanks for showing the tool! I was able to add those templates.
