### ISSUE TITLE
RegisterAsBrowser issue.

### ISSUE THREAD

**Issue by apzloy** [cairoshell/cairoshell#108]
I found a lack of functional of your shell. And it's very important for me and may be for others. I use WebBrowser in my projects. It uses [IWebBrowser2](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752127(v=vs.85)) interface which has [RegisterAsBrowser](https://msdn.microsoft.com/ru-ru/library/aa768264(v=vs.85).aspx) property. This property is very important in case of interaction between top-level browser window and popups (especially popups that created by Javascript function showModalDialog). Setting RegisterAsBrowser = True doesn't work when i use CairoShell. And popup knows nothing about parent top-level browser window and therefore cannot pass necessary info to it. But when i use standard shell (explorer.exe) it works fine. An identical question was asked [here](https://social.msdn.microsoft.com/Forums/ie/en-US/cec1aa47-c795-4e07-90da-5888ed7726d2/registerasbrowser-probelm?forum=ieextensiondevelopment), but it is unanswered yet and i think it wont be closed.

**Comment by dremin** [comment]
Try disabling the "Periodically re-establish notification area hook" option in Cairo Settings, and restart Cairo. This should allow the other apps to see and use explorer.exe functions while Cairo is running.

**Comment by apzloy** [comment]
No, it's not about Notification Area (tray). But i did it and it didn't help. I think [IShellWindows ](https://msdn.microsoft.com/en-us/library/windows/desktop/cc836570(v=vs.85).aspx)interface works in this scenario.

**Comment by josuave** [comment]
I believe the problem is that when Cairo runs as shell (no explorer.exe) some system functionality is lost due to some COM objects and interfaces that are not implemented in Cairo.

Sent from my iPhone

On Mar 20, 2018, at 4:02 AM, apzloy <notifications@github.com<mailto:notifications@github.com>> wrote:


No, it's not about Notification Area (tray). But i did it and it didn't help. I think IShellWindows <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Fwindows%2Fdesktop%2Fcc836570(v%3Dvs.85).aspx&data=02%7C01%7C%7C9ba32c4a308143e1206a08d58e38fb04%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636571297733607314&sdata=b22a87uD4TU5b8hQactGacwYLp%2FaeRN0gje24T%2B9bQg%3D&reserved=0> interface works in this scenario.

**Comment by dremin** [comment]
Did you install Cairo with the option to replace Explorer? If not, Explorer is still in the background and can service those requests. The only thing I can think of that would prevent this from happening is Cairo's notification area support which intercepts messages to Explorer.

**Comment by apzloy** [comment]
Why are you talking about notification area again? What a point of it?
When you create shell replacement (INSTEAD of explorer), you should create window with className "Shell_TrayWnd" for your notification area. Next step is to call SendNotifyMessageW(HWND_BROADCAST, RegisterWindowMessageW(L"TaskbarCreated"), 0, 0)
In this case you will be able to receive WM_COPYDATA message in your WndProc. Then you should handle COPYDATASTRUCT to determine if it is notification area data. If it is then you can manipulate this object as you wish. Add, show, remove, update notification icon etc... And that is all about notification area. And how does this relate to the described above problem?

**Comment by dremin** [comment]
You are correct, and Cairo follows these steps. However, many of the shell APIs send messages to the first window returned with the class Shell_TrayWnd. When Cairo's notification area is enabled, Cairo is the first window with class Shell_TrayWnd returned, meaning the message never makes it to Explorer. Hope this makes more sense. Maybe I can forward the requests to Explorer.

**Comment by apzloy** [comment]
Yes. "first window returned with the class Shell_TrayWnd". You are right. But anyway i can't see relation between my problem and this thing we are talking to.

**Comment by dremin** [comment]
Do you have an example program I can use to reproduce the issue?

**Comment by dremin** [comment]
I made a small app that sets registerasbrowser on some explorer windows and the setting seemed to be sticking when querying them. Is this still happening on the latest builds?

**Comment by dremin** [comment]
Closing due to no response.
