### ISSUE TITLE
Cairo doesn't appear after computer wakes up from sleep in multi-monitor configuration

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#109]
After putting my laptop to sleep, when I wake and unlock it after docking it into my multi-monitor setup, Cairo no longer appears although the process for it continues to run. There's a gap on the primary screen for the Cairo menu bar, but the other screens act as if Cairo isn't running at all.

**Comment by mdmk** [comment]
Are your video drivers up to date ?

Are you using the video connector (VGA/DVI/HDMI/DP) on the laptop or do you use a USB adapter/docking station with video ports on it ?

**Comment by coldacid** [comment]
Drivers are up to date. One monitor is connected through a USB docking station and the other is connected directly to the laptop via mini DP.

**Comment by mdmk** [comment]
Same problem if you only use laptop mini DP and no USB docking station ?
Seek for video driver for the USB docking station.
There is chance it use DisplayLink chips.
If it is the case, download latest driver on Display Link website.

**Comment by coldacid** [comment]
Just checked and yeah. So we'll see tomorrow morning if the problem reoccurs or not.

**Comment by coldacid** [comment]
Yeah, looks like DisplayLink drivers have fixed it.
