### ISSUE TITLE
Silverlight/Moonlight

### ISSUE THREAD

**Issue by bklooste** [cairoshell/cairoshell#11]
Does it work with Silverlight / Moonlight ? 

Im working on a new uclinux OS and was wondering whether it would work with Silverlight or even Moonlight ? 

If yes on silverlight . What will the performance be like ( especially looking at 600Mhz-1G embedded devices here) ?  And can you run Moonlight apps ?

**Comment by cairoshell** [comment]
Closing since Silverlight is EOL.
