### ISSUE TITLE
[Multimonitor][Bug] Cairo "restores" all over the place when waking a multi-monitor system

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#110]
See screenshot. And this time all drivers (including for DisplayLink) are completely up to date.
![screenshot](https://user-images.githubusercontent.com/130681/37912336-53590fa8-30e0-11e8-8734-957a37cca6ef.png)

For three screens, there are four Cairo menubars, with only one of them (the "closer" of the two on the top-right screen) being in the proper location. None of them respond to any input, either.

**Comment by mdmk** [comment]
What is the resources rectangle on top left monitor?
Is this a bad ms paint copy paste or is there two top menu bar on top right screen ?
If two, how many Cairo processes in task manager?

**Comment by mdmk** [comment]
What is the thing highlighted in pink? ! [](https://i.imgur.com/0z4C4xe.jpg)
Just observing:
It seems the second bar on top right screen is the bar missing on bottom screen.
Taskbar is also spanned across two screens, and misaligned.

Which one is the USB DisplayLink screen ?

**Comment by dremin** [comment]
Do you see better results if all monitors are set to the same scaling setting?

**Comment by coldacid** [comment]
@mdmk That's Stardock Fences. Also, pretty sure the menubar for the bottom (laptop internal) screen is the one that is split between the top two screens about two thirds of the way down them. The offset of the top-right screen is because of the screen positioning in the display settings since Windows 10 unfortunately doesn't allow pixel-perfect monitor alignment. IIRC the top-left monitor is the one connected USB->DisplayLink->DVI. The other top monitor is DP direct from the laptop.

@dremin We'd have to see this happen again before I could say, but if I did change the laptop monitor to 100% scaling like the other two it'd be unreadable for me. Even when the system is not docked I need it scaled up.

**Comment by mdmk** [comment]
Fences is in wrong position so ?
Try without Fences started.
Stardock tools generally does heavy modifications to Windows,  better to leave it off for test purposes.

As a workaround for what @dremin said, you can lower internal resolution.
It will be ugly and blurry, but bigger.
And no longer high dpi, so not very good idea for a significant test, unless it is totally unrelated.
You can also launch Windows magnification tool when needed, create a shortcut on your desk or taskbar, or use Win + Plus (symbol +) to launch magnification tool easily.

**Comment by dremin** [comment]
@coldacid Understood. I actually somewhat expect the positioning of things to not be correct with per-monitor DPI as that is something I am still working on, but the other issues I see on your screenshot are definitely unexpected. Does this happen every time or has it been mostly OK?

**Comment by coldacid** [comment]
@dremin It's been mostly okay.

**Comment by dremin** [comment]
Is this any better in [this build?](https://ci.appveyor.com/api/buildjobs/7b1dqj6g576w2sd0/artifacts/Installer%2FCairoSetup_64bit.exe)

**Comment by dremin** [comment]
This is fixed in the latest release.
