### ISSUE TITLE
It would be even better to provide a Chinese package.

### ISSUE THREAD

**Issue by yanjinhuagood** [cairoshell/cairoshell#111]
It would be even better to provide a Chinese package.

**Comment by mdmk** [comment]
You're welcome to translate the software if you'd like.
If you are interested in contributing, just reply here or at cairo@cairodesktop.com.

**Comment by yanjinhuagood** [comment]
I download the source code to understand

**Comment by mdmk** [comment]
https://github.com/cairoshell/cairoshell/blob/master/Cairo%20Desktop/CairoDesktop.Localization/Language.cs

**Comment by mdmk** [comment]
Here is the file to modify.
Copy English block (not french, it is not 100% up to date).
Respect indentation and code blocks.
You can do a pull request or post it raw via gist for example if you prefer.

**Comment by mdmk** [comment]
Just replace English strings by Chinese, don't touch ids or anything enclosing the string itself.
Add you're language at the end of the file.

**Comment by yanjinhuagood** [comment]
Okay, no problem.

**Comment by yanjinhuagood** [comment]
My translation will be sent to you Email

**Comment by dremin** [comment]
@yanjinhuagood thanks!

**Comment by yanjinhuagood** [comment]
I Email yanjinhuamail@gmail.com

**Comment by yanjinhuagood** [comment]
Why do many pictures do not choose path

**Comment by yanjinhuagood** [comment]
@dremin I translated the need to send to whom.

**Comment by dremin** [comment]
@yanjinhuagood Please send to cairo@cairodesktop.com Thanks!

**Comment by yanjinhuagood** [comment]
Pay attention to check

**Comment by yanjinhuagood** [comment]
To receive?

**Comment by dremin** [comment]
I got it, thanks!

**Comment by yanjinhuagood** [comment]
Well

**Comment by dremin** [comment]
This will be included in the next release.

**Comment by yanjinhuagood** [comment]
expect

**Comment by dremin** [comment]
This is now available in the latest release.
