### ISSUE TITLE
Make it possible to close windows with middle click in the taskbar

### ISSUE THREAD

**Issue by oxysoft** [cairoshell/cairoshell#115]
Middle click is well established for closing things in tab-like environments. (web browsers, etc.) I have a taskbar modification which lets me do this in Windows, and I find it very intuitive and useful. I think many would find it useful as well.

**Comment by dremin** [comment]
I've added a 'new window' option to the context menu in preparation for this, so that functionality remains regardless of middle-click preference.

**Comment by dremin** [comment]
You know, I quite like this..!

**Comment by dremin** [comment]
This is available in the latest release.
