### ISSUE TITLE
Make it possible to display a parent folder item in the full screen folder browser

### ISSUE THREAD

**Issue by oxysoft** [cairoshell/cairoshell#118]
A folder would be displayed at the start with .. for its name.

I know we can use the dynamic navigation toolbar but I find it kind of annoying.

**Comment by dremin** [comment]
I think it makes sense to add this for when the toolbar is turned off.

**Comment by dremin** [comment]
Closing, the parent folder feature was added to the desktop navigation toolbar. My comment above didn't make sense.
