### ISSUE TITLE
Cairo launches a bunch of programs without reason

### ISSUE THREAD

**Issue by bluemangoop** [cairoshell/cairoshell#119]
It seems to be launching everything in the Startup folder indescriminately; it doesn't check whether programs are enabled or disabled for startup. If I had to guess, it shouldn't be opening anything at all because Windows will probably open things on its own regardless.

**Comment by dremin** [comment]
Cairo runs the contents of the Run registry keys when it is set as shell because Explorer is responsible for this normally. Windows doesn't execute startup programs automatically.

**Comment by dremin** [comment]
This is now available.
