### ISSUE TITLE
Archive support

### ISSUE THREAD

**Issue by bklooste** [cairoshell/cairoshell#12]
One thing i always hated was archive support in Windows /Linux .. a lot of ( non IT literate ) people really struggle with archives and a a UI should take care of it . 

I have even blogged about it . 

http://www.shanghai-software.com/blog/archive/2010/05/13/why-do-we-need-to-deal-with-archives.aspx

**Comment by cairoshell** [comment]
Cairo uses the existing Windows archive support and there are no plans to change this.
