### ISSUE TITLE
Should be able to hide the menu bar like the task bar.

### ISSUE THREAD

**Issue by bluemangoop** [cairoshell/cairoshell#120]
Title says it all

**Comment by AMilkyDeveloper** [comment]
This seems pretty hard as hotswapping allocated window space causes lag. However I can't see the problem in allowing the bar to allocate no space and just pop out.

**Comment by dremin** [comment]
@AMilkyDeveloper Yeah, when we implement this it will not allocate space, rather it will behave similarly to the autohide taskbar.

**Comment by conkerts** [comment]
Hi,
I just discovered cairoshell bc I am totally fed up with windoze explorer.
Cairo looks really amazing, esp how small and efficient it is overall.

Only one thing breaks it for me right now: I can't autohide the menu bar (or at least I can't find the setting).

I really hate it in general, when any bars (that I use under 1% of the time, if I look at my overall usage), take up unnecessary space and esp. precious vertical screen space.

On top of that, I'd also love the force hide option, like there is on xfce:
The bar WILL NEVER pop up, unless YOU want to see it by manually moving the cursor over it.

**Comment by hkdemiralp** [comment]
Autohide menu bar option is very important for preventing OLED burn-ins. Is there any progress for that option?

**Comment by dremin** [comment]
I am working on adding this.

**Comment by ivan8994** [comment]
hello, so how is the progress ?

**Comment by dremin** [comment]
@ivan8994 The code was merged; you can try this test build: https://github.com/cairoshell/cairoshell/actions/runs/7440985782/artifacts/1152860317

**Comment by ivan8994** [comment]
> @ivan8994 The code was merged; you can try this test build: https://github.com/cairoshell/cairoshell/actions/runs/7440985782/artifacts/1152860317

wow thanks, let me try

**Comment by ivan8994** [comment]
> @ivan8994 The code was merged; you can try this test build: https://github.com/cairoshell/cairoshell/actions/runs/7440985782/artifacts/1152860317

hello @dremin thanks for your contribution ! wow that s a huge step forward I believe ! 
so, Ive tested the feature, it indeed works and fully satisfies the basic need of "uncovering" the full power of vertical space

however, there are still several thnigs might be improved, not much but i find this important

let me indicate the typica scenario usage. you have 3-4 different software opened, or you need to close one and minimize another, or you need to switch tab in browser manually with mouse (not ctrl-tab)
it very often happenes that you point the mouse up with a bit overforce an thus "activating" the menu bar to show , and so you need to wait until the menu bar gets hidden and only after that you can now do the job

I beileve this might be solved with following options 
1) create a 1 sec "treshold" so menu bar _**not appears instantly**_ on mouse hover, but after a short period of time
2) an additional option might be added, to adjust the period of time to wait untill the menu bar appears, like from 0.3 sec to 2 sec. so the user can define if he needs non-standart time to wait, or he can go with default one (1 sec)


* * *
thanks !

**Comment by dremin** [comment]
> UPD 1 : there is a **bug** sometimes when you work with smth in tray area ( battery, clock, wi-fi etc) the menu bar stays visible and covers a part of actual opened pogram. And even more, disabling "auto-hide" in settings and re-launching "auto-hide" back does not hellp, the menu bar stays visible anyway

Could you provide more details on the specific steps that cause this? I'm having a hard time reproducing.

> let me indicate the typica scenario usage. you have 3-4 different software opened, or you need to close one and minimize another, or you need to switch tab in browser manually with mouse (not ctrl-tab) it very often happenes that you point the mouse up with a bit overforce an thus "activating" the menu bar to show , and so you need to wait until the menu bar gets hidden and only after that you can now do the job
> 
> I beileve this might be solved with following options
> 
>     1. create a 1 sec "treshold" so menu bar _**not appears instantly**_ on mouse hover, but after a short period of time
> 
>     2. an additional option might be added, to adjust the period of time to wait untill the menu bar appears, like from 0.3 sec to 2 sec. so the user can define if he needs non-standart time to wait, or he can go with default one (1 sec)

That's a good point! I'm adding an option to let you configure the delay.

**Comment by dremin** [comment]
This is now available in the latest release.
