### ISSUE TITLE
Make it possible to open any folder item (in menu bar, in browser, and in jump menu) in Windows File Explorer by middle-clicking

### ISSUE THREAD

**Issue by oxysoft** [cairoshell/cairoshell#125]
- Left-clicking a folder in the menu bar opens it in the jump menu.
- Left-clicking in the jump menu opens in the full-screen browser.
- Left-clicking in the full screen browser enters the folder.

Middle-clicking in any of these should open that folder in the Windows file explorer.

**Comment by dremin** [comment]
This was implemented by @josuave using the shift key rather than middle click.

**Comment by oxysoft** [comment]
That's good, needs to be supported by middle click as well though.

**Comment by dremin** [comment]
Opening a file browser folder icon with a middle click doesn't really follow standard user interface patterns. Is this request to match functionality of some other enhancement you use?

**Comment by dremin** [comment]
Closing due to no response and workaround (shift key) available.
