### ISSUE TITLE
Menu bar has trouble keeping the right size when disconnecting multiple monitors and moving the Windows taskbar

### ISSUE THREAD

**Issue by oxysoft** [cairoshell/cairoshell#132]
I will give more details later, currently not at home where I have access to my second monitor. The menu bar can get stuck in a state where it is not the right width however (it does not fill the horizontal width of the screen, with a vertical Windows taskbar)

**Comment by dremin** [comment]
@oxysoft Do you happen to have details? Does this only happen if the Windows taskbar is vertical? Are you using different DPI settings on each display when this happens?

**Comment by dremin** [comment]
Closing due to no response; feel free to re-open with the requested information.
