### ISSUE TITLE
Aero Snap without Explorer

### ISSUE THREAD

**Issue by NicTanghe** [cairoshell/cairoshell#138]
I was wondering why the windows 10 Window tiling features are removed when cairo replaces the shell.

I am unable to place windows with special + arrowkey

**Comment by dremin** [comment]
Need to investigate if there is an API for this, or if Explorer is assuming the window management functionality here.

**Comment by NicTanghe** [comment]
ps : i  have switched to powertoys for a while now.

**Comment by josuave** [comment]
@dremin do you think it is acceptable to recommend PowerToys - FancyZones  (https://docs.microsoft.com/en-us/windows/powertoys/fancyzones) when running Cairo in Shell Mode?

**Comment by dremin** [comment]
@josuave Good idea! That seems to work well.

**Comment by josuave** [comment]
@NicTanghe I am closing this in as we will be advising people to use PowerToys: FancyZones for the time being.
