### ISSUE TITLE
Very low visual feedback 

### ISSUE THREAD

**Issue by oxysoft** [cairoshell/cairoshell#140]
This is a UX issue. The UI overall of Cairo has very little visual feedback. For example, when my mouse hovers on a menu bar item, they do not light up even a little. Here is an example of the Windows taskbar that I have on my computer for comparison: https://streamable.com/x6ytw It's especially bad in the directory pane and desktop view which have no feedback. All of this overall contributes to make Cairo feel and look buggy, because it always feels it is frozen.

**Comment by dremin** [comment]
This is an area I'd like to improve. Desktop needs the most love in this department. I am not sure about adding hover effects to the menu bar; there actually used to be some which were purposefully removed, but I will consider some options.

**Comment by oxysoft** [comment]
If anything, it could be configurable in the settings.

**Comment by dremin** [comment]
It may be best as a theme, it should already be possible to do this with a [XAML theme](https://github.com/cairoshell/cairoshell/wiki/Creating-Themes).

**Comment by dremin** [comment]
Implemented changes in the latest build.
