### ISSUE TITLE
Feature Request: Run as other user

### ISSUE THREAD

**Issue by Black-Seraph** [cairoshell/cairoshell#141]
For domain administrators that span multiple accounts this is a must have feature.
Just "Run as administrator" doesn't cut it I'm afraid.

**Comment by josuave** [comment]
I personally would recommend having a shift-right click option like explorer does.

Sent from my iPhone

On Apr 28, 2018, at 7:29 PM, Black-Seraph <notifications@github.com<mailto:notifications@github.com>> wrote:


For domain administrators that span multiple accounts this is a must have feature.
Just "Run as administrator" doesn't cut it I'm afraid.

**Comment by dremin** [comment]
This is now available.
