### ISSUE TITLE
Feature requests: bottom menu bar

### ISSUE THREAD

**Issue by pavelxkrejci** [cairoshell/cairoshell#142]
Could there be please optional position for the menu bar at the very bottom of the desktop? I am too used to have it there. Best if task bar could be integrated inside the menu bar, but I would be ok with it being in the second row just above menu bar. Thanks.

**Comment by vapeahoy** [comment]
In games, and such, it remains top layer if game/app is running in borderless mode. This is quite annoying.
It should be possible to move any menus to any sides of the monitor, or position.

**Comment by Amoo0001** [comment]
Please make this very high or critical priority.  The menu bar covers the "X" close icons in a few apps, most notably (to me) Unity.  This is probably the fault of the apps, but nevertheless Cairo is unusable for someone who uses them if we can't reposition, close, hide, auto-hide, style, shrink, or change the dock location of the menu bar in Cairo.  I like Cairo, but I can't use it until there is some way to gain click access to an "X" close icon that opens behind it.

I almost never use GitHub anymore so it's likely I won't see a reply for weeks, so sorry in advance if that happens.  Thank you for reading and considering.

**Comment by lafoxxx92** [comment]
+1!
We can no longer be sure that our mouse cursor is located above the current app's title bar after rapidly (very fast, almost automatically, like we always do) moving the cursor to the very edge of the screen. We have to move the mouse cursor down a few pixels afterwards, which is very resourse-consuming in our current workflow.
