### ISSUE TITLE
[Discussion] Extension points for Cairo

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#145]
Let’s collectively start a discussion about where we want Cairo to have extension points and what the best structure is for them.

**Comment by josuave** [comment]
I chose MEF for its simplicity.

I agree a widget or desktop object infrastructure would be good, like the windows sidebar. I would want the ability to drag them around the screen, maybe have them dock to the screen edges? Also, pin to desktop, floating and “on top” functionality.

Sent from my iPhone

On May 1, 2018, at 10:20 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


I think a good starting place would be widgets on the right side of the menu bar near the notification area and on the left side as well. I think a point for adding features to the Cairo menu, programs menu, and also to the taskbar, could be useful. I was looking at the MEF docs and code and I really like it from what I've seen.

**Comment by dremin** [comment]
Closing in favor of #87
