### ISSUE TITLE
[FEATURE REQUEST] Battery meter and Network status

### ISSUE THREAD

**Issue by psharma04** [cairoshell/cairoshell#146]
I have noticed that Cairo Shell does not have a battery bar or network status in the menu bar. This is an important feature for laptop users, and I was surprised not to find it. Please add this feature to improve the experience of laptop users. Thanks.

**Comment by dremin** [comment]
What version of Windows are you using? These should appear by default with Windows 10.

**Comment by psharma04** [comment]
I'm on Windows 10, and I have selected Cairo as my default shell.

**Comment by Sansyyxd** [comment]
Current ASUS Laptops:
ASUS TUF FX505DY
ASUS T303UA
ASUS K55

**Comment by dremin** [comment]
This is implemented in [this build](https://ci.appveyor.com/api/buildjobs/cx8chb4t09mgeflw/artifacts/Installer%2FCairoSetup_64bit.exe) if you would like to give it a try before release.

**Comment by psharma04** [comment]
Works in Parallels test environment for Windows 10 latest build. I will test on actual hardware soon.

**Comment by dremin** [comment]
Closing due to lack of response. Flyouts will be implemented as part of #54.
