### ISSUE TITLE
Unresponsive Menu Bar after system sleep

### ISSUE THREAD

**Issue by owenworley** [cairoshell/cairoshell#147]
When my PC resumes from sleep, the primary monitor menu bar does not respond to clicks, neither the options on the left or tray icons on the right.

Software Versions:
OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299
Cairo Version 0.3.6654.0 - Pre-release

Reproduction:
Have 2 monitors connected. Primary is 4k (3840x2160), Secondary is 2560x1440. DPI scaling set at 150% in windows 10 for Primary (4k) monitor.

Have Cairo shell not set as windows shell.

Start menu -> Sleep
Resume PC
Try to click menu on primary monitor- it will *not* respond to clicks
Try to click menu on secondary monitor - it will respond to clicks

**Comment by dremin** [comment]
Does the problem happen with DPI set to 100% on the primary monitor?

**Comment by owenworley** [comment]
@dremin I will test with 100% DPI today, sorry I'm so late replying - github wasn't sending me notifications

**Comment by owenworley** [comment]
I just tested at 100% DPI settings on windows for both monitors, and I still see the issue. It does not seem to be related to DPI,

**Comment by dremin** [comment]
Did you sign out of Windows and sign back in after changing to 100% DPI?

**Comment by owenworley** [comment]
No, I will do that now.

**Comment by owenworley** [comment]
Yes. Logged off and on again after chaning to 100%. The issue still occurs.

**Comment by dremin** [comment]
Interesting.. does this only happen when you have enabled the multi-monitor options in Cairo Settings, or does it also happen when you turn that off?

**Comment by owenworley** [comment]
It is happening with "Show menu bar on multiple menus" enabled.
I will disable this setting and test again.

**Comment by owenworley** [comment]
WIth this option disabled enabled, the issue seems to go away.
The menu is present on the primary screen (4k) and not on the secondary, as expected,

**Comment by dremin** [comment]
I've added some additional logging to Cairo to help identify if the problem lies where I think it does. Could you please install [this build](https://ci.appveyor.com/api/buildjobs/h106ig3i5qi0k6lu/artifacts/Installer%2FCairoSetup_64bit.exe), set the logging level to Debug from Cairo Settings > Advanced, restart Cairo, reproduce the issue, and provide the log files for the day from %localappdata%\Cairo_Development_Team\Logs? Thanks!

**Comment by owenworley** [comment]
@dremin Multi monitor taskbar is *enabled* in both cases, enabled or disabled taskbar does not make a difference.

**Comment by owenworley** [comment]
@dremin I will install the test build and attach logs as soon as I can

**Comment by owenworley** [comment]
@dremin Here are the logs you requested.

I DId the following (hopefully it will correlate with the logs)

Closed Cairo. 
Cleared out all old logs. 
Installed the new version. 
Set Logging to Debug (restarted Cairo as prompted).
Put System to Sleep.
Waited until PC was fully asleep.
Resumed from sleep.
Tried to tap menu bar on primary monitor (it is unresponsive as expected)


[05-20-2018.LOG](https://github.com/cairoshell/cairoshell/files/2020711/05-20-2018.-.Copy.LOG)

**Comment by dremin** [comment]
Thank you for the log, much appreciated! To confirm, you did not make any adjustments or unplug/plugin of your displays? Are you using a displaylink adapter or laptop dock?

**Comment by josuave** [comment]
This is unrelated to the current issue but looking at the debug log I think we should add either module or feature information to what is being logged, especially for debug purposes

Sent from my iPhone

On May 21, 2018, at 6:22 AM, Owen Worley <notifications@github.com<mailto:notifications@github.com>> wrote:


No adjustments to Monitor, no plugging in or unplugging.

It is a desktop PC, Both monitors are attached via Display Port to an Nvidia GTX 1080. Monitors are Acer Predator XB281HK (Primary, 4k, Gsync) and Dell UltraSharp™ U2711 (Secondary).

**Comment by owenworley** [comment]
@dremin Tested with the latest build, I still see the same problems.

**Comment by dremin** [comment]
@owenworley Could you please provide the log?

**Comment by owenworley** [comment]
Sorry for the delay, UK bank holiday - family things.

Logs:


[05-28-2018-CairoLog.LOG](https://github.com/cairoshell/cairoshell/files/2046120/05-28-2018-CairoLog.LOG)

**Comment by dremin** [comment]
Thanks, no worries. I took a look and I must have linked the wrong build to you without the extra improvements, sorry about that! (log is from 6683 rather than 6684) Could you please try [this build](https://ci.appveyor.com/api/buildjobs/2hqx5hsat4nahm6i/artifacts/Installer%2FCairoSetup_64bit.exe)?

**Comment by owenworley** [comment]
Of course, downloading now

**Comment by owenworley** [comment]
[05-28-2018 - Copy.LOG](https://github.com/cairoshell/cairoshell/files/2046167/05-28-2018.-.Copy.LOG)

To ocnfirm, issue still present in 0.3.6684.0

**Comment by dremin** [comment]
Thanks for the log! I see the results of my change in there and it doesn’t seem to have fixed the issue, but I have a new idea as to where the problem could be- to confirm, does the issue happen if you set Cairo as shell from Cairo Settings > Advanced, then log out and back in?

**Comment by owenworley** [comment]
@dremin I just tested, and setting Cairo as the shell in advanced settings makes no difference, issue is still present.

**Comment by dremin** [comment]
I have yet another theory, could you please reproduce this issue with [this build](https://ci.appveyor.com/api/buildjobs/6cbequjxedduj7jn/artifacts/Installer%2FCairoSetup_64bit.exe) with Debug logging enabled and upload the log? Thanks!

**Comment by owenworley** [comment]
[07-06-2018 - Copy.LOG](https://github.com/cairoshell/cairoshell/files/2171990/07-06-2018.-.Copy.LOG)

Please find attached a log of the build you posted doing sleep -> resume from sleep.

Interstingly, I am seeing the issue even with just one monitor (the 4k one) attached... I did the test to get the log while i had the 2nd monitor disabled so that I could play my switch on the other one.

This means that the issue reported here happens with just a single monitor attached

**Comment by dremin** [comment]
@owenworley Thanks! Those items help rule out more items. One other thing I thought of: does this happen if the Cairo desktop is disabled?

**Comment by owenworley** [comment]
@dremin This is with the Cairo Desktop *disabled*. I personally prefer classic desktop icons so I have never had it enabled.

**Comment by dremin** [comment]
@owenworley I think I might have fixed this. I was running into a similar issue and found a reliable reproduction. Could you please try [this build](https://ci.appveyor.com/api/buildjobs/d9t7nly0xxovi62j/artifacts/Installer%2FCairoSetup_64bit.exe)?

**Comment by owenworley** [comment]
> @owenworley I think I might have fixed this. I was running into a similar issue and found a reliable reproduction. Could you please try [this build](https://ci.appveyor.com/api/buildjobs/d9t7nly0xxovi62j/artifacts/Installer%2FCairoSetup_64bit.exe)?

I can try, but I have upgraded my monitor setup since this issue and have not been using Cairo.

I will see if my new monitor setup still causes this issue, but apologies in advance if I can no longer reproduce it

**Comment by owenworley** [comment]
Sorry for the delay in responding, finishing up a contract and xmas etc, not had much time spare.

Unfortunately, since changing monitor setup, I do not see the original issue anymore, so I cannot verify if this fix would have fixed the original issue (and I don't have the old monitor anymore as I sold it to a friend as it was obsolete, post upgrade)

Fortunately (for me, I guess) I don't see the original issue at all anymore, so I am back to being a happy Cairo user.

Thanks for investigating this, and Im sorry that couldn't verify the fix - ill try to reach out to my friend and see if I can borrow back the monitor to test this, but not sure how likely that is since we live a long way away from each other now :(

**Comment by owenworley** [comment]
Tested the attached build (0.3.6797/0 prerelease) and it works great, fixes the issue on resume from sleep.

Im going to do a bit more testing, with multiple monitors vs single monitor, etc, and make sure it is fixed for all the scnarios I observed it on before. Will post back later with results

**Comment by owenworley** [comment]
Single 4k monitor, 100% dpi scaling - works
Dual 4k monitors, 100% dpi scaling - works
Dual 4k, + 1 x 1440p widescreen, 100% dpi scaling on all - works
Single 4k monitor, 150% dpi scaling - works
Dual 4k monitors, 150% dpi scaling - works
Dual 4k, + 1 x 1440p widescreen, 150% dpi scaling on 4k, 100% on 1440p - works
Dual 4k, 150% and 100% dpi scaling - works
1440p and single 4k - 100% and 150% dpi scaling - works

Pretty satisfied this is fixed for all the scenarios I saw it happen, good job!

**Comment by owenworley** [comment]
Merry xmas, and I look forward to being able to update back to normal version when you get this merged. !!

**Comment by dremin** [comment]
Awesome, glad it is now fixed for you too! Thank you for the thorough testing :)

**Comment by owenworley** [comment]
> 
> 
> Awesome, glad it is now fixed for you too! Thank you for the thorough testing :)

No worries, happy to help!

**Comment by dremin** [comment]
This fix is now in the latest release. Thanks for all of the help pinning the issue down!
