### ISSUE TITLE
questions about code

### ISSUE THREAD

**Issue by gtsiros** [cairoshell/cairoshell#149]
Cairo Desktop\Startup.cs (224)

```
// close taskbars
Taskbar taskbarToClose = null;
foreach (Taskbar bar in TaskbarWindows)
{
    if (bar.Screen != null && bar.Screen.DeviceName == name)
    {
        taskbarToClose = bar;
        break;
    }
}

if (taskbarToClose != null)
{
    taskbarToClose.Close();
    TaskbarWindows.Remove(taskbarToClose);
}
```
instead,
```
// close taskbars
foreach (Taskbar bar in TaskbarWindows)
{
    if (bar.Screen != null && bar.Screen.DeviceName == name)
    {
        TaskbarWindows.Remove(bar);
        bar.Close();
        break;
    }
}
```
Just this for now, I am still reading through the code to get a feel and see if i can improve anything.
I'm new on github and i'm still fuzzy about many details, apologies.

**Comment by dremin** [comment]
Originally I had null reference issues here because the function was not thread safe. I added a lock since then so it could probably be cleaned up.

**Comment by gtsiros** [comment]
there's more important issues than this, imma close this since it's not really anything pressing. Appreciate your response!
