### ISSUE TITLE
Hiding Windows' Taskbar in Windows 7

### ISSUE THREAD

**Issue by alexey11** [cairoshell/cairoshell#15]
There is no hiding Windows' taskbar when starting this latest build. Cairo from http://www.elementsoftware.co.uk/dev/cairo/ hides it and restarts after Cairo finished. Also, after Cairo finished there are problems with Windows 7 taskbar: pinned buttons void and application buttons grown large. What should i do?
What is the LAST build of Cairo?

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
