### ISSUE TITLE
ALT+TAB While Using a full screen application

### ISSUE THREAD

**Issue by LegacyStackCrash** [cairoshell/cairoshell#150]
While using a full screen application such as a Game or any application that completely covers the Task Bar and Application bar, when you attempt to ALT+TAB the top Task/Folder Bar and bottom Application bar will randomly not appear. Sometimes both do not appear, sometimes one will appear and sometimes both will appear. This happens more commonly with applications that can run in a Border-less Windowed setup. 

Recreation Steps
1. Open application that supports borderless window.
2. Attempt to Alt+Tab back to another window such as a browser or desktop.
3. If both bars appear, attempt to Alt+Tab in and back out. (Normally occurs on the first Alt+Tab)

**Comment by dremin** [comment]
@LegacyStackCrash do you have a specific application that I can try to reproduce this?

**Comment by dremin** [comment]
Closing due to lack of response
