### ISSUE TITLE
Tray popups misplaced on 32-bit

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#151]
Something isn't marshalling right with the CAIROWINNOTIFYICONIDENTIFIER struct on 32-bit systems.

**Comment by josuave** [comment]
What’s the pc setup on this?
32 bit pc and os? 64 bit pc 32 bit os? 64 bit pc and os 32 bit Cairo?

Sent from my iPhone

On May 7, 2018, at 11:49 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Something isn't right with the CAIROWINNOTIFYICONIDENTIFIER struct on 32-bit systems.

**Comment by dremin** [comment]
Reproduces on any OS with 32-bit Cairo. The values of the struct are corrupted in the transition to native code. I suspect it is a data type issue between the version of the struct in NativeMethods.cs and WindowsHooks.h.

**Comment by josuave** [comment]
In doing some research it may be prudent to only allow the 32-bit version of Cairo to run on 32 bit systems. The PInvoke the calls would be accessing 64-bit DLLs

Sent from my iPhone

On May 8, 2018, at 9:06 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Reproduces on any OS with 32-bit Cairo. The values of the struct are corrupted in the transition to native code. I suspect it is a data type issue between the version of the struct in NativeMethods.cs and WindowsHooks.h.

**Comment by dremin** [comment]
Unfortunately that wouldn't solve this particular problem since it happens on pure 32-bit PCs.

**Comment by dremin** [comment]
This is resolved in the latest release.
