### ISSUE TITLE
No way to change wallpaper

### ISSUE THREAD

**Issue by hackaholic5069** [cairoshell/cairoshell#155]
I cannot see a function to change my wallpaper, and i do not enjoy win 10 default in background

**Comment by josuave** [comment]
Are you running Cairo on top of windows or is Cairo set a shell?

**Comment by hackaholic5069** [comment]
i replaced windows explorer shell with cairo, and renamed a few filed to open Fman instead of explorer

**Comment by hackaholic5069** [comment]
btw, i can change the wallpaper by changing it in explorer settings, learned that yesterday...

**Comment by josuave** [comment]
@dremin this can be closed due to latest release
