### ISSUE TITLE
Can not open apps store

### ISSUE THREAD

**Issue by jedr93** [cairoshell/cairoshell#156]
when I want to open any app that I have installed from the store as netflix I get the following message:
shell:appsFolder\4DF9E0F8.Netflix_mcm4njqhhss8!Netflix.App
unregistered class.
how can it be fixed?

**Comment by dremin** [comment]
What version of Windows are you using? Did you select to replace Explorer and use Cairo as Shell?

**Comment by jedr93** [comment]
What version of Windows are you using?
I'm using windows 10 rs4 1803 

Did you select to replace Explorer and use Cairo as Shell?
Yes.

**Comment by dremin** [comment]
Thanks! Explorer is required to launch UWP apps under Windows 10, and I don't anticipate this requirement changing any time soon. :(

**Comment by dremin** [comment]
Closing due to Windows limitation.
