### ISSUE TITLE
Need guidance on how to determine if Cairo Shell is active

### ISSUE THREAD

**Issue by riverar** [cairoshell/cairoshell#157]
We're a third-party app dev. We need the ability to detect if Cairo Shell is running to change some windowing behaviors. Checking for `cairodesktop.exe` process is too heavy.

**Comment by dremin** [comment]
I’d like to implement changes in Cairo to make sure you don’t have to do a workaround like this. What message are you sending, and what’s the expected vs actual result?

**Comment by riverar** [comment]
We're calling `SHAppBarMessage(ABM_GETTASKBARPOS, ...)`. It correctly responds with the position of the Cairo Taskbar. (This API wasn't built with an understanding of split notification area/taskbar.)

**Comment by riverar** [comment]
This issue is to avoid having to implement something like this:
https://github.com/File-New-Project/EarTrumpet/commit/393117b4b7e607f281c572879b3f9235d3385b4b#diff-04e2be4748cbae0bbb78d325d97f49c8L99

**Comment by dremin** [comment]
I believe you're actually getting the rect of the Windows taskbar, since Cairo currently forwards all AppBar messages to Explorer. I'm looking into adding a condition so that Cairo returns the rect of the menu bar for ABM_GETTASKBARPOS messages.

Is it okay if we handle this here and close #158?

**Comment by dremin** [comment]
Provided update in #158. That improvement removes the need to implement special handling logic for Cairo, so closing this.
