### ISSUE TITLE
Need guidance on how to locate notification area on screen

### ISSUE THREAD

**Issue by riverar** [cairoshell/cairoshell#158]
We currently use `SHAppBarMessage` to locate the Taskbar *and* Notification Area to position our window correctly. On Cario, this returns the wrong location for the Notification Area.

**Comment by dremin** [comment]
In the latest commit, Cairo now returns the correct position of the icon from Shell_NotifyIconGetRect. This is how OneDrive positions its popup, and I would suggest a similar approach as it seems to work well with various configurations.

**Comment by riverar** [comment]
@dremin I think you're suggesting we get the icon rect. and calculate which corner we're in. The notification area icons and/or overflow chevron (what `Shell_NotifyIconGetRect` returns when icon is in overflow) could exceed corner boundaries and yield an incorrect corner calculation.

![image](https://user-images.githubusercontent.com/475132/73344935-07854e00-4238-11ea-99c4-a2081667f48b.png)

**Comment by dremin** [comment]
@riverar Correct. One thing you could do is check which screen edge the rect is closest to, then position in the correct corner for a bar on that edge.

As for `ABM_GETTASKBARPOS`, that currently returns the position of the taskbar, which I believe is appropriate given the message name. Cairo breaks some assumptions (1. that the taskbar and notification area are contained within the same AppBar, and 2. that there is only one AppBar hosting a notification area--Cairo can display it on multiple monitors) so changing the response to that message could also provide undesirable results.

**Comment by riverar** [comment]
@dremin That won't work for the reasons I mentioned above. Imagine if `Shell_NotifyIconGetRect` returned this rect.:

![image](https://user-images.githubusercontent.com/475132/73374149-9319d180-426e-11ea-986b-529a338f1a3b.png)

Thanks for reminding me about your implementation of `ABM_GETTASKBARPOS`, I forgot you separate the tray from the taskbar.

**Comment by dremin** [comment]
@riverar I think that logic would still handle that case correctly: the bottom edge of the rect is the edge closest to a screen boundary. Thus, we have a bottom taskbar, so the popup should be positioned in the bottom-right corner (with the top edge of the rect representing the Y coordinate of where the bottom edge of the popup should be).

This could apply to all possible taskbar positions. For example, if the left edge of the rect is the edge closest to a screen boundary, then you can assume there is a left taskbar. If the top edge is the edge closest to a screen boundary, then it's a top taskbar, etc.

**Comment by riverar** [comment]
That's assuming taskbar height isn't altered though, right? If we look for the closest edge in this example, we'd select the top edge and incorrectly assume the taskbar's position

![image](https://user-images.githubusercontent.com/475132/73382300-1988e000-427c-11ea-83ab-d48a0dbcfa15.png)

**Comment by dremin** [comment]
Hm, that would be a problem. How about the window rect of the topmost Shell_TrayWnd window?

**Comment by dremin** [comment]
@riverar We're just going to respond to `ABM_GETTASKBARPOS` with the position of the menu bar that was clicked. In general, with applications using this message, the menu bar ends up being an appropriate placement target, rather than the taskbar. I've tested EarTrumpet with this change and it is positioned correctly.

**Comment by riverar** [comment]
@dremin Sounds good. Been doing a lot of boring administrative stuff on the background, hence our inactivity on EarTrumpet. Appreciate the help.

**Comment by dremin** [comment]
No problem! The change has been released so I am closing this issue.
