### ISSUE TITLE
Help with localization

### ISSUE THREAD

**Issue by guille0301** [cairoshell/cairoshell#16]
I'd like to help localizing CairoShell to es_ES and es_AR, I'd like to have some guidelines or if there is some file with the strings to be replaced.

**Comment by dremin** [comment]
Hi @guille0301, I understand it has been quite a while, are you still interested in helping localize Cairo? I am planning on building localization support, I could then provide a list of strings to you.

**Comment by mdmk** [comment]
I'm interested in translating to fr_FR. Let me know if I can help.

**Comment by dremin** [comment]
Awesome, thanks @mdmk ! I will update this when I have compiled a list of strings to be translated.

**Comment by mdmk** [comment]
Your welcome. I will stay tuned for updates on this issue.

**Comment by mdmk** [comment]
@dremin Any news on this ?

**Comment by dremin** [comment]
@mdmk Yes, I am currently working on the underlying components and getting a list of strings ready. I'll have it soon!

**Comment by dremin** [comment]
@mdmk [Here are the strings for localization](https://gist.github.com/dremin/9794634f8c35a39551f848b2a5d00502). The first string on each line should not be changed (it's the identifier for the string), the second string is the display string that needs to be localized.

Thanks so much for helping out with this!

**Comment by mdmk** [comment]
@dremin 
I'm done with the translation. [Here ](https://gist.github.com/mdmk/0238aa38b481a7312a06deeb58fd19a7) the file.
It will need a bit of proofreading, but I'll wait for a build with localization included If you don't mind.

**Comment by dremin** [comment]
Thank you @mdmk, the translation looks great!

**Comment by dremin** [comment]
Localization support is implemented in the latest build, closing this issue.
