### ISSUE TITLE
[Feature Request] Impliment file specific right click menus - like explore

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#160]
Implement whatever standard right click options that are available for file type and explore including shift right click. The registry contains all of the file type information and the classes hive. Of course we won’t be able implement some of the explore extension actions.

**Comment by dremin** [comment]
Aren’t these already implemented? File verbs should be there. Or am I misunderstanding?

**Comment by josuave** [comment]
I apologize, I will review the code again and will amend or close this

Sent from my iPhone

On Jun 18, 2018, at 12:00 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Aren’t these already implemented? File verbs should be there. Or am I misunderstanding?

**Comment by josuave** [comment]
I see my confusion on the matter. Explorer differentiates from standard and extended verbs. This should be closed unless it is desired that Cairo also follows that same functionality
