### ISSUE TITLE
Error message when running app grabber

### ISSUE THREAD

**Issue by jonathands** [cairoshell/cairoshell#161]
**Describe the bug**

**Steps to reproduce**
1. installed 
2. run welcome tutorial to the last step
3. opened app grabber via menu and closed it
4. finished tutorial opening app grabber

**Expected behavior**
No error message or crash

**System information:**
 - Windows version: 10
 - Cairo version: lastest stable
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: no

**Screenshots**
![image](https://user-images.githubusercontent.com/959141/41678572-c38e5fee-74a1-11e8-8c2c-c01577eae6fd.png)

**Comment by dremin** [comment]
Does this happen every time you use App Grabber and click Continue, or have you been unable to reproduce?

**Comment by jonathands** [comment]
no, i could not reproduce after I installed, i think i'd need to reinstall and follow a very specific order of actions (using appgraber from tutorial after using other features), maybe its not that worth to look into

**Comment by dremin** [comment]
Okay, feel free to re-open this if you are able to reproduce!
