### ISSUE TITLE
Taskbar hides when coming from full screen app

### ISSUE THREAD

**Issue by postbluecz** [cairoshell/cairoshell#165]
Hi,
I noticed that when I come from a full screen app (like Remote Desktop), Taskbar hides when it is set up for anything other than "Taskbar reserves space" in the Cairo settings. It would be nice if it would behave as expected - appearing again after exiting from full screen app.

Tom

**Comment by dremin** [comment]
This should be resolved in the latest release. Please re-open if you continue to have this issue.
