### ISSUE TITLE
Start task manager crash

### ISSUE THREAD

**Issue by wetherbeei** [cairoshell/cairoshell#17]
Windows 7 x64

Application Domain:    CairoDesktop.exe
Assembly Codebase:     file:///C:/Users/Ian/Downloads/CairoShell/Release/CairoDesktop.exe
Assembly Full Name:    CairoDesktop, Version=0.0.1.9, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.0.1.9
Assembly Build Date:   4/15/2010 9:18:52 PM

Exception Source:      System
Exception Type:        System.ComponentModel.Win32Exception
Exception Message:     The system cannot find the file specified
Exception Target Site: StartWithShellExecuteEx

---- Stack Trace ----
   System.Diagnostics.Process.StartWithShellExecuteEx(startInfo As ProcessStartInfo)
       CairoDesktop.exe: N 00614
   System.Diagnostics.Process.Start()
       CairoDesktop.exe: N 00056
   System.Diagnostics.Process.Start(startInfo As ProcessStartInfo)
       CairoDesktop.exe: N 00049
   System.Diagnostics.Process.Start(fileName As String)
       CairoDesktop.exe: N 00031
   CairoDesktop.MenuBar.OpenTaskManager(sender As Object, e As RoutedEventArgs)
       MenuBar.xaml.cs: line 0368, col 13, IL 0000
   System.Windows.RoutedEventHandlerInfo.InvokeHandler(target As Object, routedEventArgs As RoutedEventArgs)
       CairoDesktop.exe: N 00119
   System.Windows.EventRoute.InvokeHandlersImpl(source As Object, args As RoutedEventArgs, reRaised As Boolean)
       CairoDesktop.exe: N 00446
   System.Windows.UIElement.RaiseEventImpl(sender As DependencyObject, args As RoutedEventArgs)
       CairoDesktop.exe: N 00120
   System.Windows.UIElement.RaiseEvent(e As RoutedEventArgs)
       CairoDesktop.exe: N 00022
   System.Windows.Controls.MenuItem.InvokeClickAfterRender(arg As Object)
       CairoDesktop.exe: N 00088
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, isSingleParameter As Boolean)
       CairoDesktop.exe: N 00137
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(source As Object, callback As Delegate, args As Object, isSingleParameter As Boolean, catchHandler As Delegate)
       CairoDesktop.exe: N 00073

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
