### ISSUE TITLE
Removing stroke from bar in XAML file

### ISSUE THREAD

**Issue by risemix** [cairoshell/cairoshell#173]
I realize this isn't a support forum and that this is maybe beyond the scope of what is supposed to be discussed here, but I can't find a better place to ask, so I hope it's all right.

I'm trying to create a simple transparent theme for the top bar using white.xaml as a starting point.  I am not a developer nor am I actually that familiar with the syntax, but I do know CSS and some HTML so I was able to do most of what I want by referencing the default theme and making a few changes.

There is a small gray stroke at the bottom of the bar that I wish to remove but I can't parse exactly what style is controlling that or how to change it.

The file I currently have looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<ResourceDictionary xmlns="http://schemas.microsoft.com/netfx/2009/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <!-- Menu resources -->
    <SolidColorBrush Color="#FFFFFFFF" x:Key="MenuHeaderForeground" />
    <SolidColorBrush Color="#FFFFFFFF" x:Key="SysTrayExpanderColor" />

    <!-- Image resources -->
    <BitmapImage x:Key="MenuIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/cairoMenuDefault.png"></BitmapImage>
    <BitmapImage x:Key="SearchIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/searchDefault.png"></BitmapImage>
    <BitmapImage x:Key="ActionCenterIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/actionCenterDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeLowIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeLowIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeOffIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeOffIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeMuteIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeMuteIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="WhiteBarBackground" UriSource="C:\Users\epatt\OneDrive\Pictures\bar\menuBarTransparent.png"></BitmapImage>
</ResourceDictionary>
```
The image is attached below.  How can I achieve a transparent "stroke" so to speak?

![2018-07-25_15-53-21](https://user-images.githubusercontent.com/23641219/43212396-2579f788-9034-11e8-8145-b98a1eb82342.png)

**Comment by josuave** [comment]
Are you looking for something like these effects ?
[image1.jpeg]
Sent from my iPhone

On Jul 25, 2018, at 11:58 AM, risemix <notifications@github.com<mailto:notifications@github.com>> wrote:


I realize this isn't a support forum and that this is maybe beyond the scope of what is supposed to be discussed here, but I can't find a better place to ask, so I hope it's all right.

I'm trying to create a simple transparent theme for the top bar using white.xaml as a starting point. I am not a developer nor am I actually that familiar with the syntax, but I do know CSS and some HTML so I was able to do most of what I want by referencing the default theme and making a few changes.

There is a small white stroke at the bottom of the bar that I wish to remove but I can't parse exactly what style is controlling that or how to change it.

The file I currently have looks like this:

<?xml version="1.0" encoding="utf-8"?>
<ResourceDictionary xmlns="http://schemas.microsoft.com/netfx/2009/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    
    <SolidColorBrush Color="#FFFFFFFF" x:Key="MenuHeaderForeground" />
    <SolidColorBrush Color="#FFFFFFFF" x:Key="SysTrayExpanderColor" />
    <SolidColorBrush Color="Transparent" x:Key="menuBarStroke" />

    
    <BitmapImage x:Key="MenuIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/cairoMenuDefault.png"></BitmapImage>
    <BitmapImage x:Key="SearchIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/searchDefault.png"></BitmapImage>
    <BitmapImage x:Key="ActionCenterIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/actionCenterDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeLowIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeLowIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeOffIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeOffIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="VolumeMuteIcon" UriSource="pack://application:,,,/CairoDesktop;component/Resources/volumeMuteIconDefault.png"></BitmapImage>
    <BitmapImage x:Key="WhiteBarBackground" UriSource="C:\Users\epatt\OneDrive\Pictures\bar\menuBarTransparent.png"></BitmapImage>
</ResourceDictionary>


The image is attached below. How can I achieve a transparent "stroke" so to speak?

[2018-07-25_15-53-21]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F23641219%2F43212396-2579f788-9034-11e8-8145-b98a1eb82342.png&data=02%7C01%7C%7C216b87bcb83448b04a1f08d5f2478624%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636681311359730732&sdata=xhwzhTMb%2FJKeuO2axWBZgeEWOTTmu9CxXUnUX2xMftY%3D&reserved=0>

**Comment by risemix** [comment]
You haven't attached an image.

**Comment by josuave** [comment]
Ahhh, looks like it got stripped

Sent from my iPhone

On Jul 25, 2018, at 1:31 PM, risemix <notifications@github.com<mailto:notifications@github.com>> wrote:


You haven't attached an image.

**Comment by dremin** [comment]
Is this with the menu bar shadow enabled or disabled? I’m currently traveling but I believe that is where this line comes from.

**Comment by risemix** [comment]
Shadow is disabled.

**Comment by josuave** [comment]
Are you trying to get a gloss look almost like it’s made of smooth plastic or glass???

Sent from my iPhone

On Jul 25, 2018, at 1:58 PM, risemix <notifications@github.com<mailto:notifications@github.com>> wrote:


Shadow is disabled.

**Comment by risemix** [comment]
I'm trying to get only the text and icons without any background whatsoever. :)

For those of you familiar with Elementary OS, something like that.

https://distrowatch.com/images/cgfjoewdlbc/elementary-small.png For example.

**Comment by josuave** [comment]
Ahhh. You want no background what so ever.

Sent from my iPhone

On Jul 25, 2018, at 2:13 PM, risemix <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to get only the text and icons without any background whatsoever. :)

For those of you familiar with Elementary OS, something like that.

https://distrowatch.com/images/cgfjoewdlbc/elementary-small.png<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdistrowatch.com%2Fimages%2Fcgfjoewdlbc%2Felementary-small.png&data=02%7C01%7C%7Cb02c8b7050d04ae4db3c08d5f25a450e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636681391866949293&sdata=V%2F9TPShBDB33JQ7HHxEjWY8t7iRtaz6tkl8960bDnNs%3D&reserved=0> For example.

**Comment by dremin** [comment]
@risemix looks like it is in MenuBar.xaml line 9 so it isn't customizable. I will address this in an update so that you can tweak that line.

**Comment by risemix** [comment]
That's awesome.  Thanks so much!  

Afterwards, I'll release the skin somewhere so it can be used by whoever wants it, although it is a pretty simple one.

**Comment by dremin** [comment]
Once this is released, add the following brush to your theme to make the bottom stroke transparent:
`<SolidColorBrush Color="Transparent" x:Key="MenuBarBorder" />`

**Comment by dremin** [comment]
This has been released.

**Comment by risemix** [comment]
https://i.imgur.com/W2W1yMD.png

Thank you, it works great. :)
