### ISSUE TITLE
Spotify icon does not appear in notification area.

### ISSUE THREAD

**Issue by rndthoughts** [cairoshell/cairoshell#174]
**Describe the bug**

When you start Spotify, the icon does not appear in the notification area.  Same occurs with "Close button should minimise the Spotify window to the tray" enabled.  Normal minimise works fine.

**Steps to reproduce**
1.  Open Spotify
2. Check notification area - no icon present.

**Expected behavior**

The Spotify icon should appear in the notification area.

**System information:**
 - Windows version: Windows 10 Pro
 - Cairo version: 0.3.6693.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Comment by dremin** [comment]
Thanks for reporting this! I've implemented a fix that will be in the next release.

**Comment by dremin** [comment]
The fix has been released.
