### ISSUE TITLE
Transparent Menu Bar Backgrounds aren't interactable

### ISSUE THREAD

**Issue by risemix** [cairoshell/cairoshell#177]
**Describe the bug**
When you use a transparent menu bar background, the area behind the text is not interactable. You must click precisely on the text/icon in order to activate the Programs menu, search area, etc. 

**Steps to reproduce**
1. Set a theme with a transparent background (I have attached mine to make it easier)
2. Try to click the area around the letters

**Expected behavior**
I would expect that clicking an area around the text would activate the menu, even if I'm not clicking precisely on the the white text area.

**System information:**
 - Windows version: Windows 10 64-bit
 - Cairo version:  0.3.6701.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No, but I have tried it as shell and not as shell.

**Additional context**
I understand that this will not be a high priority issue and I feel a little bit bad for bringing it up, since it's a very specific use case.  However I figured you guys might still want to know about it. :)

**Screenshots**
https://i.imgur.com/jRZd6Mb.gifv  Hard to show with a GIF, but I tried.

I have also attached my theme below.  Just extract the files to your Cairo Shell directory.  The XAML assumes the default install path of C:\Program Files\Cairo Shell.  

[Transparent.zip](https://github.com/cairoshell/cairoshell/files/2260686/Transparent.zip)

**Comment by risemix** [comment]
I'm traveling at the moment but I will try it when I'm back at my desk.

**Comment by dremin** [comment]
Closing, workaround provided to a framework issue
