### ISSUE TITLE
Notification area missing icons and other weirdness

### ISSUE THREAD

**Issue by martinsstuff** [cairoshell/cairoshell#178]
**Describe the bug**
Icons shown in normal explorer desktop aren't shown in Cairo desktop.

Examples:

Nvidia Control Panel

SimpleDNSCrypt Control Panel

Realtek Audio

ProtonVPN Client

NetSetMan

**Steps to reproduce**
1. Have these applications installed and in the notification area.

**Expected behavior**
Icons are visible in Cairo too.

**System information:**
 - Windows version: Win 10 1803 fully up to date
 - Cairo version: M3.6701
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**
![2018-08-05_20-54-22](https://user-images.githubusercontent.com/29005772/43692090-5ba0c99c-98f2-11e8-8b05-cacaf51ba378.png)
![2018-08-05_20-55-14](https://user-images.githubusercontent.com/29005772/43692098-65061636-98f2-11e8-950c-b27017895a56.png)

EDIT: For some reason the Wallpaper Engine icon is ONLY displayed in Cairo and not Explorer?

I think the SimpleDNSCrypt icon actually showed up in Cairo at some point (had now way to check exactly, just guessing from the context menu options) as an empty icon and even when I exited Cairo it stayed that way until reboot in Explorer's notifications menu.

The notifications area seems to have really weird bugs at the moment that somehow carry over to Explorer too.

**Comment by dremin** [comment]
Do the icons appear if you restart the app it belongs to while Cairo is running?

Unfortunately the "other weirdness" part of this may not be addressable due to the lack of support for multiple notification areas in Windows' APIs.

**Comment by martinsstuff** [comment]
> Do the icons appear if you restart the app it belongs to while Cairo is running?

They don't, but sometimes icons of new applications show up and after restarts some icons that didn't show up before now do, I feel like there is some sort of "battle"  between explorer and cairo who "claims" icons that persists app relaunches?

**Comment by dremin** [comment]
Whichever is “topmost” will get the icon. Do you have the Cairo taskbar disabled and are instead using the Windows one? I can see how this could cause Explorer to get the icon instead.

**Comment by martinsstuff** [comment]
![image](https://user-images.githubusercontent.com/29005772/43815119-12ecc1aa-9a9c-11e8-83b1-dd11996c04ee.png)

Nope, I use the Cairo task bar, when booting it shows the Windows one for a bit and hides it, do you mean that?

**Comment by beppe9000** [comment]
I'm not sure if mine is the same problem, but I have missing icons when running cairo as administrator.
Could be that if I run cairo as admin the unpriviledged apps cannot put the icons in the notification area?

**Comment by dremin** [comment]
@beppe9000 Interesting, is it only certain apps that do this? The notification area in Windows relies on window messages, which I suppose could have limitations around elevated app windows.

**Comment by beppe9000** [comment]
I don't remember the exact apps but they were all launched without elevation at startup time. Maybe some unelevated helper instance could be used to double check icons. Or some other way to get the content of notification area (accessibility features ?).

**Comment by dremin** [comment]
@beppe9000 I have done some testing and elevated apps seem to appear fine in the notification area when Cairo is not running as an admin. Is there a reason why you are running Cairo as admin? If it was due to the taskbar issues with elevated apps, that should now be resolved.

**Comment by beppe9000** [comment]
thanks, I'll give it another try

**Comment by dremin** [comment]
Closing due to third party issue.
