### ISSUE TITLE
Add option to show Hibernate button in menu

### ISSUE THREAD

**Issue by martinsstuff** [cairoshell/cairoshell#179]
**Is your feature request related to a problem? Please describe.**
I'd like to use a simple button in the menu to hibernate my machine. Currently it only has sleep, restart, shutdown and logout.

**Describe the solution you'd like**
A hibernate button.

As some people don't use it I specifically suggest an option to hide it. I personally use it as sleep can corrupt data if power is cut.

**Describe alternatives you've considered**
Just press the windows key and do it from there? I guess the intention is to replace it at some point though.

**Additional context**
Nothing

**Comment by dremin** [comment]
This is available in the latest release.
