### ISSUE TITLE
Crash on right-click on Steam icon

### ISSUE THREAD

**Issue by wetherbeei** [cairoshell/cairoshell#19]
Right-clicking the Steam taskbar icon causes a crash. Probably something to do with Steam's custom UI.

Windows 7 x64

Application Domain:    CairoDesktop.exe
Assembly Codebase:     file:///C:/Users/Ian/Downloads/CairoShell/Release/CairoDesktop.exe
Assembly Full Name:    CairoDesktop, Version=0.0.1.9, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.0.1.9
Assembly Build Date:   4/15/2010 9:18:52 PM

Exception Source:      PresentationFramework
Exception Type:        System.InvalidOperationException
Exception Message:     'Border' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.
Exception Target Site: ResolveTargetName

---- Stack Trace ----
   System.Windows.Media.Animation.Storyboard.ResolveTargetName(targetName As String, nameScope As INameScope, element As DependencyObject)
       CairoDesktop.exe: N 1793274
   System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(currentClock As Clock, containingObject As DependencyObject, nameScope As INameScope, parentObject As DependencyObject, parentObjectName As String, parentPropertyPath As PropertyPath, handoffBehavior As HandoffBehavior, clockMappings As HybridDictionary, layer As Int64)
       CairoDesktop.exe: N 00404
   System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(currentClock As Clock, containingObject As DependencyObject, nameScope As INameScope, parentObject As DependencyObject, parentObjectName As String, parentPropertyPath As PropertyPath, handoffBehavior As HandoffBehavior, clockMappings As HybridDictionary, layer As Int64)
       CairoDesktop.exe: N 01113
   System.Windows.Media.Animation.Storyboard.BeginCommon(containingObject As DependencyObject, nameScope As INameScope, handoffBehavior As HandoffBehavior, isControllable As Boolean, layer As Int64)
       CairoDesktop.exe: N 00266
   System.Windows.Media.Animation.BeginStoryboard.Begin(targetObject As DependencyObject, nameScope As INameScope, layer As Int64)
       CairoDesktop.exe: N 00095
   System.Windows.Media.Animation.BeginStoryboard.Invoke(fe As FrameworkElement, fce As FrameworkContentElement, targetStyle As Style, frameworkTemplate As FrameworkTemplate, layer As Int64)
       CairoDesktop.exe: N 00035
   System.Windows.StyleHelper.InvokeEventTriggerActions(fe As FrameworkElement, fce As FrameworkContentElement, ownerStyle As Style, frameworkTemplate As FrameworkTemplate, childIndex As Int32, Event As RoutedEvent)
       CairoDesktop.exe: N 00251
   System.Windows.StyleHelper.ExecuteEventTriggerActionsOnContainer(sender As Object, e As RoutedEventArgs)
       CairoDesktop.exe: N 00220
   System.Windows.RoutedEventHandlerInfo.InvokeHandler(target As Object, routedEventArgs As RoutedEventArgs)
       CairoDesktop.exe: N 00119
   System.Windows.EventRoute.InvokeHandlersImpl(source As Object, args As RoutedEventArgs, reRaised As Boolean)
       CairoDesktop.exe: N 00446
   System.Windows.UIElement.RaiseEventImpl(sender As DependencyObject, args As RoutedEventArgs)
       CairoDesktop.exe: N 00120
   System.Windows.UIElement.RaiseEvent(e As RoutedEventArgs)
       CairoDesktop.exe: N 00022
   System.Windows.BroadcastEventHelper.BroadcastEvent(root As DependencyObject, routedEvent As RoutedEvent)
       CairoDesktop.exe: N 00305
   System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(root As Object)
       CairoDesktop.exe: N 00168
   MS.Internal.LoadedOrUnloadedOperation.DoWork()
       CairoDesktop.exe: N 00021
   System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       CairoDesktop.exe: N 00112
   System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       CairoDesktop.exe: N 00047
   System.Windows.Media.MediaContext.RenderMessageHandlerCore(resizedCompositionTarget As Object)
       CairoDesktop.exe: N 00127
   System.Windows.Media.MediaContext.RenderMessageHandler(resizedCompositionTarget As Object)
       CairoDesktop.exe: N 00042
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, isSingleParameter As Boolean)
       CairoDesktop.exe: N 00137
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(source As Object, callback As Delegate, args As Object, isSingleParameter As Boolean, catchHandler As Delegate)
       CairoDesktop.exe: N 00073

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
