### ISSUE TITLE
Calendar pop out: Current date only refreshing when another date is clicked in the calendar.

### ISSUE THREAD

**Issue by martinsstuff** [cairoshell/cairoshell#195]
**Describe the bug**
The current date doesn't update automatically in the pop out menu (filled blue selection), selecting another date (any works, selection with blue stroke) causes it refresh and be correct.

**Steps to reproduce**
1. Launch Cairo and wait a day (changing system clock works too).
2. Open the pop out, data should show yesterday.
3. Click any other date, current date should refresh.

**Expected behavior**
Displayed date in the pop out should be accurate.

**System information:**
 - Windows version: Win 10 64-bit all updated.
 - Cairo version: 0.3.6701.0 (M3.6701)
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No, as it breaks Wallpaper engine :( (Their issue)

**Additional context**
Nothing

**Screenshots**
(GIF)
![2018-08-27_10-47-48](https://user-images.githubusercontent.com/29005772/44666673-e8511400-a9e6-11e8-8a6a-f809fb0ab0a2.gif)

**Comment by dremin** [comment]
This is fixed in the latest release.
