### ISSUE TITLE
Taskbar not at the bottom of the screen

### ISSUE THREAD

**Issue by gaberade** [cairoshell/cairoshell#2]
Running Cairo on Win7.

If you start cairo before terminating explorer.exe, the cairo taskbar rests on top of the explorer taskbar and stays in that position, even if you 
-terminate explorer.exe
-disable and then re-enable the taskbar via cairo settings
-restart cairo from "New Task" in the TaskManager

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
