### ISSUE TITLE
App Grabber Bug

### ISSUE THREAD

**Issue by jewalla** [cairoshell/cairoshell#201]
**Describe the bug**
After installing Cairo and starting app grabber, the shell crashes after the splash screen appears. After the crash my wallpaper blacks out and both shells do not start, forcing me to restart my PC.

**Steps to reproduce**
1. Install Cairo
2. Start app grabber
3. Restart PC

**Expected behavior**
After installation and starting app grabber, the splash screen shows that the apps are being searched. Then Cairo force closes, causing my wallpaper to black out and both shells not opened. I am forced to restarting my pc in order for shell to restart. 

**System information:**
 - Windows version: Windows 10 Home x 64
 - Cairo version: Latest Version
 - 32-bit or 64-bit: 64- bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Comment by dremin** [comment]
Do  you have the crash log that appears when Cairo crashed?

**Comment by dremin** [comment]
Closing due to no response
