### ISSUE TITLE
German Language Support

### ISSUE THREAD

**Issue by saigkill** [cairoshell/cairoshell#204]
**Is your feature request related to a problem? Please describe.**
I would like to have a german localized cairoshell

**Describe the solution you'd like**
A solution could be to create some language files. If you could explain, how to do this, i can maybe help out to translate the strings.

**Comment by josuave** [comment]
Fell free to fork the repository and contribute!
The code you want to look at is in this area
https://github.com/cairoshell/cairoshell/tree/master/Cairo%20Desktop/CairoDesktop.Localization
Language.cs

Find the locale code for the specific German you want to add, I.e de-DE.  Cope and paste one of the other languages, change the variable name to the locale and start translating.



Sent from my iPhone

On Sep 21, 2018, at 9:48 AM, Sascha Manns <notifications@github.com<mailto:notifications@github.com>> wrote:


Is your feature request related to a problem? Please describe.
I would like to have a german localized cairoshell

Describe the solution you'd like
A solution could be to create some language files. If you could explain, how to do this, i can maybe help out to translate the strings.

**Comment by Revoluzifer** [comment]
This has already been done - in a previous pull request.
Should already have been integrated into master but has yet to be built into a release.

**Comment by dremin** [comment]
This will be included in the next release 😃
