### ISSUE TITLE
/Finished/ Spanish Language Support!

### ISSUE THREAD

**Issue by JiachengLiu13579** [cairoshell/cairoshell#207]
Hola )there´s a English version below),  

Me encanta Cario como una sustitución del explorer.exe y me ha servado bien en ambos Windows 7 y 10. Pero lo he usado en Portugués. No me daba mucha carta(eu tanbem falo Portugués) pero había esperado tanto que decidí traducir Cairo en Español. 
La traducción en Portuguese me inspiraba cuando estaba tranduciendo. Gracias al traductor de Portuguése, 

A tradução do Portugues me inspirava muito. Muitíssimos obrigados ao tradutor!
Aqui tiene la traduccion en Google Doc
https://docs.google.com/document/d/1mnAc9ULx6mApsN3Detz7wfCHxHXuXLeHh-3XpAh5Fgk/edit?usp=sharing

Por favor, arreglen los errores si pueden. ¿Gracias!

Hi

I love Cairo as a desktop replacement! I have been using it in Portuguese ever since I got it but I have been waiting for a Spanish translation for a long time. So long that I decided to translate the software by myself. Here´s the link to it:
https://docs.google.com/document/d/1mnAc9ULx6mApsN3Detz7wfCHxHXuXLeHh-3XpAh5Fgk/edit?usp=sharing

Feel free to correct gramatical mistakes as I will be online very often

**Comment by makmm** [comment]
Hola! Acá en GitHub tendrias que empezar una "pull request" para poner codigo en cairo (o en cualquier otro repositorio de Github.) Si queres puedo usar lo que ya hiciste y corregir unas cosas, y crear la pull request por vos. Te parece bien? @JiachengLiu13579 

---

^^^ explaining to the submitter that they should to create a pull request for this and that I could do that for them.

**Comment by JiachengLiu13579** [comment]
> Hola! Acá en GitHub tendrias que empezar una "pull request" para poner codigo en cairo (o en cualquier otro repositorio de Github.) Si queres puedo usar lo que ya hiciste y corregir unas cosas, y crear la pull request por vos. Te parece bien? @JiachengLiu13579
> 
> ^^^ explaining to the submitter that they should to create a pull request for this and that I could do that for them.

Hecho. Había algunos errores que impedía las actualizaciones que funcionaran pero ahora está todo bien

Gracias!

**Comment by dremin** [comment]
Thanks for helping out! This will be included in the next release.

**Comment by JiachengLiu13579** [comment]
Thanks! I am working on a Latin translation now. I know it sounds odd, but that is what I am actually studying:). Great software like Minecraft needs their Latin translation, so does Cairo
