### ISSUE TITLE
Not sure if there are forums, so I was posting here.

### ISSUE THREAD

**Issue by trusktr** [cairoshell/cairoshell#21]
The desktop interface looks cool, but what about window borders? Are those modified so that the windows match the style of the desktop??? That's a key feature i think.

**Comment by cairoshell** [comment]
Cairo is alive and well; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Window borders are not modified and there are no plans to do this as it is outside of the planned scope of Cairo. Thanks!
