### ISSUE TITLE
[BUG][Multimonitor] Menu bar doesn't appear on additional monitors in multi-DPI environment

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#213]
**Describe the bug**
In an environment where the primary monitor has a different DPI setting than the other monitors, Cairo does not show the Menu Bar except on the primary monitor. Space is allocated on the non-primary monitors but no UI is rendered. This happens regardless of the "Blur behind the Menu Bar" and "Enable Menu Bar shadow" options on the Menu Bar settings tab, or the "Force software rendering" option on the Advanced tab.

**Steps to reproduce**
1. In Windows Settings, on the System > Display page, set the "Change the size of text, apps and other items" value for monitor 1 to 125%. Ensure that the value for the other monitors stays at 100%.
2. Open Cairo Settings and enable the "Show Menu Bar on multiple monitors" option.
3. Restart Cairo.

**Expected behavior**
The Cairo menu bar is duplicated on the non-primary monitors.

**System information:**
 - Windows version: Windows 10 version 1803 (OS Build 17134.345)
 - Cairo version: 0.3.6746.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**

![Primary monitor - Cairo menu bar](https://user-images.githubusercontent.com/130681/47921744-be571a80-de8b-11e8-86ca-ec214d9e36ec.png)

Here's the Cairo menu bar as it appears on the primary monitor.

![Secondary monitors - no Cairo menu bar](https://user-images.githubusercontent.com/130681/47921866-07a76a00-de8c-11e8-8f2b-a09a0421a2fe.png)

Here's what the top of my non-primary monitors look like with the "Show Menu Bar on multiple monitors" option enabled. Space is properly allocated for the menu bar to appear, but nothing is actually rendered.

**Comment by dremin** [comment]
Is this any better in [this build?](https://ci.appveyor.com/api/buildjobs/7b1dqj6g576w2sd0/artifacts/Installer%2FCairoSetup_64bit.exe)

**Comment by dremin** [comment]
This is fixed in the latest release.
