### ISSUE TITLE
Cairo draws over fullscreen applications?

### ISSUE THREAD

**Issue by theplasticbling** [cairoshell/cairoshell#216]
Is Cairo supposed to draw over fullscreen applications? I use Steam Big Picture mode as my shell and start Cairo on boot. It draws over Steam running in fullscreen. Is it possible to have Cairo not draw over fullscreen apps? Thanks!

**Comment by dremin** [comment]
Do you have Cairo set as shell (replacing Explorer)? Currently (and I am looking to improve this), Cairo relies on full screen app notifications from Explorer, so it is expected overlap full screen apps in that scenario.

**Comment by theplasticbling** [comment]
> Do you have Cairo set as shell (replacing Explorer)? Currently (and I am looking to improve this), Cairo relies on full screen app notifications from Explorer, so it is expected overlap full screen apps in that scenario.

I actually have Steam set as my shell. I open up Cairo afterwards.

**Comment by dremin** [comment]
Okay, that makes sense as you don’t have Explorer running any more. My suggestion for now would be to re-enable Explorer as your shell and then Cairo will respect full screen apps. I do plan on fixing this in the near future.

**Comment by theplasticbling** [comment]
Ok thanks. I use Steam Big Picture as my shell so I'll just have to wait for the fix. I wish you luck!

**Comment by dremin** [comment]
This is fixed in the latest release.
