### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by beppemarazzi** [cairoshell/cairoshell#218]
Cannot find information about license for this project...
Who is the copyright holder?
What's about contribution policy?
https://choosealicense.com/no-permission/

**Comment by dremin** [comment]
Sorry, I meant to clear this up a while ago. I’m switching Cairo to the Apache license. I’ll try to get things updated soon!

**Comment by beppemarazzi** [comment]
Great.  Many thanks

**Comment by dremin** [comment]
I've updated the license!
