### ISSUE TITLE
Cairo non-responsive

### ISSUE THREAD

**Issue by mhgamework** [cairoshell/cairoshell#22]
Hey,

When i start cairo, the top bar appears, but it grays out after a few seconds. When i click on the bar, the application stops responding and crashes.
Im on a Windows 7 Home Premium 64-bit. I got this from the event log but im not entirely sure its usefull

> Faulting application name: rundll32.exe, version: 6.1.7600.16385, time stamp: 0x4a5bc637
> Faulting module name: ntdll.dll, version: 6.1.7601.17514, time stamp: 0x4ce7ba58
> Exception code: 0xc0000005
> Fault offset: 0x000a1cf8
> Faulting process id: 0x80
> Faulting application start time: 0x01cccb95ace785be
> Faulting application path: C:\Windows\SysWOW64\rundll32.exe
> Faulting module path: C:\Windows\SysWOW64\ntdll.dll
> Report Id: eb04e51e-3788-11e1-8718-14feb5b07781

Can anyone help me?

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
