### ISSUE TITLE
Example Extension

### ISSUE THREAD

**Issue by furesoft** [cairoshell/cairoshell#222]
please provide an example extension or a tutorial in wiki

**Comment by josuave** [comment]
We do have an extension you can use for reference. It’s located at https://github.com/cairoshell/cairoshell/tree/master/Cairo%20Desktop/Extensions/CairoDesktop.Extensions.Places.ShellFolders

On Dec 27, 2018, at 5:25 AM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Great idea, will do! The extension api is not close to finished so it will be a living document.

**Comment by dremin** [comment]
https://github.com/cairoshell/CairoExtensionSamples
