### ISSUE TITLE
Cairo stretches my wallpaper when using it as a shell

### ISSUE THREAD

**Issue by stelios53** [cairoshell/cairoshell#226]
cairo:
![cairo](https://user-images.githubusercontent.com/46429252/50743099-7e5e3c00-121c-11e9-8f7f-6f5f6b162535.png)
windows:
![windows](https://user-images.githubusercontent.com/46429252/50743100-7e5e3c00-121c-11e9-92d9-de427d7d2796.png)

**Comment by josuave** [comment]
I put a pull request in that should resolve this.
It allows Cairo to mimic the wallpaper style from explorer

**Comment by dremin** [comment]
This fix is in the latest release.
