### ISSUE TITLE
Crash when connecting via RDP to a session with Cairo

### ISSUE THREAD

**Issue by vladkorotnev** [cairoshell/cairoshell#228]
**Describe the bug**

When I connect to my PC from another one via RDP, there is a crash message asking me if I want to restart Cairo. If I choose "No", it just reappears again. The shell is hanged at the mean time, clicking the minimized windows brings up different windows or activates quick launch instead.

If I choose "Yes", Cairo is closed and for some reason Explorer is started.

**Steps to reproduce**
1. Set Cairo as default shell.
2. Reboot and log in to the Cairo-enabled account.
3. Lock screen with Win+L
4. Connect to the same account/session using an RDP client (i.e. MSTSC)

**Expected behavior**
No crash.

**System information:**
 - Windows version: Windows 10 version 1803 build 17134.345
 - Cairo version: 0.3.6746.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Comment by dremin** [comment]
This usually happens when the screen resolution changes as part of the RDP connection. If you are able to keep the screen resolution consistent, it shouldn't occur.

I've spent a lot of time trying to debug this over the past year and I haven't yet found a solution. It seems to have something to do with a software renderer being briefly invoked at the same time as the screen size change, which causes WPF to not be happy. I haven't found a way around this yet.

**Comment by vladkorotnev** [comment]
Sadly, the shared PC is cleared on every shutdown, so I can't really persist my resolution settings in the RDP client there. The resolution of the session is the same as of my local display though — so it may be that even if I set a resolution on the RDP client session, it will still break?

**Comment by josuave** [comment]
Hmmm... try setting explorer as the shell, if it isn’t already, once the rdp is connected try running the Cairo Desktop and see if it crashes.

**Comment by Doofitator** [comment]
I've come across the same issue,  however cairo is not my default shell - I'm running it alongside explorer. In my case, however, upon clicking 'Yes', cairo doesn't restart, and explorer's taskbar refuses to appear. I can access the start menu with the keyboard button however, and restart cairo through that.

**Comment by vladkorotnev** [comment]
@josuave Cairo does not crash if I start it from Explorer over an already established RDP session — it just crashes if it's already running and then a new session is started.

**Comment by Doofitator** [comment]
@josuave The screen resolution in my case is a significant change - a measly 1366x768 to 2560*1440. You can see why I prefer the remote screen!

In saying this, however, I have noticed that the last few times I've connected to an RDP session, the option to restart has worked. I do not have to manually reopen cairo through the explorer start menu.

On a similar vein however, I began plugging my laptop into a 1080p external monitor this week to use an extended display, and noticed that on disconnect of that monitor, Cairo's interface would disappear from the laptop screen and the working area of the screen (where programs can be maximised to) would be reduced vertically by half. The only solution I have found is to open taskman and end the Cairo process, before restarting it.

**Comment by dremin** [comment]
Is this any better in [this build?](https://ci.appveyor.com/api/buildjobs/7b1dqj6g576w2sd0/artifacts/Installer%2FCairoSetup_64bit.exe)

**Comment by dremin** [comment]
Closing due to lack of response, I believe this is fixed now.
