### ISSUE TITLE
Cairo fails to adjust background layer to aspect ratio when switching from portrait to landscape

### ISSUE THREAD

**Issue by vladkorotnev** [cairoshell/cairoshell#229]
**Describe the bug**
When I switch my monitor from portrait to landscape, my wallpaper remains in portrait, takes up only half the screen horizontally and overflows vertically.

The right half of the screen remains black, and if I place some window over it and move it around, it leaves window trails on it.

**Steps to reproduce**
1. Set display to portrait
2. Launch Cairo
3. Set display to landscape

**Expected behavior**
Wallpaper would rescale to account for the new aspect ratio.

**System information:**
 - Windows version: Windows 10 version 1803 build 17134.345
 - Cairo version: 0.3.6746.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Additional context**
May be related to #226, but I didn't test that bug fix yet.

**Screenshots**
![capture](https://user-images.githubusercontent.com/656194/50888757-b098b500-1439-11e9-9d80-4b875fc056c9.PNG)
![capture_bug](https://user-images.githubusercontent.com/656194/50888756-b098b500-1439-11e9-8755-884251fa837a.PNG)

**Comment by josuave** [comment]
If you were up to building from source you can test the changes in my repo. https://github.com/josuave/cairoshell

**Comment by vladkorotnev** [comment]
OK, this is fixed in the fresh version (not tested with the rotation, but at least the aspect settings are now honored).

However there is now a regression, which makes the wallpaper appear on top of all windows.

See #239 for more details.
