### ISSUE TITLE
It's a little dingerous

### ISSUE THREAD

**Issue by sunxfancy** [cairoshell/cairoshell#23]
I used Win8 x64 and cairo has a no response problem, but it forbid my explorer and desktop. So I restore my computer hardly...
I suggest building it like a full screen game, if you like ,you can change to the classic mode.When the shortcut interference cairo ,use the hook to shield the shortcut key.
I will read the code tomorrow, do some debug...

**Comment by cairoshell** [comment]
Many fixes have been implemented to stabilize Cairo; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
