### ISSUE TITLE
Add Desktop Background Settings to Cairo

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#230]
**Is your feature request related to a problem? Please describe.**
There have been multiple bugs reported regarding the Cairo Desktop background aspect ratio

**Describe the solution you'd like**
We should add to Cairo Settings the option to use Windows Background Settings or have Cairo specific settings. This would allow the end user to change the wallpaper at will. 

Options should include or expand on:
- Use Windows
- Image (Center, Stretch, Fill, etc.)
-  Color (Solid, Gradient, etc.)
-  Pattern
- Video

**Comment by josuave** [comment]
gif of video wallpaper

**Comment by vladkorotnev** [comment]
From what it seems to me, Cairo relies on Explorer to show the wallpaper currently?
As once I kill Explorer, the wallpaper just disappears.
So the option for Video might not really be possible since Explorer doesn't support that.

**Comment by josuave** [comment]
added.

**Comment by dremin** [comment]
This is available in the latest release.
