### ISSUE TITLE
[Question]Windows 10: Can I replace shell just for one user?

### ISSUE THREAD

**Issue by darkhog** [cairoshell/cairoshell#231]
As in the title. I was unable to find an e-mail address or support contact, so asking here. Anyway, I'm looking for a slim but functional shell to replace overgrown explorer and Cairo seems to fit the bill (not sure about the memory usage, but I'm also looking into other shells as well). The problem is that it's a shared PC and the other person who's using it wouldn't be happy with the change. Can you tell me if in Windows 10 I can replace shell for just a single user instead of going system-wide as I had to do in WinXP or Win9x (last time I've played with alternative shells)?

**Comment by dremin** [comment]
Cairo will only change the shell for the current user.

**Comment by josuave** [comment]
This is handled by running Cairo Desktop. 

1. Click the Cairo Menu in the upper left
2. Click Cairo Settings
3. From the Cairo Settings window: Click Advanced, this is found along the left edge of the window.
4. On the bottom of the displayed page click the [Set Cairo as Shell], this assumes English for localization.

That's it! Each user that wants Cairo as their shell should do follow these steps.
