### ISSUE TITLE
Win 10: Disable Windows 10 START MENU someway?

### ISSUE THREAD

**Issue by Nighko** [cairoshell/cairoshell#235]
Is there some way to disable the windows 10 start menu while still keeping UWP applications functional? I have to leave the Explorer shell running to be able to start UWP applications. Is there some sort of solution or quick "fix"?

Thanks

**Comment by Nighko** [comment]
Or to at least disable the menu from popping up when I press the Windows Button

**Comment by josuave** [comment]
What action are you trying to achieve? Are you crossing the windows key to perform some action?

**Comment by stelios53** [comment]
http://www.startkiller.com/

**Comment by Nighko** [comment]
The windows button opens up the program menu of Cairo which is what I want it to do.

**Comment by dremin** [comment]
Until we are able to launch UWP apps without Explorer running, I don't think this will be possible.

**Comment by brucbr** [comment]
Is there a possibility for an executable to run for the programs menu to open? or an exposed activity/service?
