### ISSUE TITLE
Cannot install; not detecting .NET framework

### ISSUE THREAD

**Issue by Thaddeus-Maximus** [cairoshell/cairoshell#238]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11543788/52920555-776a2500-32c2-11e9-963a-b2f434e15add.png)

**Steps to reproduce**
1. Install windows 10
2. Attempt to install Cairo

**Expected behavior**
Installation to at least proceed

**System information:**
 - Windows version: Windows 10
 - Cairo version: M3.6746
 - 32-bit or 64-bit:  64-bit

**Additional context**
Fresh install of windows 10. Attempts to install either latest .NET framework or 4.5.2 result in a message about how there is already a (newer) .NET installation

**Comment by dremin** [comment]
Which version of Windows 10 are you running?

**Comment by dremin** [comment]
This has been re-written and should now be working. Please feel free to re-open if it is broken for you in the latest release.
