### ISSUE TITLE
[Regression] Wallpaper appears above all windows

### ISSUE THREAD

**Issue by vladkorotnev** [cairoshell/cairoshell#239]
**Describe the bug**
When right-clicking the desktop with a window open, the wallpaper brings up to the top level, but the background color stays below. 
Additionally, if I click somewhere in that background color, the menu from Explorer pops up for whatever the reason.

**Steps to reproduce**
1. Have a window that spans further than your wallpaper
2. Right-click the wallpaper
3. Wallpaper becomes frontmost until context menu is deactivated

**Expected behavior**
Either just pop up the menu, or bring up the whole Cairo's Desktop to front.

**System information:**
 - Windows version: Windows 10 version 1803 build 17134.590
 - Cairo version: Version 0.3.6758.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Screenshots**
When clicking the wallpaper it overlaps the window below:

![wpbug](https://user-images.githubusercontent.com/656194/53468792-e273e280-3a9e-11e9-851f-855bef6bb198.PNG)

When clicking outside the wallpaper, explorer's menu pops up:

![clickthru](https://user-images.githubusercontent.com/656194/53468800-f3245880-3a9e-11e9-9663-203e3fe2aa31.PNG)

**Comment by dremin** [comment]
I'm a bit confused, you mentioned that Cairo is set as shell but also that Explorer is running. Have you logged off and back in after changing this setting?

**Comment by dremin** [comment]
Closing; appears to be running in an unsupported configuration
