### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by Rofii** [cairoshell/cairoshell#241]
I tried uninstalling this program while cairo was still open. It didn't work and now when I try to uninstall it, the control panel says there was an error uninstalling cairo and asks me if I want to remove if from the list of installed applications, so I clicked yes. But I found a Cairo Shell folder in Program Files, and clicking CairoDesktop.exe opens cairo, so clearly it isn't uninstalled. Can I just delete the Cairo Shell folder, or will that not be a total and clean uninstall?

**Comment by dremin** [comment]
All of Cairo's program files are in that one directory. As long as you didn't select to replace Explorer, and you have removed Cairo from your startup items, you can remove this folder and consider Cairo completely uninstalled.

**Comment by dremin** [comment]
Marking this as a bug since the uninstaller needs to check if Cairo is running first to prevent failed uninstalls. Thanks for reporting the issue!

**Comment by josuave** [comment]
One solution would be to, while using explorer as shell, reinstall Cairo and then immediately uninstall Cairo.

If you don’t mind me asking why are you choosing to remove Cairo? Missing functionality?

Sent from my iPhone

On Mar 11, 2019, at 4:49 PM, Sam Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


All of Cairo's program files are in that one directory. As long as you didn't select to replace Explorer, and you have removed Cairo from your startup items, you can remove this folder and consider Cairo completely uninstalled.

**Comment by Rofii** [comment]
Thanks for the advice. And in regards to your question, I think I'm just stuck in my ways. I've had more or less the same setup for the last 20 years, be it on windows or KDE: two row height taskbar on primary monitor, one row height taskbar on secondary monitor, both with "combine taskbar entries" or whatever it's called disabled. Believe it or not, using Cairo shell for 10 minutes actually started giving me anxiety lol. The same thing happens when I use my sister's MacBook Pro. It's no fault of Cairo though, like I said I think I'm just stuck in my ways.

**Comment by dremin** [comment]
Fix available in the latest release.

**Comment by Asarel** [comment]
Hi @Rofii 😊 

You have probably found the solution as of 2019, I was in the same problem as of today August 2024. I will give you the step of how I was able to put my computer back to normal. Or if it could help others, then good for them. 

It is simple as this 😅 

Step 1 : Open task manager Crtl + Shift + Esc or Crtl + Alt + Delete and chose task manager it does the same 
Step 2 : End task for cairo
Step 3: Don't forget to go to Startup section and put it on disabled

You should be fine to uninstall cairo. Try to restart your computer after ending task and after uninstall Cairo too. 

Some things had changed for me when I got back to my old computer. The folder on my Desktop were not there. 

So I did a right click on the desktop and then click on show desktop items 

and my task bar didn't show either 

So I clicked right on the task bar and then clicked on show task bar. 

And here we go! Everything was back as normal !
