### ISSUE TITLE
Cairo won't even attempt to open.

### ISSUE THREAD

**Issue by dytractHOME** [cairoshell/cairoshell#243]
**Describe the bug**
Whenever I open Cairo (with explorer.exe running and not running), the process starts, but doesn't open. No environment, no desktop, no error dialog, no logs, nothing!

**System information:**
 - Windows version: Windows 7 Ultimate (64-bit)
 - Cairo version: Can't tell, don't have explorer.exe running right now.
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Cairo doesn't open, so idk.

**Comment by dremin** [comment]
Which version did you download? Is .NET 4.5.2 or newer installed?

If you check the Application log in Event Viewer, do you see any errors from .NET Framework?

**Comment by dytractHOME** [comment]
> 
> 
> Which version did you download? Is .NET 4.5.2 or newer installed?
> 
> If you check the Application log in Event Viewer, do you see any errors from .NET Framework?
I have explorer.exe running now, and I have M3.6758.

I have 4.5 installed, but not 4.5.2. Will that affect it?

**Comment by dremin** [comment]
Yeah, the app is targeting 4.5.2, so I wouldn't expect it to work correctly on 4.5. [You can get 4.5.2 here,](https://www.microsoft.com/en-us/download/details.aspx?id=42643) or you can install a newer version if you'd like to as well.

**Comment by dytractHOME** [comment]
> 
> 
> Yeah, the app is targeting 4.5.2, so I wouldn't expect it to work correctly on 4.5. [You can get 4.5.2 here,](https://www.microsoft.com/en-us/download/details.aspx?id=42643) or you can install a newer version if you'd like to as well.

Im installing it now. I'll keep posted. Do I need to kill explorer.exe?

**Comment by dremin** [comment]
You shouldn't need to kill Explorer unless you select the installation option to replace it.

**Comment by dytractHOME** [comment]
> 
> 
> You shouldn't need to kill Explorer unless you select the installation option to replace it.

I chose to replace it. It works now, thanks!

**Comment by dremin** [comment]
Glad to hear it's working now!
