### ISSUE TITLE
BSOD when updating or restarting Cairo

### ISSUE THREAD

**Issue by vladkorotnev** [cairoshell/cairoshell#247]
**Describe the bug**
Starting with the pre-latest version I get frequent BSODs when trying to reinstall, update or otherwise restart Cairo.

**Steps to reproduce**
1. Have Cairo running.
2. (Possibly) Hibernate PC and bring it back on a few times.
3. Try to restart Cairo after altering some settings or receiving an update.
4. BSOD appears with MEMORY_MANAGEMENT error.
5. As soon as I switch back to Explorer as primary shell, and stop using Cairo, everything works fine for days.

**Expected behavior**
Restart or update Cairo with no problem.

**System information:**
- Windows version: Windows 10 version 1803 build 17134.590
- Cairo version: 0.3.6758.0 - Pre-release
- 32-bit or 64-bit: 64
- In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Comment by dremin** [comment]
@vladkorotnev Are you still having this issue?

**Comment by dremin** [comment]
Closing due to lack of response.

**Comment by vladkorotnev** [comment]
Sorry, I have got rid of Cairo due to moving to a workspace that is not using Windows, so cannot confirm
