### ISSUE TITLE
Bug on startup - (10 minutes to start and error)

### ISSUE THREAD

**Issue by procobain** [cairoshell/cairoshell#248]
When starting CairoShell (for the first time, and all the others), the cairo is charging for a long time, after many minutes it shows the error message, if you click No, you can use it normally. If you click Yes, it restarts and repeats the delay ...
  (Windows 10 pro x64, Xeon1270v2, Z77, 16gb, SSD, GTX970)

---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?
Please submit a bug report with a screenshot of this error. Thanks! 
Message: Uma exceção foi acionada pelo destino de uma chamada.
Target Site: System.Object CreateObjectInstance(System.Exception ByRef)
Version: 0.3.6768.0
   em System.Windows.Data.ObjectDataProvider.CreateObjectInstance(Exception& e)
   em System.Windows.Data.ObjectDataProvider.QueryWorker(Object obj)
   em System.Windows.Data.ObjectDataProvider.set_ObjectType(Type value)
   em CairoDesktop.MenuBar.<>c__DisplayClass23_0.<setSearchProvider>b__1()
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner exception:
Message: O inicializador de tipo de 'CairoDesktop.Common.SearchHelper' acionou uma exceção.
Target Site: Void .ctor()
   em CairoDesktop.Common.Searc...
---------------------------
Yes No   
---------------------------

![CairoDesktop_B7uSNASuOc](https://user-images.githubusercontent.com/31631530/54596289-12196900-4a13-11e9-8fe9-c1a74593dfaf.png)

**Comment by josuave** [comment]
Could you also provide the .net framework versions and the build of windows 10 you are using?

Sent from my iPhone

On Mar 19, 2019, at 5:49 AM, procobain <notifications@github.com<mailto:notifications@github.com>> wrote:


When starting CairoShell (for the first time, and all the others), the cairo is charging for a long time, after many minutes it shows the error message, if you click No, you can use it normally. If you click Yes, it restarts and repeats the delay ...
(Windows 10 pro x64, Xeon1270v2, Z77, 16gb, SSD, GTX970)

________________________________
Cairo Desktop Error
Would you like to restart Cairo?
Please submit a bug report with a screenshot of this error. Thanks!
Message: Uma exceção foi acionada pelo destino de uma chamada.
Target Site: System.Object CreateObjectInstance(System.Exception ByRef)
Version: 0.3.6768.0
em System.Windows.Data.ObjectDataProvider.CreateObjectInstance(Exception& e)
em System.Windows.Data.ObjectDataProvider.QueryWorker(Object obj)
em System.Windows.Data.ObjectDataProvider.set_ObjectType(Type value)
em CairoDesktop.MenuBar.<>c__DisplayClass23_0.b__1()
em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner exception:
Message: O inicializador de tipo de 'CairoDesktop.Common.SearchHelper' acionou uma exceção.
Target Site: Void .ctor()
em CairoDesktop.Common.Searc...
Yes No

[CairoDesktop_B7uSNASuOc]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F31631530%2F54596289-12196900-4a13-11e9-8fe9-c1a74593dfaf.png&data=02%7C01%7C%7C52da5ba62a214cdb721f08d6ac502a6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636885857634327839&sdata=ualBIGkQ8jXkNeW5rKcECosDbuGnmHMq07b5OOWS8Z0%3D&reserved=0>

**Comment by procobain** [comment]
After these questions, I updated from 1803 to 1809, and updated everything I needed, including .net 3.5 and 4.7.2, cairo is working normally, thanks for the help.

**Comment by dremin** [comment]
Glad to hear it's working now!
