### ISSUE TITLE
Amateur developer wish to help

### ISSUE THREAD

**Issue by spadino** [cairoshell/cairoshell#251]
Hi! I'm an amateur developer, involved in some open source projects. I was working on a virtual space manager (a project by my own) and I think that Cairo Desktop could benefit from it. Those are my requests and possibly field of involvement: 

**Virtual Desktop**
I would like to have my shell to manage virtual desktop - ideally, natively: create, delete, switch to, move to and all kind of usual behavior we expect from a desktop manager.

**Rules and filters**
I would love to be able to tell my shell to open a program always on a specific desktop, with custom dimensions and position (if wished so) 

**Dynamic Layout**
I wish my shell to be able to dynamically manage the apps windows for me. I don't want to spend time moving windows from outside another - unless I choose that. So, have a pluggable layout manager will be fantastic: tiling, cascade, fullscreen, etc...

Thanks for the great work!

**Comment by dremin** [comment]
I think these features would be great to have within Cairo! We would love to have you helping out, so please reach out if there are ways I can help you do so.

**Comment by spadino** [comment]
Great! I'm not sure how to implement those ideas yet in Cairo - I used a somewhat different approach, using native virtual desktop, i.e. - but as far as the shell is replaced, probably there is the need for a completely new virtual desktop layer (which can be easier to deal with, though!).

So, I already have a library with all sort of pinvoke reference from native Win32 to deal with windows manipulation and virtual desktops. I will incorporate such imports when needed, after better understood the cairo source tree. Btw, have you a discord channel?

Cheers

**Comment by dremin** [comment]
Closing due to lack of response.
