### ISSUE TITLE
Display Program Menu Bars in Cairo Menu Bar

### ISSUE THREAD

**Issue by rikkuporta** [cairoshell/cairoshell#252]
Hi, is it possible to somehow extract the Menu bar from Programms and Display it instead in Cairo? Just like MacOS or some Versions of Ubuntu?
I would also be interested in working on this but I'm not sure if this is possible, respectively I dot have any leads or direction/idea how or if this is possible.

**Comment by josuave** [comment]
Sorry to say that this is no easy task. I have dug in and found one software that has attempted to achieve this for windows (https://github.com/lee-soft/ViDock). Because there are no standards in place for defining the "Menu Bar", the majority of cases have to be handled case by case.

**Comment by dremin** [comment]
This is not a feature that is feasible for us to implement in a well-supported fashion.
