### ISSUE TITLE
Taskbar not staying on top level after fullscreen

### ISSUE THREAD

**Issue by Popat0** [cairoshell/cairoshell#253]
Hello there,
I'm currently experiencing a bug where the taskbar (in autohide or overlap mode) disappears after using an app in fullscreen then acts like a normal window afterwards.

**Steps to reproduce**
1. Open a Youtube video on fullscreen in Firefox.
2. Close the fullscreen video player.
3. The taskbar is now hiding behind all other windows.

**Expected behavior**
The taskbar should reappear as a "top level window".

**System information:**
 - Windows version: Windows 10 1809
 - Cairo version: M3.6768
 - 32-bit or 64-bit: 64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No.

**Additional context**
Obviously couldn't reopen the similar issue #165 since it wasn't posted by me.

**Comment by josuave** [comment]
I have not looked in to this at all but....
I would recommend that we have an always on top option for the bar. If the setting is true then when any window is shown or closed make the bar top most else let it be where it lay

**Comment by dremin** [comment]
@josuave This one is interesting, for some reason the native Windows method for setting the window as top-level isn't always working after exiting full screen. I found that making the window the frontmost first tends to help and implemented this a while ago, but there must be a few holes still.

**Comment by Matthew-Bonner** [comment]
Even the Windows TaskBar has this issue, after fullscreen mode you can sometimes overlap the taskbar with other applications when clicking on the desktop, so my guess is that Windows is handling a few more events to make itself topmost.

**Comment by dremin** [comment]
This is fixed in the latest release.
