### ISSUE TITLE
WIN+D hides desktop ?

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#254]
I am experiencing #73 on Windows Server 2016

**Comment by dremin** [comment]
Please try using the workaround presented in #73 and see if that helps.

**Comment by beppe9000** [comment]
Disabling win key combinations is not feasible for me since i rely heavily on them... Have you thought of hooking explorer' hotkey callback somehow? Also, since the taskbar itself is a window maybe there is a way to mimic its exemption from that with tricks like window class changing, or setting the window as a child of taskbar or desktop itself.

**Comment by dremin** [comment]
The latest release fixes Win + D on Windows 8 and newer.
