### ISSUE TITLE
Notification icons should have full-height click areas

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#259]
There is a ~3px margin around (top and bottom) the notification icons that inhibits notification clicking. The fix would be to port explorer's behaviour: there is a margin but it is clickable.

Below is a screenshot of cairo notification area edited to illustrate the problem.
Green is clickable, red isn't. I believe it should be, at least the top one.

![image](https://user-images.githubusercontent.com/6625123/58374710-0bdbc780-7f43-11e9-8e20-5a35ef33bc82.png)

In HTML terms should be:

```
<notifications (no margin; no padding)>
    <notif1 (with top margin=0 and click event handler)>
      <icon (with appropriate margins)>
    </notif1>
</notifications>

```

**Comment by dremin** [comment]
This is now available in the latest release. Thanks for the suggestion!
