### ISSUE TITLE
How to pin app to taskbar?

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#260]
#114 says there is pinnable icons on taskbar but I can't find how to show/add to them.

**Comment by josuave** [comment]
Add programs to the Quick Launch
1. Click "Programs" from the Menu Bar.
2. Right-Click the desired program
3. Click "Add to Quick Launch"

Please confirm if the steps work for you.

**Comment by beppe9000** [comment]
My bad, I expected for it to work like explorer in that you right click the actual window icon and 'pin it'.
Also it does not recycle the icon?

**Comment by josuave** [comment]
Sounds like you may want to consider this Issue closed and then open a new issue using the Feature Request template

**Comment by beppe9000** [comment]
yeah
