### ISSUE TITLE
[bug] unable to switch to elevation prompt window by cklicking on it in the taskbar

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#261]
I'm unable to switch to the elevation prompt of a program opened from Cairo. I click there and nothing happens. I can alt-tab with no problem. Explicitly running Cairo as administrator changes nothing.

![image](https://user-images.githubusercontent.com/6625123/58374950-d20dbf80-7f48-11e9-9783-66c057b277e2.png)

**Comment by dremin** [comment]
@beppe9000 This should actually be fixed in the latest build (I missed updating this issue when it was released). Is this working for you now?

**Comment by beppe9000** [comment]
i'll let you know as soon as I test that

**Comment by dremin** [comment]
@beppe9000 Were you able to test this?

**Comment by beppe9000** [comment]
i was not able to reproduce it, so I think it's fixed
