### ISSUE TITLE
[Feature Request] Explorer-like app pinning

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#262]
I expected for it to work like explorer in that you right click the actual window icon and 'pin it'.
Icon merging is when you open a pinned app in explorer and you end up with a single icon

**Comment by josuave** [comment]
Basic functionality of this feature has been developed on the jousave\cairoshell. If you would like to use this functionality before it is merged and release, download my fork and compile.

**Comment by dremin** [comment]
The pinning functionality referenced here has been implemented. The merging functionality is covered in #99 and #52. Closing.
