### ISSUE TITLE
Explorer windows flicker when clicking cairo menu bar and then the desktop

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#263]
Not set as shell, taskbar disabled

**Comment by dremin** [comment]
Not able to reproduce, any shell extensions you have installed that could be causing this?

**Comment by beppe9000** [comment]
I have lots of shell extensions... here is a dump:
![image](https://user-images.githubusercontent.com/6625123/60511446-44a15600-9cd2-11e9-9963-bb72e8278599.png)

**Comment by dremin** [comment]
I think this is resolved in the latest release after the desktop changes. Could you please verify? Thanks!

**Comment by beppe9000** [comment]
it looks solved. but I got a flicker of the desktop on some occasions on current version by doing random clicks on desktop, top bar and then minimize/restore of a window. looks like a desktop refresh idk if it's related

**Comment by dremin** [comment]
Interesting, would you be able to provide a screen recording showing the flicker? I am not able to reproduce that one.

**Comment by beppe9000** [comment]
I originally intended to, but the gif recording had a too slow frame rate :\ 
I will figure something...

**Comment by dremin** [comment]
Closing due to no further reproductions.
