### ISSUE TITLE
certain apps not seen in notification area

### ISSUE THREAD

**Issue by jakkaas** [cairoshell/cairoshell#265]
Certain windows 10 app are not seen in system notification area/tray icon in cairo shell.
When I exit the cairo shell, the app seems to be present and is seen in the taskbar system tray area.

**System information:**
 - Windows version: 1903
 - Cairo version: latest
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Comment by josuave** [comment]
Can you provide some of the app names?

**Comment by jakkaas** [comment]
There is app called pantherbar which I keep on at startup. It is seen in taskview but not seen in Cairo notification area. Also many software especially windows 10 store app while minimizing to taskview is sometimes not seen in Cairo. It's random. Stemio, screen reader pro, hot

**Comment by dremin** [comment]
Pantherbar appears to be unique because it is using UWP API to set its notify icon. Are you still having issues with the other apps?

**Comment by mealpi** [comment]
I have same issue with 360 Security QHSafeTray.exe

**Comment by jakkaas** [comment]
No. Only issue with Pantherbar

**Comment by dremin** [comment]
Closing as a duplicate. We're aware of some apps that don't behave correctly.
