### ISSUE TITLE
Extend Taskbar to cover screen

### ISSUE THREAD

**Issue by Recaran** [cairoshell/cairoshell#268]
Is there any way to extend the task bar to cover the entire bottom section of the screen? I have googled around and checked github but i cannot see an option to do this.

![image](https://user-images.githubusercontent.com/9035813/59145737-f5704a00-89df-11e9-8e99-0210b92faf3b.png)

This kind of emulates the Gnome desktop behavior on linux. I feels strange having spaces on either side. I understand that the task bar grows as you add programs to it, but would rather have a set space for running programs.

**Comment by josuave** [comment]
This is not currently a feature. We are going to start refactoring the code quite a bit and develop a more flexible API. One of the things that I had envisioned a long time ago was a sort-of menubar/taskbar designer, like how one would customize the google chrome toolbar. I like this as it has the potential to accept plugins as menu items with out having to develop special cases.

**Comment by josuave** [comment]
I added some code to my fork.

**Comment by dremin** [comment]
This is now available in the latest release.
