### ISSUE TITLE
Install appears to succeed, but can't open from start menu

### ISSUE THREAD

**Issue by KyleKing** [cairoshell/cairoshell#27]
I downloaded .NET and VCC (both already installed) and ran the Cairo setup.exe, but can't start Cairo. I have Windows 7

**Comment by dremin** [comment]
Hi Kyle,
Did you download the latest version from cairodesktop.com? Is there any error message that appears? Did you download the correct file for your system (32- or 64-bit)?

**Comment by KyleKing** [comment]
Hi Sam, I checked my system information and downloaded the latest 64-bit pre-release from https://github.com/dremin/cairoshell/releases/tag/v0.2.6469

The cmd prompt disappears too quickly and I'm not able to catch the message, but it does appear there is some sort of error. Is there a log file that I can check?

**Comment by dremin** [comment]
Interesting, there should not be any command prompt that appears. If there is an error you should see it in the Windows Event Viewer Application log.

**Comment by KyleKing** [comment]
There wasn't anything in the event viewer logs, but I managed to capture a screen recording and this is the error info:

![photo oct 02 14 54 42](https://user-images.githubusercontent.com/3784339/31094157-2520e35a-a782-11e7-98e1-937d1ed03b84.png)

**Comment by dremin** [comment]
Thanks! That command prompt window during the install is normal, those messages are benign and expected on Windows 7. When starting Cairo from your Start menu, do you see any errors?

**Comment by KyleKing** [comment]
Oops, I guess it was working the whole time. The application did not appear in the start menu, but I launched it from the executable in the program files folder and everything appears to work. Thanks for your help!
