### ISSUE TITLE
solidworks application not display in the bottom menu

### ISSUE THREAD

**Issue by greg328** [cairoshell/cairoshell#273]
**Describe the bug**
solidworks application not display in the bottom menu when I click the application's minimize windows

**Steps to reproduce**
1. I start the cairoshell and then start the solidworks application
2. I click the application's minimize windows
3. solidworks application not display in the bottom menu

**Expected behavior**

**System information:**
 - Windows version: win10
 - Cairo version: 6781
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Additional context**

**Screenshots**

**Comment by dremin** [comment]
This one is odd-- Solidworks doesn't say it is a window when it is maximized. I worked around this by checking for some other attributes when maximized that should address this.

**Comment by dremin** [comment]
This is fixed in the latest release.
