### ISSUE TITLE
AVG claims CairoDesktop.exe as Virus

### ISSUE THREAD

**Issue by irneb** [cairoshell/cairoshell#277]
**Describe the bug**
AVG Business claims the CairoDesktop.exe file as a virus and moves it to quarantine.

**Steps to reproduce**
1. Have AVG anti virus installed
2. Turn off, install CiaroShell
3. Reboot, AVG shows a notification after Ciaro starts and the desktop bars disappear.

**Expected behavior**
AVG should not see this as any sort of virus at all.

**System information:**
 - Windows version: Windows 10 Pro - 1903
 - Cairo version: 0.3.6781.0
 - 32-bit or 64-bit: 64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No, Windows Explorer is set as shell.

**Additional context**
Adding an exception in AVG sorts out the problem. But not all users have rights to add these exceptions, especially not in an enterprise AV system. Reporting a false positive should also come from the developers of said product.

**Comment by dremin** [comment]
Is this still happening? What virus is AVG marking for Cairo?

**Comment by dremin** [comment]
I have reported the false positive to AVG and will update here with their response.

**Comment by dremin** [comment]
@irneb This false positive should now be resolved as per AVG. If you are still seeing this after another 24 hours, please provide the information they have requested to this issue and I can update them. Thanks!

> Please accept our apologies for the inconvenience caused. The detection by AVG was incorrect and was removed in a recent AVG update, please wait at least 24 hours.
>
> If the detection persists, please reply to this e-mail and:
>
> 1. Attach a screenshot of your virus database version in AVG.
> 2. Attach the screenshot including the detection dialog, with See details in the bottom-right corner displayed.
