### ISSUE TITLE
Not starting at all

### ISSUE THREAD

**Issue by justwannafileanissue** [cairoshell/cairoshell#278]
When starting Cairo, Nothing happens and the task isn't running in task manager, All it does is set the taskbar to auto-hide and kills explorer.
`Win10 Home, 18362.19h1_release.190318-1202`

**Comment by dremin** [comment]
In order to troubleshoot, could you please go to `%localappdata%\Cairo_Development_Team\Logs` and attach the latest log file? If there isn't one, could you please check the Event Viewer > Application log for any .NET errors mentioning Cairo? Thanks!

**Comment by dremin** [comment]
Necessary information not received; closing. Feel free to re-open with the requested information. Thanks!
