### ISSUE TITLE
Novabench will not run under this shell

### ISSUE THREAD

**Issue by Telepro21** [cairoshell/cairoshell#279]
I have been using the Cairo Shell since August 2019 and I really like it.  
Recently, I installed Novabench and noted that it will only run under the regular Windows shell.
When I try to execute the program under Cairoshell, I get the error shown in the attached screen shot.
![s06eG6yA7V](https://user-images.githubusercontent.com/57018780/67603350-34f4c400-f73e-11e9-8168-66f0cba4af7a.jpg)

**Comment by dremin** [comment]
This is fixed in the latest release.
