### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by KyleKing** [cairoshell/cairoshell#28]
I'm missing most of the icons from the drop-down menus, desktop, and bottom tab bar. What do you think is going on?

![photo oct 04 11 20 08](https://user-images.githubusercontent.com/3784339/31184148-9a4f6cb2-a8f6-11e7-8fc2-fdd98321fea7.jpg)

**Comment by dremin** [comment]
I've noticed a few scenarios where Cairo got stuck loading a certain icon, causing the others to never load. I may need to add some additional logging to help troubleshoot this, but do you have any insight as to which icon Cairo is getting stuck on, maybe in one of the views where you see some icons loaded but not others?

**Comment by KyleKing** [comment]
It's hard to say - only the FIRefox icon from the quick launch app group appears. I just restarted Cairo and toggled the dynamic desktop, which fixed all visible icons

**Comment by dremin** [comment]
Hm, it may have been a desktop icon. If you change the default desktop directory in Cairo Settings to another folder (an empty one would be best for testing purposes) and restart Cairo, do all icons load?

**Comment by dremin** [comment]
Strange, glad to hear it's working! I will continue to work on the resiliency of icons to reduce the chance of this happening again.

**Comment by KyleKing** [comment]
I think Excel may be the culprit for crashing my Cairo icons

Also, my notes icon never appears:
![capture](https://user-images.githubusercontent.com/3784339/31295143-6379bbc8-aaab-11e7-9703-058b83d6bc36.PNG)

**Comment by dremin** [comment]
Is this OneNote or some other app?

Also, regarding Excel, is it an Excel file or the app itself that seems to be causing issues? Does it only happen when Excel is open? Was Excel installed under a different user or some other way by chance?

**Comment by mdmk** [comment]
It seems to be onenote I guess, with onenote 2016 I have exactly the same tooltip, but no problem.
![screenshot14](https://user-images.githubusercontent.com/32496803/31349108-18e9ee4c-ad22-11e7-9b15-1e231d2ff13f.png)

**Comment by KyleKing** [comment]
My icon is for OneNote 2016 as well (if it matters it is Office Professional Plus)

Also, I don't think the problem is with Excel and it is hard to tell when the icons start to disappear

**Comment by dremin** [comment]
I fixed a couple of issues with taskbar icon processing, which may resolve your issue. Is it still happening after the latest release? You can update using 'Check for updates' in the Cairo menu.

**Comment by KyleKing** [comment]
I think this is due to explorer.exe crashing, which happens without Cairo. I'll close this for now and will follow up if I can solve my explorer.exe issues
