### ISSUE TITLE
Tooltip position is obtrusive

### ISSUE THREAD

**Issue by Matthew-Bonner** [cairoshell/cairoshell#280]
The Windows task bar shows the tooltips above the taskbar, however in Cairo, the tooltips are positioned where the mouse cursor is, this gets annoying, the tooltips can be repositioned by traversing up the tree to position the tooltip based on the parent.

![image](https://user-images.githubusercontent.com/7858744/68020484-83521780-fc96-11e9-83f2-4a22712ffc29.png)

vs

![image](https://user-images.githubusercontent.com/7858744/68020573-cc09d080-fc96-11e9-9cb0-9c5a5a3b9d94.png)

**Comment by dremin** [comment]
This is resolved in the latest release.
