### ISSUE TITLE
Can't build in Windows 10 with update 1903

### ISSUE THREAD

**Issue by Matthew-Bonner** [cairoshell/cairoshell#283]
See the following:
https://developercommunity.visualstudio.com/content/problem/446490/visual-studio-cant-see-winmetadatadirectory-in-cwi.html

This is what happens in Visual Studio:
![image](https://user-images.githubusercontent.com/7858744/68026950-03817880-fca9-11e9-9827-e61e63adafd8.png)

This is what happens if you remove the references and add them again:
![image](https://user-images.githubusercontent.com/7858744/68026984-198f3900-fca9-11e9-8b09-be31756124a3.png)

To confirm, the files do exist:
![image](https://user-images.githubusercontent.com/7858744/68027023-3461ad80-fca9-11e9-81bf-6649a46eb38e.png)

The fix in the link above suggests adding the references like so:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#to-add-the-required-references-manually

See the last post by Microsoft:
"This was a deliberate change made by Window.
Main gist is, “the WinMetadata directory was only intended for use by the OS.”

**Comment by Matthew-Bonner** [comment]
Additionally, I just tried all 3 solutions suggested, and none worked.

**Comment by Matthew-Bonner** [comment]
It seems the solution is to add the following to the project files:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.18362.2005" />
  </ItemGroup>
```

Do you want me to submit a PR?

**Comment by Matthew-Bonner** [comment]
Thanks for letting me know. However, regardless of whether you have the issue or not, MS are saying what you are doing is fundamentally wrong, and that you should reference the Microsoft.Windows.SDK.Contracts NuGet package instead. I have no doubt you'll be able to reproduce it, but to save you the effort of building out a new dev pc I can just submit a PR tonight if you want?

**Comment by dremin** [comment]
I had this issue and resolved it with a new VM. I'll try this fix on my old VM and see if it helps!

**Comment by dremin** [comment]
The references still don't seem to be resolved even when adding this NuGet package. If you're able to get it working, please submit a PR :)

**Comment by Matthew-Bonner** [comment]
I am targeting .NET Framework 4.6.1 too, I found unless I did this I had the same issue.

**Comment by dremin** [comment]
Ah, thanks, that does the trick! Unfortunately, it looks like 4.6.0 was the last release that supported Vista, so we will need to drop support for that OS. However, I think it is a worthwhile tradeoff.

Now to decide which version to target for the next release: I am inclined to actually target 4.7.1 while we're at it, but that means potentially any system running older than Windows 10 1709 will require a .NET update for Cairo to run.

**Comment by dremin** [comment]
This should be fully resolved now.
