### ISSUE TITLE
Fix installer .NET version detection

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#284]
Now that the target framework version is being increased, the installer needs to inform the user if they need an update.

**Comment by Cereal-Killa** [comment]
Was going to look at it but I can see that the installer script already takes care of that.

**Comment by dremin** [comment]
Sorry, this was more for my own tracking, and I forgot to include the issue number in my commit message!

**Comment by dremin** [comment]
This is now available in the latest release.
