### ISSUE TITLE
Some Stuff in Taskbar wont maximize

### ISSUE THREAD

**Issue by krauthaus** [cairoshell/cairoshell#286]
Hi there! I am running the latest version of cairo, and some software cant be maximized again after minimizing to the taskbar. 

For this software I need to use Alt + Tab for changing the current window.

Software I noticed it:
- Ryzen Master (in very few cases it worked maximizing, mostly not)
- some Games (Assasins Creed Origins)
- Latency Mon

If I can help in someway just tell me what I have to do to provide more information. (logs, etc)

**Comment by dremin** [comment]
This generally happens when the program is running with elevated privileges. Are these applications being run as administrator by chance?

**Comment by dremin** [comment]
This is fixed in the latest release.
