### ISSUE TITLE
Possibility to choose for autorun at login

### ISSUE THREAD

**Issue by Brummell67** [cairoshell/cairoshell#290]
I feel need this features.

**Comment by dremin** [comment]
Could you please elaborate?

**Comment by Brummell67** [comment]
> Could you please elaborate?
Hi Dremin.
I'm interest this project, but my skill are modest. I don't know C++, but opening project, I saw only System tray need C++: I'm wrong?
I know .NET, C#, VB, WPF.
I'm also e graphic designer and I would like to collaborate, because I love study usability.
I wait your answer.

Cheers

**Comment by dremin** [comment]
Correct, only the tray component is C++. Everything else is C# and WPF. Any help is always appreciated! :)

**Comment by Brummell67** [comment]
Merry Christmas!
Exscuse me, this is my first time on Github and I don't know formal workflow.
I think to be ready. What I must do now?

**Comment by dremin** [comment]
Thanks, you too! Here is how I would suggest contributing:

1. Fork this repository (which it looks like you’ve done already) and clone to your local machine. The built in Git features in Visual Studio work well for Cairo development. 
2. Make changes in your local repository then commit and push to your fork. 
3. Come back here and open a pull request. 
4. Your pull request will be reviewed and changes may be requested. 
5. Once everything looks good we will accept the PR and merge your changes!

**Comment by Brummell67** [comment]
Excuse me: I'm noob :(
I forked in local. With VS i try to Push, but I get this:
"Push di RunAtLogOn
È stato rilevato un errore durante il push del ramo nel repository remoto: Git failed with a fatal error.
unable to access 'https://github.com/cairoshell/cairoshell/': The requested URL returned error: 403
Pushing to https://github.com/cairoshell/cairoshell".

**Comment by Brummell67** [comment]
> Excuse me: I'm noob :(
> I forked in local. With VS i try to Push, but I get this:
> "Push di RunAtLogOn
> È stato rilevato un errore durante il push del ramo nel repository remoto: Git failed with a fatal error.
> unable to access 'https://github.com/cairoshell/cairoshell/': The requested URL returned error: 403
> Pushing to https://github.com/cairoshell/cairoshell".

Maybe I solved my problem. But if I try to build without modify, get a lot errors:

10>  CairoDesktop.WindowsTasks -> D:\Git\cairoshell\Cairo Desktop\Build\x64\Debug\CairoDesktop.WindowsTasks.dll
15>------ Inizio compilazione: Progetto: Cairo Desktop, Configurazione: Debug x64 ------
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml.cs(409,26,409,36): error CS0117: 'Settings' non contiene una definizione per 'RunAtLogOn'
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(207,88,207,121): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboCairoMenuHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboCairoMenuHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(208,88,208,121): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboCairoMenuHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboCairoMenuHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(209,87,209,120): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboCairoMenuHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboCairoMenuHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(234,83,234,101): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTrayMode0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTrayMode0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(237,83,237,101): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTrayMode1_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTrayMode1_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(254,91,254,117): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'btnDesktopHomeSelect_Click' e non è stato trovato alcun metodo di estensione accessibile 'btnDesktopHomeSelect_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(261,93,261,131): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboDesktopOverlayHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboDesktopOverlayHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(262,93,262,131): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboDesktopOverlayHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboDesktopOverlayHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(263,92,263,130): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'cboDesktopOverlayHotKey_DropDownClosed' e non è stato trovato alcun metodo di estensione accessibile 'cboDesktopOverlayHotKey_DropDownClosed' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(269,90,269,115): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radDesktopIconSize2_Click' e non è stato trovato alcun metodo di estensione accessibile 'radDesktopIconSize2_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(272,90,272,115): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radDesktopIconSize0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radDesktopIconSize0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(280,90,280,115): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radDesktopLabelPos0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radDesktopLabelPos0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(283,90,283,115): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radDesktopLabelPos1_Click' e non è stato trovato alcun metodo di estensione accessibile 'radDesktopLabelPos1_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(308,86,308,107): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarSize1_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarSize1_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(311,87,311,109): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarSize10_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarSize10_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(314,86,314,107): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarSize0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarSize0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(322,85,322,105): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarPos0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarPos0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(325,85,325,105): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarPos1_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarPos1_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(333,86,333,107): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarMode0_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarMode0_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(336,86,336,107): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarMode1_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarMode1_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(339,86,339,107): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'radTaskbarMode2_Click' e non è stato trovato alcun metodo di estensione accessibile 'radTaskbarMode2_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(401,85,401,105): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'btnChangeShell_Click' e non è stato trovato alcun metodo di estensione accessibile 'btnChangeShell_Click' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\CairoSettingsWindow.xaml(416,104,416,116): error CS1061: 'CairoSettingsWindow' non contiene una definizione di 'restartCairo' e non è stato trovato alcun metodo di estensione accessibile 'restartCairo' che accetta un primo argomento di tipo 'CairoSettingsWindow'. Probabilmente manca una direttiva using o un riferimento all'assembly.
15>D:\Git\cairoshell\Cairo Desktop\Cairo Desktop\SupportingClasses\ShellContextMenu.cs(656,21,656,22): warning CS0219: La variabile 'a' è assegnata, ma il suo valore non viene mai usato

**Comment by Brummell67** [comment]
My last pull request fix last commit.

**Comment by Brummell67** [comment]
I'm back!
I'm sorry for the last  errors.
May you check my new code?

**Comment by dremin** [comment]
@Brummell67 It looks really good at first glance, thanks! I will try to review this weekend.
