### ISSUE TITLE
Disable open multiple CairoSettingsWindow.xaml

### ISSUE THREAD

**Issue by Brummell67** [cairoshell/cairoshell#293]
As the title suggests,it is not disturbing to be able to have the same window open several times at the same time?
What do you think?

**Comment by josuave** [comment]
Wouldn’t hurt to have settings be single instance. Where if a second instance is requested the current would come to the foreground. Brummell67 is this something that you would like to tackle? If not, I will add this functionality.

**Comment by Brummell67** [comment]
Sure, with pleasure.

**Comment by josuave** [comment]
Nice, i have looked at the source on here and have thought of a good solution. Very interested to see what you bring.

**Comment by Brummell67** [comment]
> Nice, i have looked at the source on here and have thought of a good solution. Very interested to see what you bring.

Wait please.
I don't know still, how to relationing in this ambient, sorry.
In cases like this, what is better/correct way?
Can we reason together before write code?
Maybe your idea is better of my.
Thank you

**Comment by Brummell67** [comment]
I'm ready. I wait your answer.

**Comment by Brummell67** [comment]
Thank for your replay.
I've another push in review:
"Possibility to choose for autorun at login #290"
 Can I push also this now?

**Comment by josuave** [comment]
Ah, i forgot about the previous PR.

**Comment by Brummell67** [comment]
I should be ready.
