### ISSUE TITLE
不显示托盘

### ISSUE THREAD

**Issue by zhangdexin** [cairoshell/cairoshell#294]
不显示系统托盘

**Comment by josuave** [comment]
Translation: Do not show system tray

I assume that this individual would like an option to hide the system tray.

**Comment by dremin** [comment]
![Annotation 2020-01-11 030013](https://user-images.githubusercontent.com/7373633/72201096-8dbf2900-341e-11ea-9e92-30441f3a4637.png)

**Comment by dremin** [comment]
Closing due to feature already existing.
