### ISSUE TITLE
Minimization animation errors

### ISSUE THREAD

**Issue by gaberade** [cairoshell/cairoshell#3]
Cairo on Win7

Using Aero, windows will minimize in the direction of their location on the explorer taskbar, rather than just fading out in place. This happens if you run cairo before terminating explorer.exe and persists after you terminate explorer.exe. It is fixed if you restart cairo.

**Comment by cairoshell** [comment]
Many fixes have been implemented to stabilize Cairo; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!

**Comment by mdmk** [comment]
@dremin 
The first time an app is minimized, it is pushed toward the position of the icon in native taskbar.
But the next minimizations work as expected, it minimizes (more or less) to the position of the icon in Cairo.
So could we reopen this issue, for as long as the problem of the first minimization is present?

P.S.: I assumed @cairoshell  is the same person as @dremin. If not, please correct me please.

**Comment by dremin** [comment]
I'll look into this some more. If it can be fixed, I'll re-open it, but it may be a system limitation. And yes, it's me 😄
