### ISSUE TITLE
Icons in desktop folder are not showing on desktop after uninstall

### ISSUE THREAD

**Issue by omerakgoz34** [cairoshell/cairoshell#305]
**BUG:**
"Desktop" disappears when uninstall. No file icons shown on desktop.
No "This PC", No "This User", No "Control Panel" native icons and file icons in "C:/Users/${username}/Desktop" folder shown on Desktop.

**System information:**
 - **Windows version:**   10 v1909 (build: 18363.592)
 - **Cairo version:**   M3.6842
 - **32-bit or 64-bit:**   64-bit
 - **In Cairo Settings > Advanced, is Cairo set as shell?:**
   yes, but i set default to winExplorer before uninstall.

![Screenshot_Desktop](https://user-images.githubusercontent.com/49201485/73106140-c1fd1400-3f0b-11ea-930c-f4282870600c.png)

**Comment by dremin** [comment]
Try right-clicking the desktop, then choosing View > Show Desktop Icons. Does that help?

**Comment by omerakgoz34** [comment]
> Try right-clicking the desktop, then choosing View > Show Desktop Icons. Does that help?

nop :(

**Comment by dremin** [comment]
Have you tried logging out and back in again? Explorer may have gotten confused.

**Comment by omerakgoz34** [comment]
oh, fixed!
it was just a explorer bug xd
