### ISSUE TITLE
Mouse back/forward button support on desktop

### ISSUE THREAD

**Issue by davwheat** [cairoshell/cairoshell#306]
**Is your feature request related to a problem? Please describe.**
The desktop does not support mouse back/forward buttons as shortcuts for the back and forwards buttons when browsing folders.

**Describe the solution you'd like**
I'd like the desktop to support these buttons.

**Additional context**

https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mousebutton?view=netframework-4.8#fields

XButton1 is Back
XButton2 is Forward

(at least ['typically'](https://www.autohotkey.com/docs/KeyList.htm#mouse-advanced))

**Comment by josuave** [comment]
Functionality added in Pull Request #307

**Comment by dremin** [comment]
This is available in the latest release.
