### ISSUE TITLE
Search Icon Missing

### ISSUE THREAD

**Issue by ike2117** [cairoshell/cairoshell#308]
**Describe the bug**
From every screenshot I've seen of cario, the top right should have a search, yet my installation doesn't. No matter how many times I reinstall, it never shows.

**Steps to reproduce**
1. Install Cairo. Its not there

**Expected behavior**
A way to search my system

**System information:**
 - Windows version: Windows 10 Build 1909
 - Cairo version: Version 0.3.6842.0 - Pre-release
 - 32-bit or 64-bit: 64 Bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes, but the search icon is missing whether its on or off.

**Additional context**
No matter what I do, it never shows

**Screenshots**
http://prntscr.com/qsmq0k

**Comment by josuave** [comment]
This is due to Windows Search service not being available. See about getting it turned on, log off and back on. Lets us know how it goes

**Comment by dremin** [comment]
Closing due to lack of response.
