### ISSUE TITLE
Settings Metro App is opening as Control Panel in Windows 10

### ISSUE THREAD

**Issue by JoJo-Denton** [cairoshell/cairoshell#309]
**Describe the bug**
When opening Settings (either through the Programs menu or the Desktop Search), instead of the expected Metro App, you see the older-style Control Panel. Its shortcut is displayed as the Metro App shortcut. 

My Hypothesis is that the Settings App shortcut has been incorrectly mapped to Control Panel and is using the wrong icon,even though Control Panel itself is already mapped.

TL, DR: What you expect to be the settings app based on the shortcut's name and icon is actually just regular Control Panel.

**Steps to reproduce**
1. Apply Cairo settings as per screenshots and restart (pay particular attention to "Enable Desktop" being turned on).
2. Try to open Settings via the Programs menu or the Desktop search
3. Both appear as Control Panel.

**Expected behavior**
I expect that the correct operation would be:
- Settings shortcut > Settings App
- Control Panel Shortcut > Control panel

**System information:**
 - Windows version: Windows 10 Pro, 1909
 - Cairo version: 0.3.6842.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes.

**Additional context**
I have a dual-monitor setup.

**Screenshots**

Settings:
![image](https://user-images.githubusercontent.com/59611017/73118935-f3babd00-3f95-11ea-9a69-44f394b886a8.png)
![image](https://user-images.githubusercontent.com/59611017/73118939-f9b09e00-3f95-11ea-8029-7fd4a47854ba.png)
![image](https://user-images.githubusercontent.com/59611017/73118944-06cd8d00-3f96-11ea-97be-8ef988f686cf.png)

Results:
![image](https://user-images.githubusercontent.com/59611017/73118947-16e56c80-3f96-11ea-8fe8-ef5cb56138d3.png)
![image](https://user-images.githubusercontent.com/59611017/73118950-22389800-3f96-11ea-90fd-2a1f4ccf20f9.png)

**Comment by josuave** [comment]
This feature actually pulls its results from the Windows Search Service. Try performing the same search in Windows Explorer and let us know if you get the same results or not. If you do, then you may meed to clear/alter your search index information to get the results you desire

**Comment by dremin** [comment]
Settings is a UWP app. When Cairo is being run as shell, UWP apps cannot launch as they are bootstrapped by Explorer on Windows 10. I would recommend running Cairo at startup rather than running it as shell so that UWP apps can function.

**Comment by dremin** [comment]
This is occurring due to #365, so closing this as a duplicate.
