### ISSUE TITLE
Windows Hotkeys not working.

### ISSUE THREAD

**Issue by Sansyyxd** [cairoshell/cairoshell#311]
**Describe the bug**
When cairo menu is enabled and you press the windows key + r (Example) the programs menu opens but not the hotkeys same with Windows key + i (Settings) and Windows key + e (Explorer)
and nothing opens

**Steps to reproduce**
1. Install Cairo as shell
2. try a windows key shortcut
3. it wont work

**Expected behavior**
Only the Programs menu to open and the hotkey, not work

**System information:**
 - Windows version: Windows 10 Home (1903)
 - Cairo version: 0.3.6842.0 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**
It doesnt work

**Screenshots**

**Comment by josuave** [comment]
Those keyboard shortcuts are managed by Explorer when it is set as shell. If you want them back you will have to have to set windows as shell and have cairo as a startup item

**Comment by Sansyyxd** [comment]
add the keyboard shortcuts then

**Comment by dremin** [comment]
We should implement these hotkeys (where applicable) in Cairo.

**Comment by dremin** [comment]
This is fixed in the latest release.
