### ISSUE TITLE
DynamicDesktop History Handling

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#312]
**Description**
When using the DynamicDesktop Navigation, one would expect the Forward and Backward navigation to traverse the History List. This is not the case.

**Steps to reproduce**
1. Populate the history DynamicDesktop History list by changing the Desktop path a few times. I used Documents, Downloads, Music, Pictures and C:\.
2. Use the back button to traverse the list. Note the directories being displayed.
3. Use the forward button to traverse the list. Note the directories being displayed.

**Expected behavior**
The forward and back actions should traverse the history list and display the proper directory on the desktop.

**Comment by josuave** [comment]
Fix available in Pull Request #307

**Comment by dremin** [comment]
This is fixed in the latest release.
