### ISSUE TITLE
Cant use Search function in explorer.

### ISSUE THREAD

**Issue by KyranStorm** [cairoshell/cairoshell#313]
I installed cairo, set it as the shell, and i cant use the Search bars in the explorer menu or control panel.  clicking in the box does nothing and if i hit any key i get windows error ding sound.

**Comment by dremin** [comment]
In Windows 10 1909 the search field is a UWP component. UWP is not supported by the OS without Explorer running, so it's not something we can fix.

This works if you set Explorer as shell and have Cairo run at startup instead.

**Comment by josuave** [comment]
I wonder if Microsoft was nice enough to have some way of disabling the UWP version
