### ISSUE TITLE
Interaction/Esthetics Issues with App

### ISSUE THREAD

**Issue by jferrazza** [cairoshell/cairoshell#316]
I have a couple ideas and problems with the app:
1. The menu bar is constantly on the top. It would be good to have an auto hide feature especially for those who like Windows fullscreen.
2. The menu bar does not match the rest of Windows 10. I find it a bit of an eyesore. Maybe flatten it or disable transparency. I tried skinning Windows with Stardock every app inherited from the desktop broke WindowBlinds from the suspected relocation of the windows.
3. Manually opening Task View along with certain other views break Cairo slightly as if it's returning to Windows.

EDIT: Number 2 I disabled blurring and shadow and it mostly worked but it doesn't work with Chrome which tries to wrap offscreen but in the process wraps behind the menu bar.

**Comment by dremin** [comment]
Regarding 2, I am working on a flat theme that fits in better with newer Windows versions.

Could you please elaborate number 3? I am able to use Task View without disruption.

**Comment by raiguard** [comment]
+1 for a flatter design, hopefully with translucency. I like Cairo but I do think it looks more Windows 7-esque.

**Comment by dremin** [comment]
@raiguard There is a flat theme included now that you can enable in Cairo Settings, if you'd like!

**Comment by raiguard** [comment]
Ah, didn't see that! My bad. Thanks for the quick response! :D

**Comment by josuave** [comment]
@jferrazza can you elaborate on the third issue? If not, we should consider this closed

**Comment by dremin** [comment]
Closing due to lack of response or reproduction regarding the remaining item.
