### ISSUE TITLE
Cairo overlaps with fullscreen apps.

### ISSUE THREAD

**Issue by RUvlad1** [cairoshell/cairoshell#317]
**Describe the bug**
When an application if fullscreen, Cairo overlaps it.

**Steps to reproduce**
1. Open any application that supports fullscreen
2. Go to fullscreen

**Expected behavior**
The app that is fullscreen should overlap.

**System information:**
 - Windows version: Windows 10 Version 1909 (OS Build 18363.592)
 - Cairo version: 0.3.6842.0 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Screenshots**

![msedge_EEmAJHZSuC](https://user-images.githubusercontent.com/60317461/73135904-e1ee1e00-4058-11ea-91ff-89041e30340b.jpg)

**Comment by RUvlad1** [comment]
Update: Just found out it can get fixed by making Explorer the default shell.

**Comment by josuave** [comment]
We had another user report that, between the time when Cairo is installed and the time the Cairo is run a second time (reboot/sign out/other reason), fullscreen apps didn’t work. There may be a pattern here, There may not.
