### ISSUE TITLE
ShareX Video Recording issue

### ISSUE THREAD

**Issue by LordDamionDevil** [cairoshell/cairoshell#318]
**Describe the bug**
The Shell completely disappears when you try to make a video with ShareX

**Steps to reproduce**
1. Open ShareX
2. Make a Video

**System information:**
 - Windows version: Windows 10 1909 - 18363.592
 - Cairo version: 0.364.2.0
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Comment by dremin** [comment]
I'm not able to reproduce. How are you taking the video, and what other applications are running?

**Comment by LordDamionDevil** [comment]
Seems to be a issue only when you have just installed Cairo after restarting it works without issues.
