### ISSUE TITLE
Windows Store apps not working

### ISSUE THREAD

**Issue by robinhood2014** [cairoshell/cairoshell#319]
**Describe the bug**
I cannot launch any Windows Store apps from Cairo.

**Steps to reproduce**
1. Click Programs > All.
2. Click any Windows Store app that appears in the list (in my case, it's Calculator).
3. An error message appears saying "Class not registered."

**Expected behavior**
The Windows Store app should have launched as it usually would have done if it were launched from Windows Explorer.

**System information:**
 - Windows version: Windows 10 version 1909 build 18363.592
 - Cairo version: 0.3.6842
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

![class-not-registered](https://user-images.githubusercontent.com/6971466/73149713-2d6bf080-4088-11ea-8c29-43b4658bb004.PNG)

**Comment by dremin** [comment]
This is because you have Cairo set as shell, replacing Explorer. This is not recommended in Windows 10, as Explorer bootstraps Windows Store apps. In Cairo settings, try setting Explorer as shell and these should work again with Cairo running.

**Comment by dremin** [comment]
Closing as this is a feature that requires support from the OS.
