### ISSUE TITLE
Modern control panel shortcut

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#32]
OS: Windows 10 x64
Cairo opens the legacy control panel instead of the modern control panel (it is called Immersive control panel in Cairo).
Or control.exe instead of SystemSettings.exe for the corresponding processes.
![screenshot115](https://user-images.githubusercontent.com/32496803/31309116-58426d78-ab81-11e7-9cc8-be1bcdb2dbb4.png)

**Comment by dremin** [comment]
I have added this feature to the Cairo menu on Windows 10 in the latest build. You can update using 'Check for updates' in the Cairo menu.

**Comment by mdmk** [comment]
The new entry in the menu works.
But the app shortcut created with app grabber does the same thing than before.

**Comment by dremin** [comment]
Glad it works! The shortcut that appears in App Grabber is installed by default with Windows but doesn't appear to link to the correct place, so you can remove this shortcut.
