### ISSUE TITLE
Windows Taskbar Autohide disabled after quitting Cairo

### ISSUE THREAD

**Issue by TheComputerNerd88** [cairoshell/cairoshell#320]
After quitting Cairo (Cairo Menu -> Exit Cairo), Cairo attempts to restore taskbar settings, including turning off autohide. However, if you already have autohide turned on, it turns the settings off regardless. Cairo **should** remember your preferences and change and restore them accordingly.

**Comment by josuave** [comment]
@dremin I agree with this. I can only see this functioning properly when Explorer is still shell, if Cairo exits gracefully we should put Explore back into the same state as it was in when we started.

**Comment by dremin** [comment]
We attempt to put Explorer in the same state when exiting, however, it doesn't always seem to work. I wondering if we are not responding to an exit correctly, or if maybe Explorer is closing before we do such that it doesn't get the setting change.

**Comment by dremin** [comment]
The fix is now available in the latest release.
