### ISSUE TITLE
No EDGE-Browser // app not registered

### ISSUE THREAD

**Issue by leisefuxX** [cairoshell/cairoshell#321]
whenever i start edge browser, an error pops up which tells me, my app is not registered. using another browser is not an option. tried to load edge manually, but it also fails.
using latest cairo as shell (no explorer) and with autostart on windows 10 pro.

**Steps to reproduce**
1. open edge via menu or by hand
2. error-message appears

**Expected behavior**
edge opens. i can browse the internet

**System information:**
 - Windows version: win 10 pro 1909, all updates applied
 - Cairo version: latest (Cairo Desktop M3.6842)
 - 32-bit or 64-bit: off course 64 bit (:
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Additional context**

**Screenshots**

**Comment by josuave** [comment]
Did you install Microsoft Edge (Chromium)? If so, it actually replaces the original bundled version. I had the same issue. My solution was to open AppGabber, remove the original shortcut, and then add the new one for the new Edge (Chromium).

**Comment by PeterStrick** [comment]
Windows Store Apps won´t open if Cairo Desktop is the default shell, because Windows Store Apps need Windows Explorer to start correctly. If they are started by something else then Windows Explorer they will give Error Messages about missing DLLs and Classes not being registered.

**Comment by dremin** [comment]
Closing as this is an issue that requires OS support. Use Cairo set to run at startup instead of running as shell to use Cairo with UWP apps.
