### ISSUE TITLE
Question: Virtual Desktops

### ISSUE THREAD

**Issue by Quasaur** [cairoshell/cairoshell#322]
My Work Computer:
Lenovo ThinkPad Carbon X1 (with dock [USB-C])
Windows 10 Enterprise x64 Build 1809
3 HP 27" Monitors connected to dock (one using StarTech's USB2VGAE3

I'm able to use Windows' Virtual Desktop to multiply my workspace 4-fold...does CairoShell support that?

Thanks!

**Comment by dremin** [comment]
Yes, you can use the Windows virtual desktops feature with Cairo (don't install it set to replace Explorer, as Explorer provides this functionality). It should use the existing set up you have in Task View.

**Comment by josuave** [comment]
@dremin i think this can be closed

**Comment by dremin** [comment]
I believe so.
