### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by XorogVEVO** [cairoshell/cairoshell#323]
**Is your feature request related to a problem? Please describe.**
I like this desktop environment but it's really frustrating to actually use the built-in desktop because there's no drag & drop. Of course there's still the Cut Feature but that's just not always the option.

**Describe the solution you'd like**
Add Drag & Drop.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by josuave** [comment]
I agree this should get some attention at some point.

**Comment by dremin** [comment]
Closing as duplicate of #85
