### ISSUE TITLE
Changing any setting in Cairo corrupts Windows profile

### ISSUE THREAD

**Issue by roxylalo** [cairoshell/cairoshell#325]
**Describe the bug**
Whenever I change any setting in Cairo and restart to apply, it crashes immediately upon starting, even after restarting my computer. At first I thought this was simply a weird bug with Cairo, but upon looking into it I saw a lot of crash upon startup issues being related to a corrupted Windows profile. So, I looked up a guide to fix my Windows profile - I noticed that the value for State in my profile was set to 256, so I changed it back to 0, restarted, and hooray, Cairo is working properly again! So I went to continue configuring it, changed a couple settings, and restarted to apply - and boom, same issue again. I checked my registry and the value for State in my user profile is back to 256. Changing it back to 0 and restarting fixes it again, but I'm unable to configure Cairo at all without going through this annoying process.

**Steps to reproduce**
1. Install Cairo, change settings.

**Expected behavior**
I wasn't really expecting much - the settings to change without any hassle, I guess.

**System information:**
 - Windows version: Windows 10 Pro 1909
 - Cairo version: Latest at time of posting (M3.6842)
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Screenshots**
Here's Windows' "Problem Details"
![image](https://user-images.githubusercontent.com/60368289/73218189-162c1200-411f-11ea-865d-8b9da28c54fe.png)

**Comment by josuave** [comment]
Does this also happen when windows explorer is set as shell?

**Comment by PeterStrick** [comment]
> **Describe the bug**
> Whenever I change any setting in Cairo and restart to apply, it crashes immediately upon starting, even after restarting my computer. At first I thought this was simply a weird bug with Cairo, but upon looking into it I saw a lot of crash upon startup issues being related to a corrupted Windows profile. So, I looked up a guide to fix my Windows profile - I noticed that the value for State in my profile was set to 256, so I changed it back to 0, restarted, and hooray, Cairo is working properly again! So I went to continue configuring it, changed a couple settings, and restarted to apply - and boom, same issue again. I checked my registry and the value for State in my user profile is back to 256. Changing it back to 0 and restarting fixes it again, but I'm unable to configure Cairo at all without going through this annoying process.
> 
> **Steps to reproduce**
> 
> 1. Install Cairo, change settings.
> 
> **Expected behavior**
> I wasn't really expecting much - the settings to change without any hassle, I guess.
> 
> **System information:**
> 
> * Windows version: Windows 10 Pro 1909
> * Cairo version: Latest at time of posting (M3.6842)
> * 32-bit or 64-bit: 64-bit
> * In Cairo Settings > Advanced, is Cairo set as shell?: Yes
> 
> **Screenshots**
> Here's Windows' "Problem Details"
> ![image](https://user-images.githubusercontent.com/60368289/73218189-162c1200-411f-11ea-865d-8b9da28c54fe.png)

This did not happen to me a single time. Maybe it´s cause I only set Cairo as the default shell for one day and then resetting Windows Explorer back as the shell but with Cairo autostarting to get things such as the Action Center and UWP Apps starting again in Cairo.

On secound thought, Why is everyone setting Cairo as the default shell if it works just fine without it.

**Comment by dremin** [comment]
@roxylalo This is very strange; I have never seen this issue. Could you please elaborate the registry value in question?

@PeterStrick I saw a video posted recently on YouTube suggesting people set it as default shell, but this is bad advice since Cairo is designed to run alongside Explorer in Windows 10 (due to changes made in the OS, mostly regarding UWP app activation).

**Comment by PeterStrick** [comment]
> @roxylalo This is very strange; I have never seen this issue. Could you please elaborate the registry value in question?
> 
> @PeterStrick I saw a video posted recently on YouTube suggesting people set it as default shell, but this is bad advice since Cairo is designed to run alongside Explorer in Windows 10 (due to changes made in the OS, mostly regarding UWP app activation).

@dremin I know the Video since I first heard about Cairo because it got demonstrated in that video. His YouTube Channel is Michael MJD (https://www.youtube.com/channel/UCS-WzPVpAAli-1IfEG2lN8A) and the video is https://www.youtube.com/watch?v=CH9SdOJEack

Im trying to contact him telling him about his mistake.

**Comment by PeterStrick** [comment]
> > @roxylalo This is very strange; I have never seen this issue. Could you please elaborate the registry value in question?
> > @PeterStrick I saw a video posted recently on YouTube suggesting people set it as default shell, but this is bad advice since Cairo is designed to run alongside Explorer in Windows 10 (due to changes made in the OS, mostly regarding UWP app activation).
> 
> @dremin I know the Video since I first heard about Cairo because it got demonstrated in that video. His YouTube Channel is Michael MJD (https://www.youtube.com/channel/UCS-WzPVpAAli-1IfEG2lN8A) and the video is https://www.youtube.com/watch?v=CH9SdOJEack
> 
> Im trying to contact him telling him about his mistake.

Done. https://twitter.com/PeterStrick_/status/1222221724407803911

**Comment by josuave** [comment]
I believe this can be closed.

**Comment by dremin** [comment]
Agree, if we can get a reproduction, we can reopen.
