### ISSUE TITLE
White Theme - Incomplete?

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#326]
When White theme is chosen it appears to only change the Cairo Menu Bar. All sub-menus, Taskbar and ancillary controls seem to be left untouched

**Steps to reproduce**
1. Set Theme in Settings to White.xaml

**Expected behavior**
Assumed, more of the system should be themed.

**Additional Info**
I suppose we could have a description of each theme, so that on selection of a theme the description is displayed.

**Comment by dremin** [comment]
Yeah this is currently by design as the white theme is more of a demo than anything else. I think it makes sense to give it some love as well. Also, I wonder if we can embed some additional theme data (name, description, author, version, ??) in the XAML?
