### ISSUE TITLE
Programs Menu

### ISSUE THREAD

**Issue by Windowsfree** [cairoshell/cairoshell#331]
I would like to put categories on the left, not the applications themselves.  Similar to the Whisker Menu used in XFCE desktop environment.  As a bonus it would be great to hover over categories to change categories.
I don't believe this relates to the other issues that appear similar.

![whisker](https://user-images.githubusercontent.com/60443718/73472442-0f88df00-4359-11ea-8685-135e6b315712.png)

Thank you.

**Comment by dremin** [comment]
This is available in the latest release.
