### ISSUE TITLE
Cairo Desktop flickers when hovering over an Shortcut

### ISSUE THREAD

**Issue by PeterStrick** [cairoshell/cairoshell#332]
**Describe the bug**
Cairo Desktop flickers when hovering over an Shortcut or opening it.

**Steps to reproduce**
1. Install Cairo Desktop as **not** the default shell.
2. Navigate to a Folder that has a Shortcut in it using the Dynamic Desktop
3. Hover / Press on it. The Dynamic Desktop will flicker when trying to Display the InfoTip of the Shortcut.

**Expected behavior**
Don´t flicker when hovering/pressing on a Shortcut.

**System information:**
 - Windows version: Windows 10 Version 2004 (Build: 19546.1000)
 - Cairo version: 0.3.6842.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
/

**Screenshots**
A video showing/describing the bug.
Link: https://drive.google.com/file/d/1cMNbWO2-xCv_Tlt9c40UwuqvizZHHkvU/view?usp=sharing

**Comment by dremin** [comment]
I can't reproduce the behavior in the video. Does it always happen on your machine? What applications (including in the background) do you have running?

**Comment by PeterStrick** [comment]
> I can't reproduce the behavior in the video. Does it always happen on your machine? What applications (including in the background) do you have running?

I don´t know but it doesn´t flicker anymore.

The bug seems to be gone.

Bute here are my Background Programs:
Adobe Creative Cloud, ASUS Software, Avast Internet Security and SecureLine VPN, DeskScapes 8, Internet Download Manager, ShareX, Steam, Twitch and Discord.

Maybe it ´s DeskScapes 8 since it is deactivated right now and the desktop doesn´t flicker.

**Comment by dremin** [comment]
I would be interested to hear if the issue comes back with DeskScapes activated. For what it's worth, @josuave is implementing a similar feature for a future release.

**Comment by PeterStrick** [comment]
> I would be interested to hear if the issue comes back with DeskScapes activated. For what it's worth, @josuave is implementing a similar feature for a future release.

On further inspectation the issue seems to occur when Disable DeskScapes is pressed in the DeskSpaces Program > Help Icon

Also DeskScapes 8 will not deactivate when pressing this Button.

This can be solved by terminating the DeskScapes 8 Application in TaskManager and stopping it´s service. Doing so will disable DeskScapes 8 and stop the flickering.

**Comment by PeterStrick** [comment]
> > I would be interested to hear if the issue comes back with DeskScapes activated. For what it's worth, @josuave is implementing a similar feature for a future release.
> 
> On further inspectation the issue seems to occur when Disable DeskScapes is pressed in the DeskSpaces Program > Help Icon
> 
> Also DeskScapes 8 will not deactivate when pressing this Button.
> 
> This can be solved by terminating the DeskScapes 8 Application in TaskManager and stopping it´s service. Doing so will disable DeskScapes 8 and stop the flickering.

Also after deactivating DeskScpaes 8 you might need to restart Windows Explorer and Cairo to stop the flickering or restart your computer.

**Comment by dremin** [comment]
Thanks for the details! I'm guessing that DeskScapes is drawing a bottom window, and we go beneath it when we go bottommost (which happens when clicking, etc). I'll try to reproduce. We will need to continue to adjust how the desktop positions itself so that we can handle this better.

**Comment by dremin** [comment]
I was able to reproduce with your instructions, thanks! My above comment is exactly what's happening, so I'm making some changes for the next release so that we don't have to keep repositioning ourselves, and in my testing this resolves the problem (and more) nicely.

If you'd like to try, there is a [build with this fix here.](https://ci.appveyor.com/api/buildjobs/s3ph3x0o22gu0n20/artifacts/Installer%2FCairoSetup_64bit.exe)

**Comment by PeterStrick** [comment]
> I was able to reproduce with your instructions, thanks! My above comment is exactly what's happening, so I'm making some changes for the next release so that we don't have to keep repositioning ourselves, and in my testing this resolves the problem (and more) nicely.
> 
> If you'd like to try, there is a [build with this fix here.](https://ci.appveyor.com/api/buildjobs/s3ph3x0o22gu0n20/artifacts/Installer%2FCairoSetup_64bit.exe)

Thank you, the Build you provided works.

Now I can have animated memes as my desktop background again.
