### ISSUE TITLE
"Not Enough Memory" errors when at about 65% memory usage, and eventually crashes and refuses to reopen.

### ISSUE THREAD

**Issue by DremOSDeveloperTeam** [cairoshell/cairoshell#333]
**Describe the bug**
This may not even be a bug but instead a safety precaution or something, but when my computer is at about 65% memory usage, Cairo throws a lot of "not enough memory" errors. It also eventually crashes and refuses to open again until the memory usage is lowered. It tends to crash easier if I use Desktop Search, too.

**Steps to reproduce**
1. Have about 65% of your computer's memory be used
2. Do anything that uses Cairo, such as opening or closing windows, browsing files, etc.

**Expected behavior**
I'd expect it to only throw these errors when there's actually not a lot of memory left.

**System information:**
 - Windows version: Windows 10 1809
 - Cairo version: 0.3.6842.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes, but I haven't restarted so Explorer is still running.

**Screenshots**
![bug](https://user-images.githubusercontent.com/26072405/73600169-2de60a80-4512-11ea-8097-55b81e1203f4.PNG)

**Comment by dremin** [comment]
This seems to happen when there is some sort of resource leak on the system (doesn't necessarily correlate to high memory usage). The error comes from the OS, so there is not much we can do. If you are able to restart the offending program, things should start working again.
