### ISSUE TITLE
Localize desktop toolbar items

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#338]
- Back
- Parent (Up?)
- Clear History

**Comment by josuave** [comment]
Should the images also be themeable

**Comment by dremin** [comment]
Sure, why not :)

As a side note, "Back" is already localized in the XAML, just not in the code behind when switching between back/parent.

**Comment by josuave** [comment]
Well based on all the mergers and changes I just had to do everything is going to be localized from now on and I’m going to do 100% perfect code

**Comment by dremin** [comment]
You'd be the first person in history to do so 😂
