### ISSUE TITLE
Preloaded modern apps appear on Cairo's taskbar

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#34]
Some times, on start, I have the same few apps shown in task bar:
- Calculator
- Photos
- Modern settings
- Windows Store

![screenshot18](https://user-images.githubusercontent.com/32496803/31357186-fd700d94-ad40-11e7-83a0-46666124fc19.png)

They are background tasks, the apps are preloaded but their windows are invisible.
But the apps are listed in the Cairo's taskbar which is wrong behavior.

**Comment by dremin** [comment]
This seems to happen only when loading Cairo manually after the system has been up for a while in my experience. For some reason the Windows API returns these as active windows even though they are not, and they are not being marked as hidden. I will continue to look for a solution for this, but in the mean time, you can select them and then close the window that appears and the button will be removed.

**Comment by nickisghosty** [comment]
@mdmk  how did you get program icons on the left like a quick launch?

**Comment by mdmk** [comment]
@nickisghosty You need the app grabber to function in order to pin apps.

**Comment by dremin** [comment]
This is fixed in today's release.
