### ISSUE TITLE
TaskBar has different spaces between buttons

### ISSUE THREAD

**Issue by Brummell67** [cairoshell/cairoshell#341]
As the title suggests:
![image](https://user-images.githubusercontent.com/5261273/74034564-d4218c80-49b8-11ea-982b-057d52cf7c73.png)

**Comment by josuave** [comment]
This is a feature of the tasks categorization from appgrabber. If you click the tasks button to the right you will see that the spaces correlate to the categories.

- this has come up before - should we have an infographic about this in the getting started wizard???

**Comment by dremin** [comment]
It is part of the welcome tour, maybe it is not worded well enough?
> Open windows in your taskbar are now organized the same way you choose to categorize your Programs menu. Now, all of your related tasks are grouped together for quick and easy use.

**Comment by dremin** [comment]
Originally Cairo had capsule shaped taskbar buttons instead of the mostly square ones we have now, so it was much more obvious then. I wonder if we should explore that design again, or close this as intentional.

**Comment by dremin** [comment]
A tip was added in the latest release to hopefully make this more clear.
