### ISSUE TITLE
3wutfeiow

### ISSUE THREAD

**Issue by windows10win7posreadywoeskio** [cairoshell/cairoshell#342]
![image](https://user-images.githubusercontent.com/56192384/74036328-a22b1d00-49ee-11ea-864c-36de7744d480.png)

Cairo doesn't restart, i had to use the start menu shortcut.

OS: Windows 10 Pro 1909
Processor: Intel Core i3

**Comment by josuave** [comment]
What are the steps to reproduce this issue? Does it persist after cairo was restarted?

**Comment by windows10win7posreadywoeskio** [comment]
Nope, after my discovers, this happened......

**Comment by windows10win7posreadywoeskio** [comment]
Yeah, i forgot, i deleted the template

**Comment by windows10win7posreadywoeskio** [comment]
FD
