### ISSUE TITLE
Cairo doesn't always restart after error

### ISSUE THREAD

**Issue by windows10win7posreadywoeskio** [cairoshell/cairoshell#343]
**Describe the bug**
Cairo doesn't restart after clicking OK

**Steps to reproduce**
1. Press Windows key
2. Click Expand
3. Click Cairo Desktop

**Expected behavior**
Error that would restart Cairo when clicking OK.

**System information:**
 - Windows version: Windows 10 1909
 - Cairo version: 0.3.684.2.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/56192384/74038534-f801c400-49f2-11ea-87e2-1a4b8207e878.png)

**Comment by windows10win7posreadywoeskio** [comment]
K

**Comment by windows10win7posreadywoeskio** [comment]
~~IM GONNA CROSS YOUR ASS~~

**Comment by dremin** [comment]
This error should actually be fixed in the latest release. However, I will look into the restart issue. Thanks!

**Comment by windows10win7posreadywoeskio** [comment]
No problem!

**Comment by windows10win7posreadywoeskio** [comment]
No problem!

**Comment by windows10win7posreadywoeskio** [comment]
~~No problem!~~ THanks
