### ISSUE TITLE
Bug - need defense around user inputted fields

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#344]
From Discord - `i accidentally put a quote mark in the time field and now the shell won't open`

**Comment by dremin** [comment]
We probably should add some sanitization in the menu bar `clock_Tick` method.

**Comment by josuave** [comment]
Sanitize on load or save would cutdown on logic. Pretty easy to have a fallback to the system format string if it fails

**Comment by dremin** [comment]
Good point. I wonder which characters we need to strip? I am surprised this one causes an issue, since special characters are used as part of both date and time strings.

**Comment by josuave** [comment]
Its possible it was another issue. I will attempt to reproduce today.

**Comment by josuave** [comment]
This should be complete, as far as UI settings management is concerned. We could implement safeguards at the setting level as a future task.

**Comment by dremin** [comment]
This is now available.
