### ISSUE TITLE
24 hour clock

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#35]
The clock is 12 hour.
I would like an option to have 24 hour, or at least an AM/PM indicator.
All I managed to do in the settings is to add a digit to the clock, so for example, 2:53 is displayed 02:53.
Perhaps the option already there and I don't know what time format to use in the option field?

**Comment by dremin** [comment]
Try using a capital H in the time format, this should give you 24 hour time! Example: `ddd H:mm`

![screen shot 2017-10-11 at 6 47 33 pm](https://user-images.githubusercontent.com/7373633/31471013-b9287cd2-aeb4-11e7-80ba-76377654fa00.png)

**Comment by mdmk** [comment]
![screenshot20](https://user-images.githubusercontent.com/32496803/31494314-0be5ab40-af53-11e7-9e7e-f9cd130feec9.png)

Exactly what I wanted, thanks!
Could you later add a tooltip when hovering the time format field in order to give some directives about the syntax?
Or a clickable (?) button next the field, or something similar?

**Comment by dremin** [comment]
Good idea! I'll add a link to this page: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
Also, I will adjust the default format to be correct across regions.

**Comment by mdmk** [comment]
The "H" thing is [here (custom)](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and not [there (standard)](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings).

Very informative link but perhaps a bit complicated.
But it has a technical benefit, the page is available in a wide variety of languages.
It leads me to the question:
Could you also link to the correct language for the page?
I mean, in https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings there is `en-us`. The code region is `en_US` if I'm correct. It should suffice to subtitute the underscore "_" by a dash "-" and make the string lowercase. And so `fr-fr` instead of `fr_FR` and so on...

**Comment by dremin** [comment]
Good point, maybe I should approach this differently. It may make more sense to add a tooltip with some examples, and localization for this will be handled in #16.

**Comment by dremin** [comment]
This is implemented in today's update.

**Comment by mdmk** [comment]
@dremin The tooltip is missing `hh Hour (12-hour, leading zero)`.

**Comment by dremin** [comment]
@mdmk whoops! I just released an update that fixes this.
