### ISSUE TITLE
Cairo top bar and icon tray showing in full screen apps/videos

### ISSUE THREAD

**Issue by zbholman** [cairoshell/cairoshell#350]
When watching a video and enabling full screen view, the Cairo app tray and top menu bar still show.

**Comment by dremin** [comment]
What application are you using that is not being detected as full screen? What version of Cairo and Windows?

**Comment by zbholman** [comment]
As of yesterday, the latest version (checked for updates and none available).

I'm not at my computer right now, but I was using the latest version of Firefox, and Windows 10 (not sure which release exactly).

I can provide more details when I get home and have access to the machine I found this issue with.

**Comment by dremin** [comment]
Interesting, I use Firefox to test the full screen awareness and it works on my machines. Any additional information you can provide, especially regarding Firefox version/config/addons would help!

**Comment by dremin** [comment]
@zbholman I am trying a new full screen detection method, could you please try [this build](https://ci.appveyor.com/api/buildjobs/wf5r53ttioewy1lu/artifacts/Installer%2FCairoSetup_64bit.exe) and see if it works as expected for you?

**Comment by VirusRenamon** [comment]
> @zbholman I am trying a new full screen detection method, could you please try [this build](https://ci.appveyor.com/api/buildjobs/wf5r53ttioewy1lu/artifacts/Installer%2FCairoSetup_64bit.exe) and see if it works as expected for you?

Same issue, but on Brave browser. I used the build you linked to, no change in full screen behavior.

**Comment by dremin** [comment]
I'm at a bit of a loss here.. Can you increase logging level to Debug in Cairo Settings > Advanced, restart Cairo, then try to fullscreen those browsers? Afterwards, could you please attach the current log file in `%localappdata%\Cairo_Development_Team\Logs`? Thanks!

**Comment by VirusRenamon** [comment]
[03-09-2020.log.txt](https://github.com/cairoshell/cairoshell/files/4309562/03-09-2020.log.txt)

Made it a .log.txt extention cause github doesnt like .log, should open just the same either way.

Made sure to be in Debug logging mode, restared Cario and tested both browsers. Hopefully it contains something useful because I poked around it and all I can see is my wifi point and my tray programs along with other misc things.

**Comment by dremin** [comment]
@VirusRenamon thanks! Question- are you using a scaling setting different than 100% in Display settings?

**Comment by VirusRenamon** [comment]
@dremin Yes and no, I am using 175% on my secondary monitor and 100% on my main monitor.

**Comment by dremin** [comment]
@VirusRenamon Which monitor are you full-screen-ing your browser on?

**Comment by VirusRenamon** [comment]
@dremin the main monitor, using 100%

**Comment by dremin** [comment]
@VirusRenamon Thanks for the details! I think I got it, can you try [this build](https://ci.appveyor.com/api/buildjobs/e9gt1qsp7myng1th/artifacts/Installer%2FCairoSetup_64bit.exe)?

**Comment by VirusRenamon** [comment]
@dremin confirmed fixed for both browsers I used.

**Comment by dremin** [comment]
@VirusRenamon Great! Thanks for helping narrow this one down!

**Comment by katawajojo** [comment]
I just want to post and say this bug has popped back up.

**Comment by dremin** [comment]
Did it begin after installing a specific update?

**Comment by katawajojo** [comment]
it began about 3 updates ago or so. I don't know exactly which one it was

**Comment by dremin** [comment]
@katawajojo I did some more testing and found an issue that affected a few specific apps (such as Chrome and Edge). If you would like to see if the fix for this issue helps your scenario, [you can try installing this build](https://ci.appveyor.com/api/buildjobs/x5tjhqk4w06k14u7/artifacts/Installer%2FCairoSetup_64bit.exe).

**Comment by katawajojo** [comment]
Yes, this build fixes the issue.
