### ISSUE TITLE
Some Notification Area icons don´t open when doubleclicked

### ISSUE THREAD

**Issue by PeterStrick** [cairoshell/cairoshell#351]
**Describe the Bug**
Some Notification Area Icons like Avast SecureLine and Avast Battery Saver don´t open when doubleclicked. They do open normal in Windows Explorer.

**Steps to reproduce**
1. Install Avast SecureLine or Battery Saver
2. Launch the Application so it creates a notification area icon.
3. Try to doubleclick it. It ain´t work.

**Expected behavior**
Open the Application when doubleclicked like it does in the Windows Explorer.

**System Information:**
 - Windows Version: 2004 (Build 19569.1000) (Insider-Preview)
 - Cairo Version: 0.3.6943.0 (latest version available)
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as Shell?: **No**

**Screenshots**
Video uploaded to Dropbox describing the issue.
https://dl.dropboxusercontent.com/s/8sghuoj5gh7rzop/fpcbedvNLd.mp4

**Comment by dremin** [comment]
Do you know if they worked in the previous build, or were these icons never working correctly with Cairo?

**Comment by PeterStrick** [comment]
> Do you know if they worked in the previous build, or were these icons never working correctly with Cairo?

They never worked at all actually. They only opened in Windows Explorer. you can´t even right click them in Cairo. Other Apps and Avast Programs open and right click fine in Cairo.

**Comment by josuave** [comment]
@PeterStrick have any of the latest builds worked for you?

**Comment by PeterStrick** [comment]
> @PeterStrick have any of the latest builds worked for you?

The latest build still doesn´t do naything when pressing the Avast SecureLine icon in the notification area of cairo. Nor when Cairo is or isn´t set as shell. Can´t say the same with Avast Battery Saver since I don´t use that program anymore. Every other Application including Avast Omni and Avast Driver Updater opens fine.

**Comment by LoTechFo** [comment]
Also right clicking does not display context menus for some system tray icons.

**Comment by dremin** [comment]
@PeterStrick I got the Avast apps working; if you'd like you can [try this build](https://ci.appveyor.com/api/buildjobs/m4clrg1mi59u9gr3/artifacts/Installer%2FCairoSetup_64bit.exe) which includes the improvements.

**Comment by PeterStrick** [comment]
> @PeterStrick I got the Avast apps working; if you'd like you can [try this build](https://ci.appveyor.com/api/buildjobs/m4clrg1mi59u9gr3/artifacts/Installer%2FCairoSetup_64bit.exe) which includes the improvements.

Thanks! The Avast apps now open when they are double clicked.

**Comment by PeterStrick** [comment]
> > @PeterStrick I got the Avast apps working; if you'd like you can [try this build](https://ci.appveyor.com/api/buildjobs/m4clrg1mi59u9gr3/artifacts/Installer%2FCairoSetup_64bit.exe) which includes the improvements.
> 
> Thanks! The Avast apps now open when they are double clicked.

Although I couldn´t test if they work if Cairo is set as the default shell, as it seems that the latest Windows Insider Preview (2004 Build 20241.1005) launches Windows Explorer as the shell, regardless what you do and change in Cairo, the Avast apps seem to work fine.
