### ISSUE TITLE
Disappearing top bar and problem with bottom bar

### ISSUE THREAD

**Issue by KhazAkar** [cairoshell/cairoshell#352]
**Describe the bug**
Top bar disappears after several lock/unlock cycles, bottom bar can't keep windows taskbar hidden.

**Steps to reproduce**
1. Cairo shell not as replacement for windows explorer shell
2. Lock/unlock screen several times with ctrl+alt+delete and hitting "lock", then unlock with your password

**Expected behavior**
Top bar doesn't disappear and bottom bar still keeps windows taskbar to hide

**System information:**
 - Windows version:  Windows 10, 1809
 - Cairo version: 0.3.6943.0 - Pre-release
 - 32-bit or 64-bit: 64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional info**
Installed without Admin rights by unpacking installer with 7-zip and launching CairoDesktop.exe - I know It's bad, but I don't have admin rights at work.
In order to have it working again you need to kill and relaunch CairoDesktop.exe

**Comment by dremin** [comment]
Interesting, are there any changes to the screen configuration happening while the system is locked? For example, docking/undocking a laptop, connecting or removing screens, DPI changes, resolution changes, etc?

**Comment by KhazAkar** [comment]
No, just sometimes I need to switch off/on display because docking station not always wakes up all displays.

**Comment by dremin** [comment]
Is this better in the latest release?

**Comment by KhazAkar** [comment]
I will tell when It will pass further tests, but so far works better :)

**Comment by KhazAkar** [comment]
Well, works better, but on second screen instead of force hiding windows task bar it allows it to reveal with mouse pointer hover

**Comment by dremin** [comment]
@KhazAkar I made further adjustments in the latest release, is it better now?

**Comment by KhazAkar** [comment]
Testing latest release right now, I will give feedback after some time :)

**Comment by dremin** [comment]
Can this be closed in favor of #380 which discusses the taskbar issue?

**Comment by KhazAkar** [comment]
Yes, sure, I will close it :)
