### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by MrMic** [cairoshell/cairoshell#353]
**Describe the bug**
Where acn I find the uninstaller ?

**System information:**
 - Windows version: windows 10
 - Cairo version:  Version 0.3.6943.0 - Pré-version

 - r 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?:  yes

**Comment by dremin** [comment]
First, in Cairo Settings > Advanced, set Windows Explorer as shell, and follow the instructions to log off. Then, once you log in again, exit Cairo if it is running, then you can remove Cairo from Control Panel > Programs and Features.

**Comment by dremin** [comment]
Closing as uninstall instructions have been provided above.
