### ISSUE TITLE
Is there any current way to change keyboard layouts on Cairo?

### ISSUE THREAD

**Issue by GeetHaab** [cairoshell/cairoshell#355]
I have read the other issues, and all I see are suggestions. I need to know is there a current way to change keyboard layouts because I use English most of the time when I'm on the computer and my native language to chat with my friends. Do I need to include something in the settings, in the setup, or something entirely different? I won't mind if it's an "aftermarket" fix.

**Comment by josuave** [comment]
Do you have cairo set as shell?

**Comment by GeetHaab** [comment]
@josuave Yes, of course. (sorry for my late reply)
