### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by YAR-Oracool** [cairoshell/cairoshell#357]
**Describe the bug**
I downloaded the shell about 3 days ago, the moment of installing it worked great, things were fast all of the needed info was on the top bar aside from the battery which raised so red flags.
The second day I turned on the laptop the wifi indicator was gone too. On the third day, I get the error showed on the uploaded photo. if you press Yes you would sit and watch a black screen for the rest of eternity if you press No the shell restarts but the programs act as if it's not there and go under it. The way to solve this is to go to Cario settings and change something that Cario has to restart for it to apply. 
**Steps to reproduce**
1.  Press the power button
2. Boot into windows
3. Log in
![Untitled](https://user-images.githubusercontent.com/35577618/76690127-6ec55900-6652-11ea-8416-732e295a5791.jpg)

**Expected behavior**
I expect to log in not seeing an error and have my wifi info and my battery info showed to me.

**System information:**
 - Windows version: 1909 (OS Build 18363.719
 - Cairo version: 0.3.6947.0
 - 32-bit or 64-bit: 64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  Cario is the default shell and replaced Explorer.

**Additional context**
Atm 90% of the times I get this error after boot and when it happens window managers do not work which in my case is called Aqua Snap.
Not sure why the first 2 days this didn't happen but I think this started after I set my taskbar to be at the top but after reverting it back to down, I still get the same error.

**Screenshots**

**Comment by dremin** [comment]
Do you have the option to show the menubar or taskbar on multiple screens enabled? If you do, can you try disabling them and report back if it helps?

**Comment by dremin** [comment]
Is this any better in [this build?](https://ci.appveyor.com/api/buildjobs/7b1dqj6g576w2sd0/artifacts/Installer%2FCairoSetup_64bit.exe)

**Comment by dremin** [comment]
I figured out the crash, but it was happening because the taskbar wasn't initializing properly. I added some logging in the latest release if you are still experiencing the problem.

**Comment by YAR-Oracool** [comment]
Sorry, it took me this long, I was... busy. I tried turning off multi-monitor but the same error happens and it seems like without explorer starting up first the info won't show up. 

I hadn't tried the new build yet but I am gonna try it now.

**Comment by YAR-Oracool** [comment]
The new update has fixed everything apart from 1 thing.  My Window manager still doesn't work if Cario is activated first, like it works but the shortcuts seem to not activate because for example if windows key + -> is attach a window to the right, as soon as you press windows key Cario's Programs tab collapses so the hotkey for window manager won't trigger.

Also in case, you lunch explorer first than terminated it with taskbar to fix this your wallpaper just disappears.

**Comment by dremin** [comment]
> The new update has fixed everything apart from 1 thing. My Window manager still doesn't work if Cario is activated first, like it works but the shortcuts seem to not activate because for example if windows key + -> is attach a window to the right, as soon as you press windows key Cario's Programs tab collapses so the hotkey for window manager won't trigger.

Thanks for verifying! I'll check out AquaSnap and see if I can reproduce this part.

> Also in case, you lunch explorer first than terminated it with taskbar to fix this your wallpaper just disappears.

On Windows 10, the shell is responsible for displaying wallpaper. If Explorer is started before Cairo, then Explorer is displaying the wallpaper. I don't recommend terminating Explorer while Cairo is running, because then neither Cairo nor Explorer are running in shell mode, so you run in to some problems such as this.

**Comment by YAR-Oracool** [comment]
The original problem is this issue has been fixed which was error on startup but the secondary one still exists. Since the main one is solved than leaving this open is meaningless.
