### ISSUE TITLE
Can't edit new shortcut target after creating on desktop

### ISSUE THREAD

**Issue by mathacka** [cairoshell/cairoshell#358]
I was trying to create a new shortcut simply by right clicking on the desktop, selecting "New -> Shortcut" then right clicking on the "New shortcut" icon and going to properties, when I get there the "Target" field is un-editable, "Open File Location" simply does nothing to improve the situation, and the "Start in" field is also un-editable.

![example](https://user-images.githubusercontent.com/1857352/77093511-70d84080-69e1-11ea-8c69-2d14a51ab3eb.png)

**Comment by josuave** [comment]
@mathacka do you have cairo set as shell?

**Comment by dremin** [comment]
@josuave I believe this can happen either way if you create a new shortcut from the "New" menu on the desktop. Interestingly I see the same behavior in Explorer++. Haven't yet found an example way to hook in to pop the wizard.
