### ISSUE TITLE
Untranslated desktop background style options if background type is Image

### ISSUE THREAD

**Issue by curoviyxru** [cairoshell/cairoshell#360]
**Describe the bug**
Desktop background style aren't translated if type is Image.

**Steps to reproduce**
1. Open Cairo setttings / Desktop / Desktop background
2. Choose Background type: Image
2. Open Style combobox

**Expected behavior**
Translated options. (non-English)

**System information:**
 - Windows version: 10.0.18363.719
 - Cairo version: 0.3.7383.40742
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**
If type is Windows, options are translated.

**Screenshots**
![image](https://user-images.githubusercontent.com/61984636/77144742-bbb48f80-6a97-11ea-88d5-8cfaba2600dd.png)
![image](https://user-images.githubusercontent.com/61984636/77144795-df77d580-6a97-11ea-9b5a-4d4b055bf49e.png)

**Comment by dremin** [comment]
This is fixed in the latest release.
