### ISSUE TITLE
Crash while running ACT.

### ISSUE THREAD

**Issue by Adwardbear** [cairoshell/cairoshell#363]
**Describe the bug**
Cairo desktop error after Advanced Combat Tracker (ACT) is running for a while. I am certain this is being caused by ACT as I never have a crash when it is not running.

**Steps to reproduce**
1. Run ACT
2. After about 30m-1hr Cairo will crash

**System information:**
 - Windows version: 10
 - Cairo version: 0.3.971.0
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Screenshots**

![image](https://user-images.githubusercontent.com/151639/77265790-94c3ac80-6c95-11ea-884d-77821191a8d7.png)

**Comment by curoviyxru** [comment]
I have this bug too, but it appears randomly. :/ Answering "Yes" causes "Hard error" and Cairo just freezes, until you kill it in Task Manager and launch again.

**Comment by dremin** [comment]
Do you have to perform any specific actions in ACT for this to happen?

**Comment by Adwardbear** [comment]
No, it runs in the background while playing FFXIV, crash happens randomly when trying to use the Cairo UI with it running

**Comment by dremin** [comment]
Could you please try installing [this build](https://ci.appveyor.com/api/buildjobs/qgs8q290l6ok6acy/artifacts/Installer%2FCairoSetup_64bit.exe) and see if it is any better?

**Comment by Adwardbear** [comment]
So far no issues with that build, thanks!
