### ISSUE TITLE
Full Width Taskbar DesktopOverlay and Tasklist Press Style Incorrect

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#367]
**Describe the bug**
When click either DesktopOverlay or Tasklist when the taskbar is set to full width still shows a curved corner

**Steps to reproduce**
1. Click it and observer

**Expected behavior**
Style for pressed button should not have a curved corner

**Comment by dremin** [comment]
Is this a duplicate of #295?

**Comment by josuave** [comment]
Hmmm, i will have to try the different styles. I think i was using default style rather than flat.

**Comment by josuave** [comment]
This is a duplicate of #295. I am closing
