### ISSUE TITLE
Universal Windows Platform Support Cairo as Shell Mode

### ISSUE THREAD

**Issue by mealpi** [cairoshell/cairoshell#374]
Please add support Universal Windows Platform (UWP) for Cairo as Shell Mode.
UWP Apps not working on Cairo Shell Mode.

**Comment by AnErrupTion** [comment]
The dev could add an option to use the shell to execute programs. (ProcessStartInfo.UseShellExecute set to false for UWP programs for example)

**Comment by artdeell** [comment]
Yeah. Someone should contribute UWP support, because, hey, i can't view images with Windows-integrated tool.

**Comment by josuave** [comment]
@dremin we should create a low level [feature request] and close these requests in favor of it.

**Comment by dremin** [comment]
@josuave I agree, or edit an existing issue to make it more appropriate as a catch-all for duplicates.

**Comment by dremin** [comment]
Closing as duplicate of #365
