### ISSUE TITLE
Cairo crashes when you click on some folders in dynamic desktop!

### ISSUE THREAD

**Issue by mealpi** [cairoshell/cairoshell#375]
[16.04.2020 03:41:56] Error: Would you like to restart Cairo?

Please submit a bug report with a screenshot of this error. Thanks! 
Message: Aritmetik işlemde taşma veya yetersiz gelme.
Target Site: Double RoundLayoutValue(Double, Double)
Version: 0.3.7015.0

   konum: System.Windows.UIElement.RoundLayoutValue(Double value, Double dpiScale)
   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   konum: System.Windows.UIElement.Measure(Size availableSize)
   konum: System.Windows.Window.MeasureOverrideHelper(Size constraint)
   konum: System.Windows.Window.MeasureOverride(Size availableSize)
   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   konum: System.Windows.UIElement.Measure(Size availableSize)
   konum: System.Windows.ContextLayoutManager.UpdateLayout()
   konum: System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   konum: System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   konum: System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   konum: System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	:::Exception Details:::
	System.ArithmeticException: Aritmetik işlemde taşma veya yetersiz gelme.
	   konum: System.Windows.UIElement.RoundLayoutValue(Double value, Double dpiScale)
	   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   konum: System.Windows.UIElement.Measure(Size availableSize)
	   konum: System.Windows.Window.MeasureOverrideHelper(Size constraint)
	   konum: System.Windows.Window.MeasureOverride(Size availableSize)
	   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   konum: System.Windows.UIElement.Measure(Size availableSize)
	   konum: System.Windows.ContextLayoutManager.UpdateLayout()
	   konum: System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
	   konum: System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
	   konum: System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
	   konum: System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
	   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**System information:**
 - Windows 10.0.18363
 - Cairo version: 0.3.7015.0 64-bit 
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Comment by dremin** [comment]
Does this happen only in certain folders? Is there anything specific about these folders, or something that is in common with folders that are causing this error?

**Comment by mealpi** [comment]
I have same error again.  I don't know how is happen.  I clicked on a folder i clicked right mouse, than open new windows and finally crash. I tried 2 different folders on Documents and D drive but same problem.
Thanks.
--------------------------------------------------------------------------------
Error: Would you like to restart Cairo?

Please submit a bug report with a screenshot of this error. Thanks! 
Message: Aritmetik işlemde taşma veya yetersiz gelme.
Target Site: Double RoundLayoutValue(Double, Double)
Version: 0.3.7015.0

   konum: System.Windows.UIElement.RoundLayoutValue(Double value, Double dpiScale)
   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   konum: System.Windows.UIElement.Measure(Size availableSize)
   konum: System.Windows.Window.MeasureOverrideHelper(Size constraint)
   konum: System.Windows.Window.MeasureOverride(Size availableSize)
   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   konum: System.Windows.UIElement.Measure(Size availableSize)
   konum: System.Windows.ContextLayoutManager.UpdateLayout()
   konum: System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   konum: System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   konum: System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   konum: System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	:::Exception Details:::
	System.ArithmeticException: Aritmetik işlemde taşma veya yetersiz gelme.
	   konum: System.Windows.UIElement.RoundLayoutValue(Double value, Double dpiScale)
	   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   konum: System.Windows.UIElement.Measure(Size availableSize)
	   konum: System.Windows.Window.MeasureOverrideHelper(Size constraint)
	   konum: System.Windows.Window.MeasureOverride(Size availableSize)
	   konum: System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   konum: System.Windows.UIElement.Measure(Size availableSize)
	   konum: System.Windows.ContextLayoutManager.UpdateLayout()
	   konum: System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
	   konum: System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
	   konum: System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
	   konum: System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
	   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by josuave** [comment]
Are you running multiple monitors? Are the DPI settings different? Is there any other details you could provide? Excessively long paths or filenames?

**Comment by josuave** [comment]
@mealpi is this still happening?

**Comment by dremin** [comment]
Closing due to lack of response.
