### ISSUE TITLE
bug(startup): shell:startup programs doesn't run in Windows start

### ISSUE THREAD

**Issue by Kristinita** [cairoshell/cairoshell#376]
### 1. Summary

**If** CairoShell is my shell:

1. None of the programs from [**`shell:startup`**](https://www.thewindowsclub.com/startup-folder-in-windows-8) run for me when Windows start.
1. Programs that added to autostart via other methods start successfully for me.

### 2. Steps to reproduce

I set CairoShell my default shell → I restart Windows → all my programs from `shell:startup` doesn't run in Windows start.

I restart Windows again → problem are reproduced.

### 3. Environment, configuration and debugging information

1. [**CairoShell log**](https://www.pastery.net/jhdwmf/)
1. `shell:startup` Programs list in red square (screenshot from [**Autoruns**](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)):

    ![`shell:startup` programs](https://i.imgur.com/U1Uq5eE.png)

    (Programs with green icon and `H` letter is my custom [**AutoHotkey**](https://autohotkey.com) scripts)

1. [**CairoShell `user.config`**](https://www.pastery.net/mqaddx/)

Thanks.

**Comment by dremin** [comment]
Thanks! Sorry, it looks like we have missed some startup locations, we will get them all added and track it in this issue.

**Comment by dremin** [comment]
So we actually weren't missing this folder; I broke loading startup items from folders completely when I made directory loading async. Going to refactor this.

**Comment by dremin** [comment]
@Kristinita could you please try [this build](https://ci.appveyor.com/api/buildjobs/md6ffaoo44e896f8/artifacts/Installer%2FCairoSetup_64bit.exe) and report back if applications start now?

**Comment by dremin** [comment]
This is fixed in the latest release.
