### ISSUE TITLE
Change the Name

### ISSUE THREAD

**Issue by keithga** [cairoshell/cairoshell#379]
There is *ALREADY* a shell for windows called Cairo.

https://en.wikipedia.org/wiki/Cairo_(operating_system)

The windows 95 user interface was based on the work done internally on the Cairo User Interface.

Usage of the name "Cairo" as a desktop interface is confusing, Recommend changing.

**Comment by AnErrupTion** [comment]
"There is ALREADY a shell for windows called Cairo."
No. It was NOT a shell, but an operating system (as seen in the link itself), while this Cairo is a shell.

**Comment by ebkalderon** [comment]
If you read the article itself, "Cairo" refers to an internal codename for an unreleased operating system project at Microsoft. Given that "Cairo" and the Cairo shell bear no similarities, and moreover, the former ultimately never yielded a finished product under that name, I don't think a name change would be called for here.

**Comment by dremin** [comment]
Thanks for bringing this up, but we do not have any intentions of changing the name.
