### ISSUE TITLE
Cairo settings window is considered as a graphic program by graphic card panel

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#38]
Sorry, not a real issue.
I have an nvidia graphic card, with the geforce experience software.
This panel offers an FPS counter for games.
It is activated by default on game or graphic intensive softwares.
The cairo settings shows a counter (the green 1 in the top right corner), so I think something is wrong.
![screenshot21](https://user-images.githubusercontent.com/32496803/31496069-33babc76-af5a-11e7-86aa-61ae9b329473.png)
Absolutely a minor issue, it is just for mentionning.

**Comment by dremin** [comment]
This is probably due to Cairo being drawn using GPU acceleration. I've been using MSI Afterburner to display FPS and other info in games and it doesn't have this issue.

**Comment by dremin** [comment]
I'm going to close this since this is an issue with GeForce Experience detecting incorrectly. If it has an exclusions feature I would try using that and excluding Cairo, otherwise another program may be the best solution for this.

**Comment by mdmk** [comment]
The FPS doesn't appear with Fraps.
So definitely a geforce experience problem.
