### ISSUE TITLE
[Feature Request] add option to hide window labels on taskbar

### ISSUE THREAD

**Issue by mrjones2014** [cairoshell/cairoshell#381]
it would be awesome to have an option to hide the window labels on the taskbar for open windows, and show only the icons, in order to preserve space.

I imagine this looking similar to the MacOS dock, where open windows are grouped with your pinned icons, like if you open a pinned app, it opens and shares the icon with the pinned item, rather than creating a new item on the task bar.

**Comment by dremin** [comment]
To clarify, are you looking for similar behavior to the Windows 7-10 taskbar groupings?

**Comment by mrjones2014** [comment]
@dremin yes. stack instances of same application, and show only icon.

**Comment by dremin** [comment]
Closing this, as the label hiding feature is now available in the latest release, and #52 covers the grouping part.
