### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by Alteroku** [cairoshell/cairoshell#385]
**Action center icon disappears**
The action center icon is gone, and is no longer displayed.
The option is enabled in Cairo DTE settings.

**System information:**
 - Windows version: Windows 10 Pro
 - Cairo version: 0.3.7015.0 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Comment by dremin** [comment]
Which build of Windows 10 are you using?

**Comment by Alteroku** [comment]
> 
> 
> ~Which build of Windows 10 are you using?~ Sorry, just noticed that you have Cairo set as shell. This feature is not supported with Cairo set as shell due to Action Center being a feature of `explorer.exe`.

That's fine the action center disappears when cairo is set as shell and the user logs out, but stays when I have it set to start on startup. So that makes sense.

**Comment by josuave** [comment]
Should this be closed?

**Comment by dremin** [comment]
Yeah, I think it was reopened inadvertently.
