### ISSUE TITLE
Location of Menu Bar

### ISSUE THREAD

**Issue by danielks11** [cairoshell/cairoshell#387]
**Is your feature request related to a problem? Please describe.**
I am using Cairo Desktop on Hyper V Server 2019 with Server Core App Compatibility Feature on Demand. Cairo, so far, is working okay but the one issue I have is that due to the fact that the menu bar is located on the top of the screen, I am unable to resize the application I am using because the Menu Bar is positioned over where the Application's Minimize, Restore and Close buttons in the top right-hand corner. I tried checking the Cairo Settings to see if I can move the menu bar to the bottom of the screen or set it to auto-hide but I am not seeing any such option.

Also, when Google Chrome is maximized, it's hard to click on tabs as the tabs are behind the menu bar.

See the screenshot below.

**Describe the solution you'd like**
I would like the functionality added to change the location of the Menu bar or hide it. In Windows, the Menu button (Start button) is in the bottom left-hand corner of the screen and it is only displayed when you click it or press the Start key on the keyboard. If you can add both options, it would be nice. Users can choose to display the menu bar as always as the default or choose to move it to the bottom of the screen or choose to add a menu button on the taskbar and display the menu when the button is clicked.

Alternatively, if, when maximized, the application can be under the menu bar. That is, the menu bar would be at the very top of the screen and the application title bar would be under it and not behind it.

**Describe alternatives you've considered**
Right now, I have to click the application in the taskbar to minimize or show the application. Which is okay but sometimes you want to click the application title bar and drag the window etc. Because the menu bar is on top it is hard to select the application title bar.

Additional context
![screenshot](https://user-images.githubusercontent.com/65672381/82474319-de175900-9a98-11ea-83ae-915818dfd623.PNG)

**Comment by danielks11** [comment]
**Is your feature request related to a problem? Please describe.**
I am using Cairo Desktop on Hyper V Server 2019 with Server Core App Compatibility Feature on Demand. Cairo, so far, is working okay but the one issue I have is that due to the fact that the menu bar is located on the top of the screen, I am unable to resize the application I am using because the Menu Bar is positioned over where the Application's Minimize, Restore and Close buttons in the top right-hand corner. I tried checking the Cairo Settings to see if I can move the menu bar to the bottom of the screen or set it to auto-hide but I am not seeing any such option. 

Also, when Google Chrome is maximized, it's hard to click on tabs as the tabs are behind the menu bar. 

See the screenshot below.

**Describe the solution you'd like**
I would like the functionality added to change the location of the Menu bar or hide it. In Windows, the Menu button (Start button) is in the bottom left-hand corner of the screen and it is only displayed when you click it or press the Start key on the keyboard. If you can add both options, it would be nice. Users can choose to display the menu bar as always as the default or choose to move it to the bottom of the screen or choose to add a menu button on the taskbar and display the menu when the button is clicked.

Alternatively, if, when maximized, the application can be under the menu bar. That is, the menu bar would be at the very top of the screen and the application title bar would be under it and not behind it.

**Describe alternatives you've considered**
Right now, I have to click the application in the taskbar to minimize or show the application. Which is okay but sometimes you want to click the application title bar and drag the window etc. Because the menu bar is on top it is hard to select the application title bar.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/65672381/82474079-85e05700-9a98-11ea-9815-a724ae163568.PNG)

**Comment by dremin** [comment]
The menu bar should not obstruct the window, by chance was Chrome opened before Cairo in this example?

**Comment by danielks11** [comment]
> The menu bar should not obstruct the window, by chance was Chrome opened before Cairo in this example?

Hello. Thank you for your response.

Cairo is set to autostart with Windows but I have noticed that it seems to start last after every other autostart program. As it relates to your question, I just closed chrome and restarted it and Chrome opened behind the Cairo menu bar. 

I have been using Cairo for a few weeks now, and definitely the Cairo menu bar is always overlaid on top of the application title bar of all program windows. All windows open behind the Cairo Menu bar. The only way to avoid this is to not Maximize the window but whenever the window is maximized, it is behind the Cairo menu bar as my previous screenshot showed.

Unless I have a Cairo setting wrong that is causing this behavior?

See my Cairo Menu bar settings below:

![Cairo menu bar setting](https://user-images.githubusercontent.com/65672381/82579523-eedcd300-9b5b-11ea-87ca-d47267591040.PNG)

**Comment by dremin** [comment]
I think you may be running Cairo without it configured as shell. On the advanced tab, is there an option to set Cairo as shell?

**Comment by danielks11** [comment]
> I think you may be running Cairo without it configured as shell. On the advanced tab, is there an option to set Cairo as shell?

Yes there is but with that option from the first time I used it, it had the desktop changing with file names as I traversed the menu. So I had set it back to Windows Explorer so as to use Windows Explorer to search for files.

**Comment by dremin** [comment]
I did not realize you could use Windows Explorer on Hyper-V server! I will need to investigate if this version of Explorer is missing the features that prevent overlap. 


> it had the desktop changing with file names as I traversed the menu.

Do you mean the dynamic desktop feature of Cairo? You can disable this in the desktop tab of settings.

**Comment by danielks11** [comment]
Ok. So I just set Cairo as the Shell. I had to sign out and sign back in.

So far, the menu bar issue over the application title seems to be resolved. So thank you for that.

However, it created another issue, before I could fullscreen and have the window fill my entire monitor but not it is a smaller size. See the screenshot because I do not think I am explaining properly. Ok. Scratch that. I just went to get the screenshot and it full-screened properly. 

I turned off the dynamic desktop and Windows Explorer is opening as it should even though Cairo is set as the Shell. So I will test this out and make sure it is fully working as I wanted.

Thank you very much

> I did not realize you could use Windows Explorer on Hyper-V server! I will need to investigate if this version of Explorer is missing the features that prevent overlap (when set as shell, Cairo uses its own implementation).

Ok. Sorry, I should have explained my set up. So I am on my Windows 10 desktop. I created a Hyper-V machine and installed Hyper-V Server 2019. I needed a version of Windows where I did not need a separate license. I am using Hyper-V Server 2019 as a desktop and not a hypervisor hence why I am using Cairo Desktop Environment. Yes, initially Windows Explorer did not work in Hyper-V server. However, from version 2019, Microsoft released [Server Core App Compatibility Feature on Demand](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19) that allows more Windows component to work in Hyper-V Server. So when I had discovered this, I reinstalled the Hyper-V Server 2019 VM and installed the Server Core App Compatibility Feature on Demand (SCACFoD) and sure enough, Windows Explorer works. Still a lot of other stuff still doesn't work but I can now run certain applications that were giving me an error before or were not working properly.

For example, before when I first installed Cairo, the drag and drop feature to configure the App grabber would not work. After SCACFoD, drag and drop now works. Before when I installed Daum Potplayer, I got an error when trying to play a video. Now videos play after SCACFoD. 

So the only issue was the Cairo menu bar was overlaid on the application title, so that is definitely an issue that needs to be resolved for anyone who wants to use the Windows Explorer as the Shell in Hyper-V Server 2019 with SCACFoD.

**Comment by dremin** [comment]
After installing the FOD, I am able to start explorer as a file browser, but when starting it as the shell, I am only getting a command prompt upon login. What steps did you perform to start explorer as the shell?

**Comment by danielks11** [comment]
Oh wow. Now I am sorry I did not make notes.

What I remember doing was with a fresh install of Hyper-V Server 2019, I ran the PowerShell commands from the website I sent you.

I downloaded the FOD first, then ran the install command from the FOD iso. Then restarted. I also did the optional add Internet Explorer 11 to server core, then restarted again. After it restarted Windows Explorer was working.

Wait, I just reread your post. When you say file browser, do you mean the normal Windows Explorer window? If so then yes that is how mine is as well. Other than that you have to start everything from command prompt or PowerShell because Hyper-V Server is a restricted version of Server Core. I installed [Core-fig for Server 2012 core](https://archive.codeplex.com/?p=coreconfig) and Cairo Desktop to add a Gui.

When I installed Cairo, I just opted not to use Cairo as the Shell. Windows Explorer as the Shell in Cairo settings was selected by default.

Sorry, I am working from home and juggling a lot of IT support requests and trying to respond to you, so I apologize if I did not answer your question properly. Let me know if I need to be clearer.

**Comment by dremin** [comment]
Thanks for the details! I think we are both seeing the same behavior--Explorer is not displaying a desktop and taskbar, only the file browser window. In this setup, Explorer is not actually providing any other shell features, so Cairo needs to be configured as shell in this scenario in order to have features such as reserving space for maximized windows and desktop wallpaper.

Ideally, I should make an adjustment so that Cairo automatically runs in shell mode if we see there is nothing else providing these features. I will take that away as an improvement so that things are a bit less confusing.

> I turned off the dynamic desktop and Windows Explorer is opening as it should even though Cairo is set as the Shell. So I will test this out and make sure it is fully working as I wanted.

Is this working as desired now with Cairo set as shell?

**Comment by danielks11** [comment]
Ok. So if I am understanding you, if I was using Cairo in say Windows 10 or even Windows Server, I would not have had the issue but because I am using it in Hyper-V that does not have a GUI, explains why the issue occurred?

I am working on some stuff for work at the moment so I am not able to test extensively. However, from what I have seen so far applications are now opening below the Menu bar, which is fine. I will look out for if there are any specific programs that differ.

Instead of making Cairo the default shell, what about programming it to detect whether there is a shell present during installation and if there is one, ask the user if they want to make Cairo the default and the pros and cons of both option and if there is none, then inform the user that no shell was found and as such Cairo will be set as the default shell. 

As a first time user, I did not understand the importance of this setting so it would have been good to have been asked this question when I was installing with either a simulation of the two options or screenshots or explanation or some combination thereof. If I had been aware of this setting and its implications, I would have been spared the last few weeks of frustration. Lol. Such is life.

**Comment by dremin** [comment]
> Ok. So if I am understanding you, if I was using Cairo in say Windows 10 or even Windows Server, I would not have had the issue but because I am using it in Hyper-V that does not have a GUI, explains why the issue occurred?

Correct! We actually recommend leaving Explorer as the shell when running on an OS version that has a GUI, since Explorer provides some crucial features such as UWP app activation.

> Instead of making Cairo the default shell, what about programming it to detect whether there is a shell present during installation and if there is one, ask the user if they want to make Cairo the default and the pros and cons of both option and if there is none, then inform the user that no shell was found and as such Cairo will be set as the default shell.

That's a good idea too! I will investigate this, I can see a few ways we could implement this that would be beneficial.

Apologies this was so confusing in this scenario. For the majority of use cases, this isn't an issue, but we definitely want to make Cairo also be a great shell for the server core flavors of Windows as well, so your feedback has been extremely useful and will help us make improvements in this area!

**Comment by danielks11** [comment]
Thank you for your assistance.

> so your feedback has been extremely useful and will help us make improvements in this area!

No problem. I look forward to future updates.

**Comment by dremin** [comment]
In the latest release, Cairo will always start in shell mode regardless of setting if no other shell is running (unless disabled via command line argument).
