### ISSUE TITLE
Bug with modern apps maximized

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#39]
Sometimes the modern apps are not correctly sized when maximized.
Happens with Windows store, [Windows settings](https://user-images.githubusercontent.com/32496803/31511094-e817d2ae-af86-11e7-8527-9932c35baf32.png) and [facebook messenger app](https://user-images.githubusercontent.com/32496803/31511091-e73d6db2-af86-11e7-8560-1a9dba7fc225.png).
See the small overlapp with menu bar.
The reverse scenario already happened, windows on top of menu bar.

**Comment by dremin** [comment]
Unfortunately, this is a Microsoft bug 😞 The UWP windows are not maximizing with respect to the system workspace area.

**Comment by dremin** [comment]
For further insight, the UWP window borders are drawn by the shell (Explorer). When a UWP window is maximized, without Cairo, you can see it goes a bit off the top of the screen and then jumps to the correct size instantly as Explorer has rights to resize the window.

**Comment by mdmk** [comment]
Is it not possible to correct the size in the same way than explorer?
Thanks for the explanation anyway.
So sad modern apps are marred with such flaws.

**Comment by dremin** [comment]
Unfortunately Cairo doesn't have rights to resize other windows. When Cairo reserves the edge of the screen, Windows emits an event to other applications to resize but it is up to the application to use the correct size.
