### ISSUE TITLE
Can not access Windows Settings in any way

### ISSUE THREAD

**Issue by firkenator** [cairoshell/cairoshell#393]
**Describe the bug**
Windows Settings not available when Cairo is set as main shell.

**Steps to reproduce**
1. Set Cairo as main shell.
2. Log off and log in.
3. Click on the Cairo icon (Windows Settings not there)

**Expected behavior**
Windows Settings should be available

**System information:**
 - Windows version: Windows 10 Pro 1903
 - Cairo version: Cairo Desktop M3.7023
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**
Windows Settings are available when windows explorer is the main shell.

**Screenshots**
-Windows Explorer is set as main shell
![windowsexplorer_main](https://user-images.githubusercontent.com/66781401/84385110-4e744e80-abef-11ea-8609-5b1e05fff4c7.jpg)

-Cairo Desktop is set as main shell.
![cairoshell_main](https://user-images.githubusercontent.com/66781401/84385182-6a77f000-abef-11ea-91dd-f6afad221f2a.jpg)

**Comment by josuave** [comment]
Windows settings is a UWP app, Microsoft has not provided a method to execute UWP apps when Explorers is not shell. The only way that you can access Windows Settings, and any other UWP app, is to set explorer as shell and run Cairo on top of it.

**Comment by dremin** [comment]
Thanks for the report! This is occurring due to #365, so closing as a duplicate.
