### ISSUE TITLE
Minimized windows disappear instead of appearing on the taskbar 

### ISSUE THREAD

**Issue by Blackrucat** [cairoshell/cairoshell#396]
**A clear and concise description of what the bug is.**
I have a problem when I minimize the Counter-Strike 1.6 window, it doesn't appear on the taskbar anymore, even with the process running in the background. 

**Steps to reproduce**
1.  Open CS 1.6
2.  Minimize the CS 1.6 window
3.  Try to maximize the window again

**Expected behavior**
The game appearing in the taskbar

**System information:**
 - Windows version:  Windows 10
 - Cairo version: https://github.com/cairoshell/cairoshell/releases/tag/v0.3.7023
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  yes

**Video**
So I did this video just to show you guys.
https://youtu.be/U34aqgXyvi0

**Comment by dremin** [comment]
Sorry, didn't mean for this to get closed by that commit..

**Comment by dremin** [comment]
@Blackrucat Could you please try [this build](https://ci.appveyor.com/api/buildjobs/24v85ytb1sdv2ji8/artifacts/Installer%2FCairoSetup_64bit.exe) and report back if this issue is resolved?

**Comment by dremin** [comment]
Improvements that should fix this are in the latest release.
