### ISSUE TITLE
Taskbar buttons do not update when switching Virtual Desktops

### ISSUE THREAD

**Issue by munael** [cairoshell/cairoshell#398]
**Describe the bug**
With multiple virtual desktops, switching does not update the programs on the taskbar.

**Steps to reproduce**
1. Have multiple virtual desktops
2. Open several apps in different desktops
3. Start Cairo
4. Switch desktops and look for the corresponding apps on the taskbar

**Expected behavior**
Only apps on the active virtual desktops show on the taskbar.

**System information:**
 - Windows version: Windows 10 1909
 - Cairo version: M3.7023
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Not replaced

**Additional context**

**Screenshots**

**Comment by AdmiralLordM** [comment]
I would add emphasis to the fact that taskbar on multi monitor setups should show only the tasks running on that individual screen (or virtual desktops - if virtual desktops are available in cairoshell) - or have the option to change between "show every app" vs "show only the apps on this screen"
