### ISSUE TITLE
Logging/Debugging

### ISSUE THREAD

**Issue by ThMage** [cairoshell/cairoshell#4]
I think it would be a help to those of us who are trying to get this running on our machines and to those of you who are in development if Cairo automatically created a log file that would be able to identify when the errors occur.
I suppose I could set up debugging in VS2008, but that's more work and most users won't know how to do that.

Actually, now I see that there is supposed to be a crash log...  I'm not getting one for some reason though.  Mine is crashing nearly on startup.  The taskbar comes up, but when I mouse over, I get the "busy" cursor.  If I try to click on it, the shell crashes.
Err, it just worked this time...

Just thought I would put that suggestion out there.  Keep up the good work guys, maybe I'll even try to contribute a bit once I have more time.

**Comment by cairoshell** [comment]
Cairo now displays error information, and it can be found in Event Viewer as well. Many fixes have been implemented to stabilize Cairo; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
