### ISSUE TITLE
Window explorer overlapping cairo shell

### ISSUE THREAD

**Issue by jakkaas** [cairoshell/cairoshell#401]
Explorer/Edge chromium over laping cairo shell after window 2004 update

![image](https://user-images.githubusercontent.com/43289832/85573250-59010000-b653-11ea-9046-def47e98d2cc.png)

**System information:**
 - Windows version: Build 19041
 - Cairo version: 0.3.7023.0
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**

**Comment by josuave** [comment]
Does the issue persist after reboot?

**Comment by jakkaas** [comment]
Happens mostly with Edge Chromium.

I have to exit cairo and restart to get the issue solve

**Comment by dremin** [comment]
When in this state, did other windows overlap Cairo when dragging them over it?

**Comment by jakkaas** [comment]
No while clicking the window, it gets overlaped

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 24, 2020 at 8:58 PM, Sam Johnson<notifications@github.com> wrote:   


When in this state, did other windows overlap Cairo when dragging them over it?

**Comment by dremin** [comment]
This should be resolved in the latest release.
