### ISSUE TITLE
Feature Request - Blurred Taskbar

### ISSUE THREAD

**Issue by grinreaperxdesign** [cairoshell/cairoshell#404]
Would it be possible to add an option for blur under taskbar like there is for the menu bar? I find I get too visually distracted with full transparency when I'm doing art on my surface, but still like to have the taskbar visible for a more tablet like use.

**Comment by dremin** [comment]
If you are using the full-width taskbar setting, I think we can make this happen just like the menu bar! (If you're using the default setting where the taskbar does not take the full width of the screen, we will need to investigate some alternate methods which don't impact performance.)

**Comment by grinreaperxdesign** [comment]
Thank you so much! I love that you guys are giving people options, windows explorer is so dated.

**Comment by Blackrucat** [comment]
Just make it an option, and give some advice about how it can impact the performance, then if someone uses it they will know what is better for them.

**Comment by dremin** [comment]
In the latest release, when enabling "blur behind the menu bar", the taskbar now also gets blur if it is in full-width mode (either via the setting or via lots of windows)
