### ISSUE TITLE
[UX] Program categorization on first start is horrible

### ISSUE THREAD

**Issue by grantlmul** [cairoshell/cairoshell#405]
**Is your feature request related to a problem? Please describe.**
When launching Cairo for the first time, the "Categories" page requires clicking and dragging with slow scrolling

**Describe the solution you'd like**
multiple selections of programs at least
* Multi-panel: have a second panel for uncategorized items
* Upgrade: allow usage of the scroll wheel

**Describe alternatives you've considered**
maybe a python script to edit some file i find? not worth it

**Additional context**
![CairoDesktop_E8oPFJVIYh](https://user-images.githubusercontent.com/39559405/89721773-af31c480-d9af-11ea-8714-39f33250fe67.png)

**Comment by dremin** [comment]
If you click the "Hide" button at the top, the categorized apps will be hidden so that you can organize uncategorized apps without requiring excessive scrolling. This button is not well-named nor is it obvious, so if you have any suggestions to make this clearer we are all ears!

**Comment by TheMeq** [comment]
Collapse / Expand?

**Comment by dremin** [comment]
Forgot to close this earlier; it's fixed in the latest release.
