### ISSUE TITLE
Inconsistent and missing functionality on Cairo's systray icons

### ISSUE THREAD

**Issue by Someone65** [cairoshell/cairoshell#406]
**Describe the bug**
Mousing over and clicking systray icons lacks functionality compared to default explorer. In the standard Win 7 taskbar for example, if you use [Process Hacker](https://processhacker.sourceforge.io/)'s tray icons you can double click the tray icon to open up the Process Hacker window and mousing over it brings up a mini-interface related to the corresponding tray icon. Neither of these work with Cairo. On the other hand, other systray using programs work more or less fine like Volume2 or ESET Security Suite.

**Steps to reproduce**
1. Install Process Hacker and open its View menu, Tray Icons, then select any of the items to be displayed in systray.
2. Mouse over and click tray icon in Cairo and Windows taskbar to compare functionality. 

**Expected behavior**
Mousing over should display a miniature window as seen in the screenshot below and clicking the icon once should open the Process Hacker window. Neither of these happen in Cairo.

**System information:**
 - Windows version: Windows 7
 - Cairo version: 
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Screenshots**
![Windows explorer default](https://i.vgy.me/M16BA1.png)
![Cairo](https://i.vgy.me/3OphXf.png)

**Comment by Someone65** [comment]
Just found that this partially overlaps with [this report](https://github.com/cairoshell/cairoshell/issues/351) except for the mousing over aspect of it.

**Comment by dremin** [comment]
I'm not able to reproduce this problem (see below). Are you still seeing this behavior?

![Screen Shot 2020-08-14 at 8 57 42 PM](https://user-images.githubusercontent.com/7373633/90303144-36c87900-de71-11ea-9111-cbb54eeb9fe0.png)

**Comment by Someone65** [comment]
Yeah, it's still happening. I'm also experiencing issues where if I right click Steam's systray icon, it immediately goes out of focus, thus closing the context menu before I can even see it. Doesn't happen to other systray icons as it stays on focus on the menu bar when I right click those. There were a few times very early on where I could successfully get the context menu to properly show up and it was inconsistent.

**Comment by josuave** [comment]
What version of ProcessHacker? What version of Steam

**Comment by Blackrucat** [comment]
![image](https://user-images.githubusercontent.com/56588184/91587391-172f5700-e92d-11ea-917f-0b3f71499096.png)
It only happens to you, try to use the "process hacker kernel mode" or reinstall the program

**Comment by dremin** [comment]
@Someone65 I've made some tray compatibility improvements, could you please try [this build](https://ci.appveyor.com/api/buildjobs/qvf6hsyana6apufc/artifacts/Installer%2FCairoSetup_64bit.exe) and let us know if things are improved?

**Comment by dremin** [comment]
Closing due to lack of response.

**Comment by Someone65** [comment]
Sorry, had my pc in almost 2 months. Will get it back up again soon and do some thorough testing when I do.

**Comment by Someone65** [comment]
Sorry for the extremely late response. I've gotten my PC back and testing the latest version of Cairo, Steam, and ProcessHacker2 as of the date of posting, the issue with Steam in particular is now resolved. 

The issue with ProcessHacker is unchanged, though.
