### ISSUE TITLE
Wallpaper doesn't show up when i turn off Desktop 

### ISSUE THREAD

**Issue by Blackrucat** [cairoshell/cairoshell#408]
I already tried in many ways to set the wallpaper of Cairo Shell and it doesn't appear

**System information:**
 - Windows version: w10 pro
 - Cairo version: Cairo Desktop M3.7028
 - 32-bit or 64-bit:  64
 - In Cairo Settings > Advanced, is Cairo set as shell?:  yes, always 👍 

**Additional context**
I want to see my wallpaper, but I don't want to see desktop icons, so then I set up off desktop, but without desktop on it doesn't appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/56588184/90966799-6dc00f80-e4ad-11ea-960d-6e5835d1833a.png)
![image](https://user-images.githubusercontent.com/56588184/90966896-7d8c2380-e4ae-11ea-8b51-c1a1f1bf4094.png)

**Comment by dremin** [comment]
This is fixed in the latest release.
