### ISSUE TITLE
Network, Battery, and Search Issue

### ISSUE THREAD

**Issue by Lord-Shadjo** [cairoshell/cairoshell#425]
**Issue**

These menus won't work at all if Cario Shell is set as default shell. I've included screenshots bellow.

**Set-Up**

OS: Windows 10 Home

Cairo Version: v0.3.7028

Cairo Shell Set As Default: No

**Screenshots**

![battery](https://user-images.githubusercontent.com/70665684/93386763-6e866000-f825-11ea-981f-a7f105d092aa.png)

![network](https://user-images.githubusercontent.com/70665684/93386969-bad1a000-f825-11ea-90c6-fa7a32d722f2.png)

![search](https://user-images.githubusercontent.com/70665684/93387127-f9675a80-f825-11ea-9ff5-b833ea01fe24.png)

**Comment by dremin** [comment]
The network/battery issue is related to #365, but search should definitely work. What issue do you see with search?

**Comment by dremin** [comment]
Closing due to lack of response as duplicate of #365
