### ISSUE TITLE
Cairo shell audio control issues

### ISSUE THREAD

**Issue by OutragedMetro** [cairoshell/cairoshell#426]
When I enable Cairo shell it does not allow me to controll my volume from your widget on the top bar are you working on a bug fix for this or is anything possible?

**Comment by Blackrucat** [comment]
I already did an Issue about this, i think they're already working on this feature.

**Comment by dremin** [comment]
@OutragedMetro in Cairo Settings > Advanced, is Cairo configured as shell or Windows Explorer? In the next update we are hoping to use the native volume controls when Cairo is running alongside Explorer as shell.

**Comment by dremin** [comment]
Closing due to lack of response.
