### ISSUE TITLE
shortcut bug in throwhelper.cs

### ISSUE THREAD

**Issue by austinHeisleyCook** [cairoshell/cairoshell#427]
when a duplica itme is tp shjrot the shell crashed evne commentin lin 7 near throwexe doed not helop.. i tried added console log but this does not hell

- [ ] click cario setitng thry
-[] the pother problam is a canon printer refer broek and is system.generic.collections 
i am trying to write a fix myself  since it i knw nad reoute the expet

**Comment by austinHeisleyCook** [comment]
| Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"An item with the same key has already been added."} | System.ArgumentException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147024809 | int
  | HelpLink | null | string
  | IPForWatsonBuckets | 0x0000000000000000 | System.UIntPtr
  | ▶ InnerException | null | System.Exception
  | IsTransient | false | bool
  | Message | "An item with the same key has already been added." | string
  | ParamName | null | string
  | RemoteStackTrace | null | string
  | Source | "mscorlib" | string
  | StackTrace | "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) in f:\\dd\\ndp\\clr\\src\\BCL\\system\\throwhelper.cs:line 72\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) in f:\\dd\\ndp\\clr\\src\\BCL\\system\\collections\\generic\\dictionary.cs:line 393\r\n   at CairoDesktop.Common.HotKey.Register()\r\n   at CairoDesktop.Common.HotKeyManager.RegisterHotKey(IList`1 keys, Action`1 action)\r\n   at CairoDesktop.Desktop.SetupPostInit()\r\n   at System.Windows.Window.OnSourceInitialized(EventArgs e)\r\n   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)\r\n   at System.Windows.Window.ShowHelper(Object booleanBox)\r\n   at CairoDesktop.Startup.Main(String[] args)" | string
  | ▶ TargetSite | {Void ThrowArgumentException(System.ExceptionResource)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | ▶ WatsonBuckets | {byte[5616]} | object {byte[]}
  | _HResult | -2147024809 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | _exceptionMethod | null | System.Reflection.MethodBase
  | _exceptionMethodString | null | string
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | _ipForWatsonBuckets | 0x0000000000000000 | System.UIntPtr
  | _message | "An item with the same key has already been added." | string
  | _remoteStackIndex | 0 | int
  | _remoteStackTraceString | null | string
  | ▶ _safeSerializationManager | {System.Runtime.Serialization.SafeSerializationManager} | System.Runtime.Serialization.SafeSerializationManager
  | _source | "mscorlib" | string
  | ▶ _stackTrace | {sbyte[384]} | object {sbyte[]}
  | _stackTraceString | null | string
  | ▶ _watsonBuckets | {byte[5616]} | object {byte[]}
  | _xcode | -532462766 | int
  | _xptrs | 0x0000000000000000 | System.IntPtr
  | m_paramName | null | string
  | ▶ Static members |   |  


degud code

**Comment by austinHeisleyCook** [comment]
@Revoluzifer  @oxysoft

**Comment by austinHeisleyCook** [comment]
i amworking on a soluon a d testing is there way i can add a fix if i amke one. this is an awesom proejkct

**Comment by dremin** [comment]
Thanks for the debug output! Is this using the latest 0.3.7086 version? The stack trace looks like it is from the previous version.

**Comment by austinHeisleyCook** [comment]
yes it is  i tried to comment out the code line 7 seems to caused alot of issues on my tests

**Comment by austinHeisleyCook** [comment]
also the detail of interest is canon printer and this happned with a  connan  printer then a unhandled exception...

**Comment by austinHeisleyCook** [comment]
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) in f:\dd\ndp\clr\src\BCL\system\throwhelper.cs:line 72
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) in f:\dd\ndp\clr\src\BCL\system\collections\generic\dictionary.cs:line 393
   at CairoDesktop.Common.HotKey.Register()
   at CairoDesktop.Common.HotKeyManager.RegisterHotKey(IList`1 keys, Action`1 action)
   at CairoDesktop.Desktop.SetupPostInit()
   at System.Windows.Window.OnSourceInitialized(EventArgs e)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at CairoDesktop.Startup.Main(String[] args)
^^

**Comment by austinHeisleyCook** [comment]
how is the item algoritm handing the same itmes this causes alot of it

**Comment by dremin** [comment]
This still looks like old code. Please try again using the latest version published the other day.

**Comment by austinHeisleyCook** [comment]
thank you will do...

**Comment by austinHeisleyCook** [comment]
@dremin  I will try to add m fy csuto f ile manager to the project
