### ISSUE TITLE
Dual Monitor Taskbar - Autohide placement miscalculation

### ISSUE THREAD

**Issue by BlamJams** [cairoshell/cairoshell#429]
**Describe the bug**
Now (latest update), the taskbar on my secondary monitor shifts out to the far right of the screen when Autohide is enabled.
When the setting is changed to Reserve Space, it shows at the very far right of the screen.
Restarting Cairo after this, the taskbar appears centered on the secondary screen as it should.

**Steps to reproduce**
1. Set Taskbar to Autohide
2. Restart Cairo
3. *Taskbar is way out to the right of secondary screen*
4. Set back to Reserve Space - taskbar appears on far left.
5. Restart - Taskbar is back to the center and visible.

**Expected behavior**
Taskbar should appear on the secondary monitor, centered and autohiding.
<img width="3200" alt="Screenshot 2020-09-21 18 47 51" src="https://user-images.githubusercontent.com/71634312/93748123-11324a80-fc3b-11ea-8e64-dd04e8b4cea7.png">

**System information:**
 - Windows version: Win 10
 - Cairo version: 0.3.7086.0
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?: 

**Additional context**
Primary monitor on left is 4k res
Secondary monitor on right is 2560x1440

**Screenshots**

**Comment by dremin** [comment]
Thanks! A couple questions:

- Is this a new regression that did not occur with 0.3.7028?
- Is your Windows 10 version 2004?

**Comment by BlamJams** [comment]
This is a new problem that was not happening prior. This only happened after the update that came through in the last 24 hours.
I've only been running Cairo since Friday, and am unfamiliar with it's update schedule.
So for the 3 days prior to yesterday, it was operating as it should be.

I was on Win 10 1903, now 1909 (same prob) and in the process of updating to 2004.

**Comment by dremin** [comment]
@BlamJams I was able to reproduce this and make a fix. If you'd like to try the fix early, you can [install this build](https://ci.appveyor.com/api/buildjobs/ccof1t96kgplaog5/artifacts/Installer%2FCairoSetup_64bit.exe).

**Comment by dremin** [comment]
This is resolved in the latest release.
