### ISSUE TITLE
Feature Request: Moving and rotating bars/Change edges of screen

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#43]
It would be good to be able to move the bars freely on the screen and rotate them by 90/180 degrees.
Or at least chose the edge of the screen.
For menu bar and taskbar essentially (desktop bar already draggable).

**Comment by dremin** [comment]
I do plan to support taskbar on top as part of M3. I also think menu bar on bottom could be an interesting thing to add as well.
However, the existing interface wouldn't work very well in a vertical layout. If someone is willing to spend the time to create a usable and sustainable implementation of it, I would gladly accept the pull request 😄

**Comment by dremin** [comment]
Taskbar-on-top is available in the latest Milestone 3 release. Please check for updates and re-open the issue if it is not resolved.

**Comment by mdmk** [comment]
Menu bar on bottom has not been implemented yet.
I think I cannot reopen this by myself, isn't it ?

**Comment by dremin** [comment]
I do not plan on implementing menu bar on bottom at this time.
