### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by austinHeisleyCook** [cairoshell/cairoshell#430]
https://github.com/austinHeisleyCook/fileuiReplacementfor10
i would like to propose adding my ui file manger for windows to for cairoshell to overhaul to current one from windows. I love this project so i want to contribute in any way I can.
also i would like to help manage to shell project @dremin

**Comment by josuave** [comment]
We always enjoy help from the community!
The best way to contribute, is to Fork the project, make your changes, then put in a Pull Request.
For your current proposition, I would suggest describing what your projects solves and how this is lacking in CairoShell.

I will close this issue for now and if your response merits more discussion we can reopen it and discuss further.
