### ISSUE TITLE
Taskbar blur doesn't auto hide when bar grows to full with

### ISSUE THREAD

**Issue by Plloi** [cairoshell/cairoshell#431]
**Describe the bug**
Once the taskbar reaches full width and auto hide is enabled,  the blur stays visible once the bar hides.
This is true if the bar size is dynamic or set to screen width

**Steps to reproduce**
1. Enable blur behind the menu bar
2. Set taskbar to auto hide
3. Either
3a. Set taskbar to full width
3b. Open a bunch of stuff
4. Enjoy the blur where the task bar slides away from

**Expected behavior**
Blur should hide with taskbar
**System information:**
 - Windows version: 2004 OS Build (19041.508)
 - Cairo version: 0.3.7086.0 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Screenshots**
![image](https://user-images.githubusercontent.com/2743514/93931730-2bc4fc00-fced-11ea-9dae-390704a6acda.png)

**Comment by dremin** [comment]
Oops. Thanks for the report, we'll get this fixed.

**Comment by dremin** [comment]
@Plloi This will be resolved in the next release; if you'd like you can install [this build](https://ci.appveyor.com/api/buildjobs/dkqih8p9k2yioc6s/artifacts/Installer%2FCairoSetup_64bit.exe) to get the fix early.

**Comment by dremin** [comment]
This is resolved in the latest release.
