### ISSUE TITLE
Main calculator is not accessible to users on windows due class not found or addec

### ISSUE THREAD

**Issue by austinHeisleyCook** [cairoshell/cairoshell#436]
**Describe the bug**
Cairo does not work well with windows main calculator 

**Steps to reproduce**
1. Go to calculator on windows 
2. Click start
3.  And a error message saying class not found

**Expected behavior**
The calculator should open normally like windows does 
**System information:**
 - Windows version: 
 - Cairo version: 
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?: 

**Additional context**
Classes not adds or found on the exception messagebox that is thrown to user appdata:it seeming from maybe dire t the resources to the correct spot the calculate is found this happened on both machines I found on Cairodeskto the version cureeny
And It is 64 bit windows 10pro
My laptop is 32bit windows home. 

**Screenshots**
Wil definitely I Ned screenshot the error this is what attempting to fix with my other calculator that got deiniex in pr

**Comment by austinHeisleyCook** [comment]
I found this by testing two different spruced machine and got the same results so it is definitely not one use problem or machine issue it have Cairo handle native windows applications like the calculator or other windows native applications that come with windows I don't if this a big fix but it make it more diserable users if done

**Comment by austinHeisleyCook** [comment]
@dremin @cairoshell

**Comment by austinHeisleyCook** [comment]
![16010664149306495279660814084775](https://user-images.githubusercontent.com/16505118/94314051-a9c71400-ff34-11ea-9e92-0956d017c62a.jpg)
This happened with both machines and refers to way appp Reference thee a fix

**Comment by austinHeisleyCook** [comment]
Shell:app reference seem cause the problem for not just calculator but most ui so this is major ui function problem that stops usage of command apps already in windowa

**Comment by josuave** [comment]
This is due to Microsoft changing much of their UI to UWP/WinRT apps or components. Unfortunately, unless Microsoft makes it so that UWP/WinRT can run without Explorer running as shell, we wo not have any immediate fixes or workarounds. The current recommendation is to use apps that do not utilize UWP/WinRT.

**Comment by austinHeisleyCook** [comment]
that means windows native calculator will not work or any windows app installed on a fresh windows instillation @josuave
