### ISSUE TITLE
Improve icon label readability

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#44]
In order to improve readability of desktop icon, there could be a backdrop behind them.

**Comment by dremin** [comment]
I've darkened the outline around the text. It should be more readable in the next build.

**Comment by dremin** [comment]
I have just released a new build, could you please check if the icons are now legible for you? Thanks!

**Comment by mdmk** [comment]
@dremin That seems good to me, thanks.
The issue can stay closed.
