### ISSUE TITLE
The ability for you to be able to change the font of the UI

### ISSUE THREAD

**Issue by AlexDev404** [cairoshell/cairoshell#450]
**Is your feature request related to a problem? Please describe.**

The font you currently set always hurt my eyes, and it sometimes is hard to read.

**Describe the solution you'd like**

I would really like the ability for you to be able to change the font of the UI to whichever you choose and you to be able to allow anti-aliasing/font smoothing (TrueType or ClearType)

**Describe alternatives you've considered**

I would suggest that in settings you put an `"Appearance"` tab within Cairo where the user can tweak the font to something like Roboto among other things within Cairo just similarly like they have within a generic Linux interface like GNOME or KDE.

**Additional context**

No additional context available at this time.

**Comment by dremin** [comment]
Could you please post a screenshot of how your fonts look? Cairo uses the default Windows font, so the behavior you're describing is unexpected.

You can change fonts using a theme, but we could probably make this a bit easier.

**Comment by AlexDev404** [comment]
![Image 2](https://user-images.githubusercontent.com/34188635/95641427-7e2d4900-0a5f-11eb-8874-1152211368a5.png)

**Comment by AlexDev404** [comment]
The rendering is inconsistent

**Comment by AlexDev404** [comment]
@dremin Hi it has been almost a month now. I would like to ask if this issue is still relevant or not?

**Comment by dremin** [comment]
@AlexDev404 I'm adding better support for changing fonts in themes, so you can more easily change them. Once this is finalized I'll post an example flat theme with font changes so that you can customize to best fit your needs.

**Comment by AlexDev404** [comment]
@dremin Is there something like a wiki I can use to refer to if I would like to make something like my own themes? I have already seen your wiki, but in my opinion is doesn't do a good job at explaining the tags you use other than basically saying "Go figure it out yourself!". Is there another alternative (for example a step-by-step or your usual manual/documentation) that better explains this?

**Comment by dremin** [comment]
@AlexDev404 Sorry, our documentation for this really is pretty bad. I'll work on improving that as part of this ticket as well.

**Comment by dremin** [comment]
I've updated the theming documentation to be less bad. Included is an example of how to create a theme that changes the font family and size (as well as a few colors). I hope this helps!

**Comment by AlexDev404** [comment]
Nice! I love it! :) Thanks so much!

**Comment by dremin** [comment]
Yay! No problem, thanks for the report!
