### ISSUE TITLE
Newest update fails

### ISSUE THREAD

**Issue by dbarronoss** [cairoshell/cairoshell#453]
When launching it for installation, it closes out Cairo, and does nothing else (tried three times, including reboots).

**Comment by TheMeq** [comment]
This happens because the executable is not trusted by windows. If you download the installer from github and run it from your downloads folder, you should be able to update.

**Comment by dbarronoss** [comment]
Yes, I had already done that.  However, I've applied the last three updates prior to this one automatically via the check for updates, etc.
Why should the behavior have changed? (recent Windows update perhaps?).
Please feel free to close the ticket, I just left it open (this time) so you could reply if you would.

**Comment by dremin** [comment]
I actually ran into this on one of my machines as well. We’ll try to get this fixed!

**Comment by dremin** [comment]
This should be fixed in the latest release, 0.3.7147. If you continue to have issues updating please reopen. Thanks!
