### ISSUE TITLE
Icons not displaying correctly in taskbar, show up as white pages.

### ISSUE THREAD

**Issue by TheMeq** [cairoshell/cairoshell#454]
**Describe the bug**
Icons that used to appear as normal icons have changed into white page icons, this happened a couple of versions ago but recent updates have not fixed it. Have tried removing the icons from the quick launcher and putting them back on but the issue still occurs. This also happens in the Programs menu and in the App Grabber. 

**Expected behavior**
Icons to appear correctly.

**System information:**
 - Windows version: Windows 10 Pro 64bit
 - Cairo version: 0.3.7108.0 - Pre-release
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Windows Explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/7303969/95663411-fca8ea00-0b36-11eb-9983-25f2e16502d4.png)

![image](https://user-images.githubusercontent.com/7303969/95663437-2d891f00-0b37-11eb-9e50-1cc50ca9ced4.png)

**Comment by dremin** [comment]
Interesting, do you know which was the last version these worked correctly in?

**Comment by TheMeq** [comment]
I think about 2 versions ago, but they didn't disappear after or during an update, They where there one day, and gone the next, I thought an update would fix it.

**Comment by dremin** [comment]
Do you know if there were any other changes to your system around the time they stopped working correctly?

**Comment by TheMeq** [comment]
Potentially, I couldn't tell you what though.

**Comment by dremin** [comment]
Hmm, could you try [resetting the shell icon cache](https://www.howtogeek.com/232779/how-to-rebuild-a-broken-icon-cache-in-windows-10/)?

**Comment by TheMeq** [comment]
OK, it didn't work initially, but what I did was exit Cairo shell, right click the shortcuts in the start menu and click on properties, I then clicked on change icon and selected the icons already highlighted and applied. I did that for each of the issue icons and then started Cairo shell back up, all icons have returned now. Thanks for the fix!
