### ISSUE TITLE
File Explorer not refreshing

### ISSUE THREAD

**Issue by ezybrzy** [cairoshell/cairoshell#456]
**Describe the bug**
When making changes within FileExplorer, moving, creating, etc., the screen does not automatically update. Having to manually refresh screen to see changes

**System information:**
 - Windows version:  Windows 10 and Server 2019
 - Cairo version: 0.3.7108.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes *Desktop is disabled

**Comment by dremin** [comment]
Thanks for the report! This is the same issue as #434 so I will be closing as duplicate.
