### ISSUE TITLE
Cairo settings crashed when access to the auto"run" registry key is denied

### ISSUE THREAD

**Issue by C0pperKiDD** [cairoshell/cairoshell#457]
If Cairo is installed and runs with configured autostart, the Cairo Setting are not accessible if Windows or some Security Software deny the access to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

```
Message: Der Zugriff auf den Registrierungsschlussel
"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentV
ersion\Run" wurde verweigert
Target Site: Void Win32Error(int32, System.String)
Version: 0.3.7108.0

bei Microsoft.Win32.RegistryKey.Win32Error(Int32
errorCode, String str)

bei Microsoft.Win32,RegistryKey.CreateSubKeyinternal(String
subkey, RegistryKeyPermissianCheck permissionCheck, Object
registrySecurityObj, RegistryOptions registryOptions)
bei Microsoft.Win32.RegistryKey.CreateSubkey(String
subkey)
bei CairoDesktop.CairoSettingsWindow.checkRunAtLogOn()
bei CairoDesktop.CairoSettingsWindow..ctor()
bei CairoDesktop.CairoSettingsWindow.get_Instance()
bei CairoDesktop.MenuBar.InitCairaSettingsWindaw(Object
sender, RoutedEventArgs e)
bei System.Windows.EventRoute InvokeHandlersimpl(Object
source, RoutedEventArgs args, Boolean reRaised)
....
```

**System information:**
 - Windows 10 Version 1909 (18363.1139)
 - Cairo version: 0.3.7108.0 Pre-Release 64Bit

**Comment by dremin** [comment]
Thanks, we'll get this fixed!

**Comment by dremin** [comment]
The issue should be resolved in the next release; you can try [this build](https://ci.appveyor.com/api/buildjobs/w1sdnj484dut2efg/artifacts/Installer%2FCairoSetup_64bit.exe) if you'd like to get the fix early.

**Comment by C0pperKiDD** [comment]
👌 works very well for me. thx

**Comment by dremin** [comment]
The fix is now available in the latest release.
