### ISSUE TITLE
 Feature Request: Adding button/hotkey to show desktop

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#46]
On the contrary to #45, it would be good to have a button/hotkey to simply show desktop (minimize everything).

**Comment by dremin** [comment]
WinKey+M should minimize all windows.

**Comment by mdmk** [comment]
If I remember correctly, Win+D (toggle desktop) did not work. I did not test Win + M but it should only hide, without possibility to show again Windows as they were previously.
I'll test this later and report back.

I'll try develop the idea of a button on the other side.
Imagine a hot corner like on native taskbar, it would be a plus.
It would be like an invisible button (1 pixel by one pixel).
I mean, no need to have a button on the taskbar.
You click on bottom right, then it toggles desktop.
Then the feature would be on the exact same place as native taskbar, no change of habbits.
Then we could choose the hot corner to activate in the options.
If I'm not clear I can explain further.

**Comment by mdmk** [comment]
Win + M works as intended
For Win + D I knew there was something wrong I forgot.
It does toggle every Windows, but also dynamic desktop, which is not intended.
I opened the issue #73 for this bug.

**Comment by mdmk** [comment]
As for the hot corner, [here ](https://sites.google.com/site/bytecar/home/hotcornersapp/hotcornersapprelease15) is an example of app that does just do hot corners in the way I thought of (ok it shows desktop, not toggle it but that's close).
I'd personnaly prefer to have to click in the corner and not just hover it, to prevent unwanted toggles, but that's the spirit globally.
Tell me if I can open a feature request for this or if it not your intention to do this.
After that the issue could be closed, except if you want to discuss about the possibility to add a clickable button on the dock (where ?), the initial question with the hotkey problem.
Thanks for your patience.

**Comment by dremin** [comment]
I now understand this issue versus #45. I think the best method of accomplishing this is by fixing #73 so that there is a hotkey as requested, close this and instead implement #45 as I really like the idea of a dynamic desktop 'overlay'.

**Comment by mdmk** [comment]
OK that seems good to me.

**Comment by dremin** [comment]
Closing in favor of #73 and #45
