### ISSUE TITLE
Feature Request: Change icon size in taskbar

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#47]
Icon are a bit small, it would be good to be able to change their size.

**Comment by dremin** [comment]
I have added settings for 16px (WinVista default), 24px (Win10 default), and 32px (Win7 default) taskbar icon sizes.

**Comment by mdmk** [comment]
That's great to hear. I look forward to test this once the next binary build is out.

**Comment by dremin** [comment]
This is now available in the current release.
