### ISSUE TITLE
Updater not closing Cairo before trying to update.

### ISSUE THREAD

**Issue by VexisMorlock** [cairoshell/cairoshell#480]
**Describe the bug**
I am using Cairo under explorer and running Version 0.3.7108.0 - Pre-release.  When trying to update it downloads and runs the installer but doesn't close it-self before trying to install the new version.  It does close it-self after but only after failing to update.

**Steps to reproduce**
1. Run Cairo
2. Check for updates
3. Click install update
4.Wait for download
5.Click install update
6.Follow UAC
7.Get "Cairo is running please close" promt
8.Cairo closes

**Expected behavior**
The app should be able to close it-self before Running the updater.  Maybe even as part of the installer.

**System information:**
 - Windows version: Version	10.0.17763 Build 17763
 - Cairo version: Version 0.3.7108.0 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: not replacing explorer/at start-up

**Additional context**

**Screenshots**
![image](https://user-images.githubusercontent.com/50764330/97834914-ce2db300-1c8d-11eb-96f9-c112cf2ba132.png)

**Comment by dremin** [comment]
About how long did the installer wait for Cairo to exit? Was it just a few seconds or was it a notable amount of time?

I did make some improvements in the latest release to improve this. I'd be interested to hear how updating to the next release in the future works after installing the current release.

**Comment by VexisMorlock** [comment]
It didn't wait at all.  I'll let you know what I see on the next update.

**Comment by VexisMorlock** [comment]
Worked for me today when I updated.  No issues

**Comment by dremin** [comment]
Closing per update. Thanks!
