### ISSUE TITLE
Can no longer hide the Volume icon after latest patch

### ISSUE THREAD

**Issue by SuperMewio** [cairoshell/cairoshell#484]
**Describe the bug**
In the latest update, the ability to hide the volume icon in the menu bar items section has been removed. This makes it so people like me who use EarTrumpet or some other volume mixer replacer have two volume icons. Hiding the icon via Windows settings>"Turn system icons on or off" does not hide menu bar items either so there is no way to hide the icon using conventional means.

**Steps to reproduce**
1. Install the latest Cario and or update to it.
2. Go to Cairo Settings.
3. Menu Bar.
4. Menu Bar Items.
5. Hide Volume icon now missing.

**Expected behavior**
Just be able to hide the volume icon as before using the above steps.

**System information:**
 - Windows version: Windows 10 Version 20H2 OS Build 19042.630
 - Cairo version: 0.3.7147.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
If this is intended, I did not see it on the patch notes.

**Comment by josuave** [comment]
Is the functionality still functioning when Cairo is not running?

**Comment by SuperMewio** [comment]
If you mean the windows specific setting, yes it hides the icon in the windows taskbar but does not in cairo. The specific issue though is with the volume icon in the cairo settings now missing entirely as stated above. It used to be one of four things you could hide: Action Center,  Search, and Clock are all still in the list. Volume was among them in the previous versions.

**Comment by dremin** [comment]
This change was somewhat intentional in that we follow the Windows behavior a bit more closely- rather than removing the icon, you can move it into the collapsible icons area, so it can be hidden. That said, the icon can be removed via group policy, but we do not yet respect that setting. I think the best fix for this will be for us to support the group policy setting for removing the icon.

**Comment by SuperMewio** [comment]
Interesting, unfortunately I do not use the "collapsible icons area" and have all my icons visible. There's a lot of software that reset and move to the collapsible area even though I put them into the non-collapsible area. I would find that more annoying than there being two volume icons. Thank you for your time.

**Comment by dremin** [comment]
@SuperMewio [Try installing this build](https://ci.appveyor.com/api/buildjobs/ysoci360y7v9q3xj/artifacts/Installer%2FCairoSetup_64bit.exe) which has the new group policy feature I mentioned above. After installing this, to disable the volume icon using group policy, perform the following steps:
1. Open `gpedit.msc` via Cairo menu > Run
2. Navigate to User Configuration > Administrative Templates > Start Menu and Taskbar
3. Find "Remove the volume control icon" in the list and double-click it
4. Select "Enabled", then OK
5. Now, restart Cairo. Now the volume icon should be hidden in both Cairo and Explorer.

**Comment by SuperMewio** [comment]
Hey that works, the icon is now gone. The only issue I see (that does not effect me as I have Win10PRO) is that group policy on Windows 10 is only available to people on windows 10 PRO or higher.

**Comment by dremin** [comment]
This will actually work on Windows 10 Home as well, we just check the registry setting and not the Windows edition.

**Comment by SuperMewio** [comment]
ah I understand

**Comment by dremin** [comment]
The group policy support is now available in the latest release.
