### ISSUE TITLE
No blur behind full width task bar

### ISSUE THREAD

**Issue by SuperMewio** [cairoshell/cairoshell#485]
**Describe the bug**
In update Cairo Desktop M3.7086 to current, the feature to have blur behind the full width taskbar does not work properly. It will only show if you disable and re-enable the menu bar blur and will not show when restarting Cairo, starting Cairo, or when the computer starts.

**Steps to reproduce**
1. Have full width taskbar enabled
2. Start/Restart cairo from any means
3. There is no blur behind the full width taskbar.
4. Go to Cairo Settings
5. Menu Bar
6. Appearance
7. Uncheck and Recheck "Blur behind the menu bar"
8. The blur behind the taskbar should then be enabled till cairo is launched again.

**Expected behavior**
Blur should show as soon as Cairo starts, not having to uncheck and recheck the menu blur setting.

**System information:**
 - Windows version: Windows 10 Version 20H2 OS Build 19042.630
 - Cairo version: 0.3.7147.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
I had built a new computer and have had this problem on both my new and old computer.

**Comment by dremin** [comment]
This will be fixed in the next release. If you'd like to try the fix early, you can [install this build](https://ci.appveyor.com/api/buildjobs/3c8o8v87go35rkj5/artifacts/Installer%2FCairoSetup_64bit.exe).

**Comment by dremin** [comment]
This is fixed in the latest release.
