### ISSUE TITLE
Look of the task view button in taskbar

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#49]
As I stated in #33,
The [task view icon] has too many stripes I think. I looks like the grip of a handle and I expected it to be draggable by mouse at first. It is very mainstream and not original but a simple three-stripe hamburger
![image](https://user-images.githubusercontent.com/32496803/31676555-4b62a4ee-b368-11e7-8cc6-7225304610f1.png) icon would suffice.

**Comment by dremin** [comment]
This is fixed in the latest Milestone 3 release. Please check for updates and re-open the issue if it is not resolved.
