### ISSUE TITLE
Scan folder on click

### ISSUE THREAD

**Issue by Manaberry** [cairoshell/cairoshell#491]
Hi there,

EDIT: It seems I was wrong sorry, but folders are indeed removed from the Taskbar if they came from Google Drive or something that launches after Cairo (on PC startup.)

Thanks,
Keep up the good work.

**Comment by dremin** [comment]
Do you mean the folder stacks in the menu bar at the top of the screen? Which version of Cairo are you running?

**Comment by dremin** [comment]
Closing per update above.
