### ISSUE TITLE
context menu options have no spaces / bad spelling

### ISSUE THREAD

**Issue by Dinoraptor101** [cairoshell/cairoshell#496]
**Describe the bug**
context menu options for run as, run as user, and print to, are missing correct spacing.

**Steps to reproduce**
1. from the shortcuts dropdown (see directory pinned in the taskbar)
2. right-click an executable or an image

**Expected behaviour**
- I expect to see "Run as, Run as user, Print to" spelled correctly.
- Current implementation displays: "Runas, Runasuser, Printto"

**System information:**
 - Windows version: Windows 10
 - Cairo version:  Version 0.3.7147.0 - Pre-release
 - 32-bit or 64-bit: 64 bit.
 - In Cairo Settings > Advanced, is Cairo set as shell?:  Yes

**Additional context**
N/A

**Screenshots**
![2020-12-07 12_37_18-](https://user-images.githubusercontent.com/5091904/101384865-032eb600-3889-11eb-812f-f14f93aa9053.png)![2020-12-07 12_37_05-](https://user-images.githubusercontent.com/5091904/101384866-03c74c80-3889-11eb-92dc-79abc60b8349.png)

**Comment by dremin** [comment]
We need to either get the localized name for these verbs or find a way to display the shell context menu without it causing the stack to close.

**Comment by dremin** [comment]
This is fixed in the latest release.
