### ISSUE TITLE
Cairo Shell not starting when updating to the latest version.

### ISSUE THREAD

**Issue by ghost** [cairoshell/cairoshell#497]
**Describe the bug**
Cairo Shell not starting up after updating tot he latest version.

**Steps to reproduce**
1. Update Cairo Shell to the latest version
2. Restart Cairo Shell

**Expected behavior**
Cairo Shell starting up

**System information:**
 - Windows version: Windows 10 Pro
 - Cairo version: M3.7147
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Cairo is set as the default shell.

// Extra Information
Windows 10 Version: 20H2
What I have tried: I tried reinstalling, restarting Windows, logging in and out of Windows.
Cairo Shell version before update: M3.6943

// @JMWSoftware 2020 | Latest Edit: 5:19PM CST 12/7/2020

**Comment by dremin** [comment]
Did you have the option "Taskbar overlaps windows" set?

**Comment by dremin** [comment]
Does the latest release work for you?

**Comment by dremin** [comment]
Closing as no follow-up received and account was removed.
