### ISSUE TITLE
Action Center option is not greyed out when using Cairo as Shell

### ISSUE THREAD

**Issue by Dinoraptor101** [cairoshell/cairoshell#500]
**Describe the bug**

**Steps to reproduce**
1.  Switch Cairo to replace Windows as Shell
2.  Restart Computer
3.  Access Settings -> Menu Bar -> Menu Bar Items

**Expected behaviour**
I expect that actions depending on Windows Shell should become unavailable when we switch to Cairo as Shell.

**System information:**
 - Windows version: 
 - Cairo version: 
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?:  Yes

**Additional context**

**Screenshots**

**Comment by dremin** [comment]
Thanks for the report!

**Comment by dremin** [comment]
This is fixed in the latest release.
