### ISSUE TITLE
Error message when running app grabber

### ISSUE THREAD

**Issue by Gart763** [cairoshell/cairoshell#508]
**Describe the bug**

**Steps to reproduce**
1. installed
2. run welcome tutorial to the last step
3. opened app grabber via menu and closed it
4. finished tutorial opening app grabber

**Expected behavior**
No error message or crash

**System information:**
 - Windows version: Microsoft Hyper-V Server 2012 R2
 - Cairo version: 0.3.7174.0
 - 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: no

**Additional context**

**Screenshots**
![2020-12-23_11-11-35](https://user-images.githubusercontent.com/76506593/102969745-ab8e7c80-450f-11eb-93a6-d40d2f34c253.png)

**Comment by dremin** [comment]
I think I have a fix for this but am having trouble testing it, as I can't seem to get WPF apps to run on this OS. Did you have to install certain packages other than .NET?

**Comment by dremin** [comment]
This is fixed in the latest release.
