### ISSUE TITLE
Opening "Windows Settings" results in an error

### ISSUE THREAD

**Issue by featherbear** [cairoshell/cairoshell#51]
When clicking on the _Windows Settings_ menu option in the Cairo menu, nothing happens for around ten seconds. Afterwards an error message appears

```explorer.exe "File system error (-2147219200)."```

This error only occurs when CairoShell is set as the user shell.

I'm guessing it's something to do with some initialising not happening where needed?

**Comment by bearbear12345** [comment]
By the way

OS: Windows 10 Pro
Build: 16299
CairoShell: 1fa3337b95678efc29ec824b95f54e60b10acdcb

**Comment by dremin** [comment]
Good catch, the Settings app is a UWP app, which depends on Explorer as shell in order to run. I’ll remove this item when Explorer isn’t shell.

**Comment by dremin** [comment]
This is fixed in the latest release.

**Comment by codic12** [comment]
Hi, still running into this on Windows Server 19.
