### ISSUE TITLE
Laptop screen stays black after re-opening

### ISSUE THREAD

**Issue by FiddleStickers** [cairoshell/cairoshell#526]
**Describe the bug**
Laptop screen stays black after re-opening (Not sleep mode, see below 2nd step) with Cairo running. Nothing but force power off can fix it. Tried Ctrl+Alt+Delete as well, didn't work.

**Steps to reproduce**
1. Install Cairo
2. Set laptop to NOT sleep (Do nothing) when lid is closed in power settings, so it just turns off the screen. (My preference)
3. Start Cairo
4. Close laptop lid and open after about 10 seconds.

**Expected behavior**
N/A

**System information:**
 - Windows version: 10 x64 1909
 - Cairo version: M3.7174
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**

**Comment by FiddleStickers** [comment]
I LOVE Cairo Shell BTW 👌🏻😎

**Comment by dremin** [comment]
Thanks for the report! It seems odd that Cairo would cause this, does it occur if you exit Cairo before sleep?

**Comment by FiddleStickers** [comment]
I will test this more! I set my laptop to never sleep (even when closing the lid). I will report back soon.

**Comment by FiddleStickers** [comment]
You were right, of course. It happened without Cairo installed yesterday. You can close this!
