### ISSUE TITLE
Implement an inline restart option for Cairo

### ISSUE THREAD

**Issue by monster1612** [cairoshell/cairoshell#528]
**Is your feature request related to a problem? Please describe.**
sometimes, I find that Cairo will glitch out for whatever reason (like the taskbar won't appear sometimes if set to auto-hide, or specific notification icons won't work when right/double-clicked on), and the only way to restart Cairo would be making a trip to Cairo settings to expose the restart button by "changing" the language.

**Describe the solution you'd like**
I'd propose an option to restart Cairo using either a dedicated "Restart Cairo..." option in the Cairo menu, or by holding down a modifier key (like Shift) whilst clicking on "Exit Cairo..." to invoke an inline restart.

**Describe alternatives you've considered**
opening Cairo Settings and then selecting any language (even the one in use) will cause the "Restart Cairo to apply" option to appear, but this seems to require a few extra clicks and isn't super intuitive.

**Additional context**
N/A. this is a solid DE, and I would love to see it improve.

**Comment by dremin** [comment]
> opening Cairo Settings and then selecting any language (even the one in use) will cause the "Restart Cairo to apply" option to appear, but this seems to require a few extra clicks and isn't super intuitive.

Funny, that is exactly what I do :)

Naturally, we would prefer to fix the issues that make the need to restart Cairo arise in the first place, but I do agree that a key modifier with the Exit Cairo option would help in the interim.

**Comment by RooseBaker** [comment]
When Cairo errors out (ie. menu bar no longer appears - using it as Windows shell), I use Sysinternals pskill.exe:
@ECHO OFF
PSKILL /accepteula CairoDesktop
START "" "%ProgramFiles%\Cairo Shell\CairoDesktop.exe"

**Comment by dremin** [comment]
Forgot to close this earlier; it's available in the latest release.
