### ISSUE TITLE
Bugs with Forza Horizon 4

### ISSUE THREAD

**Issue by curoviyxru** [cairoshell/cairoshell#531]
**Describe the bug**
Programs menu item doesn't have an image icon. Game window doesn't show at taskbar.

**Steps to reproduce**
1. Install Forza Horizon 4 in Microsoft Store
2. Add Forza Horizon 4 in App Grabber
3. Launch the game

**Expected behavior**
Menu item have an icon. Game window shown at taskbar.

**System information:**
 - Windows version: Windows 10 Pro 20H2 19042.746
 - Cairo version: 0.4.62.9543
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/61984636/107251790-c7a99700-6a45-11eb-977c-b55b3be06eb7.png)
![image](https://user-images.githubusercontent.com/61984636/107251762-c24c4c80-6a45-11eb-8ff3-584f116936be.png)

**Comment by curoviyxru** [comment]
UPD: Game window shows at taskbar while it's loading and UWP window shows.

**Comment by dremin** [comment]
Thanks for the report! I'll see if I can reproduce with the Game Pass version.

**Comment by dremin** [comment]
I am able to reproduce this and will take a look.
