### ISSUE TITLE
Clock prevents me from energy-saving mode

### ISSUE THREAD

**Issue by juwo1811** [cairoshell/cairoshell#550]
The current time in the Cairo Desktop prevents me from going into energy-saving mode; if the time is removed, the mode works without any problems.

**Comment by dremin** [comment]
Could you please clarify what you mean by energy-saving mode and how you are measuring this, so that we can better understand?

**Comment by juwo1811** [comment]
Sorry I tested once more and now my PC shutdown to hibernate after my 
time..
Please close the ticket.
Regards
Juergen

------ Originalnachricht ------
Von: "Sam Johnson" ***@***.***>
An: "cairoshell/cairoshell" ***@***.***>
Cc: "juwo1811" ***@***.***>; "Author" 
***@***.***>
Gesendet: 19.04.2021 22:42:20
Betreff: Re: [cairoshell/cairoshell] Clock prevents me from 
energy-saving mode (#550)
