### ISSUE TITLE
[Feature Request] Add option to remove UI Transparency

### ISSUE THREAD

**Issue by aragubas** [cairoshell/cairoshell#555]
An option to remove transparency will be nice since my laptop has an Intel Celeron N3060 wich is not know for being fast

A option on Cairo Settings to remove all UI Transparency for better peformace

I gonna try messing up with the themes to try to remove transparency

No aditional context heh

**Comment by dremin** [comment]
Thanks for the report! I'd like to narrow down the source of slowdowns you're seeing. The menu bar and taskbar are fairly small windows, so their transparency shouldn't impact performance significantly. However, the desktop window is a full-screen transparent surface (when running with the default settings on top of Explorer), which I have definitely seen cause performance issues on lower-end machines. If you disable the desktop feature in Cairo Settings, do you see more acceptable performance?

**Comment by karmaral** [comment]
I came looking for the same thing, though not because of the performance.
I have a lot of icons and I tend to use the taskbar on top, so the transparency creates a lot of visual noise on top of the browser tabs and such. Is it possible to remove it via theming?

**Comment by josuave** [comment]
@karmaral I am working on a very small change that will allow you to set the "core" RGBA value of the MenuBar and TaskBar

**Comment by dremin** [comment]
Forgot to close this earlier; it's available in the latest release. Instructions for usage are in #568.
