### ISSUE TITLE
Cairo ignores "Show desktop icons" selection on exit

### ISSUE THREAD

**Issue by monster1612** [cairoshell/cairoshell#567]
**Describe the bug**
when Cairo is exited (either manually or by Windows during the logoff process), the Windows Explorer "Show desktop icons" setting is set to enabled regardless of its previous setting, even if it is disabled while Cairo is running.

**Steps to reproduce**
1. start Cairo.
2. in Windows Explorer, right click on any empty space in the desktop and under View, uncheck "Show desktop icons".
3. exit Cairo (or logoff/shutdown/reboot and log back in).

**Expected behavior**
if "Show desktop icons" is unchecked, desktop icons should not appear on the desktop once Cairo is exited.

**System information:**
 - Windows version: _Windows 10, Insider Preview build 21376_
 - Cairo version: _0.4.80.38114_
 - 32-bit or 64-bit: _64-bit_
 - In Cairo Settings > Advanced, is Cairo set as shell?: _no._

**Additional context**
this seems to occur regardless of if the "Show desktop icons" option is disabled before Cairo is launched or while it is running.

FWIW, in Cairo Settings -> Desktop, "Enable desktop" is NOT enabled.

**Screenshots**
N/A.

**Comment by dremin** [comment]
This will be fixed in the next release.
