### ISSUE TITLE
Menu -> Places -> Videos Library Folder is Missing

### ISSUE THREAD

**Issue by Carbongrip** [cairoshell/cairoshell#58]
Hello, I think you missed a Library Folder in the Places Menu, their is no Videos item. Videos is very much a Library folder in explorer.

Cheers!

**Comment by dremin** [comment]
Thanks for pointing this out, I'll add this.

**Comment by dremin** [comment]
This is fixed in the latest Milestone 3 release. Please check for updates and re-open the issue if it is not resolved.
