### ISSUE TITLE
Hide Windows System Tray icons if their Registry/G.P. values are set to hide them in Explorer

### ISSUE THREAD

**Issue by dominichayesferen** [cairoshell/cairoshell#588]
**Is your feature request related to a problem? Please describe.**
Windows Explorer has optional Registry / Group Policy settings where you can hide System Tray icons for all users, such as Network, and so on. However, right now Cairo's System Tray displays them despite this setting being in place.

**Describe the solution you'd like**
Cairo could do with following these values to hide the tray icons Explorer is configured to hide via Group Policy / Regedit policies.

**Describe alternatives you've considered**
Windows's own one exists, but... it isn't really a thing in Windows PE for example (the popup itself that's meant to appear doesn't exist at all).

**Additional context**
It's also useful for when having a substitute Networks list tray icon (hence you'd want to hide the Windows one to prevent duplication).

**Comment by dremin** [comment]
We already support this for the system volume icon, but we should expand to support the others.
