### ISSUE TITLE
Apps to auto-select in App Grabber

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#59]
- Firefox (64 bit)
- Google Chrome (64bit, not shown at all in App Grabber)
- VLC (64bit, not shown at all in App Grabber)

And the 32bit releases if they also lack...

Would it be possible to also create default groups ?
I think at least an 'Office' category is mandatory, because libreoffice and Microsoft Office add many entries.
Something like this would be a good start I think ([Photo from the official website](http://cairodesktop.com/img/ss_progs.png)).

**Comment by dremin** [comment]
These should be included already, but after looking into this I found some other bugs that caused these to be skipped over.
Pre-categorizing these is a good idea. I will give it a go.

**Comment by mdmk** [comment]
@dremin Could you list the apps that should be auto-selected please ?
I would like to add some other apps but if there are bugs preventing them to show it will just bother you unnecessarily.

**Comment by dremin** [comment]
The bug was with multiple shortcuts to the same application, so doesn't affect most apps, and will be fixed in the next build. 

[Here is the list of app names](https://github.com/cairoshell/cairoshell/blob/9a204ea63fd96dc3dc8775cdd917491c10e6bb6a/Cairo%20Desktop/CairoDesktop.AppGrabber/AppGrabberUI.xaml.cs#L228-L284) that Cairo currently looks for. Feel free to add your suggestions here.

**Comment by mdmk** [comment]
@dremin Some random unordered thoughts abouts categories, feel free to ignore some or all of them if they are not relevant.
- Do you consider paint as an accessory? Microsoft do, but I'm not so sure it is relevant. Letting it in accessories does not lead to confusion due to the app's lack of complexity. But we have an appropriate Graphic category, what about using it?
- Is it relevant to list libreoffice safe mode? I personally never used it I think (I frequently erase profile though when encountering bugs after update so I'm really not of sound advice on this).
- Can you make a special 'Other' category at the end of all of them? It would list everything that is not in a category. So, e.g. I add Core Temp in app grabber, it does not belong to a category and it is one of the only app that is in that case, I will then check in 'Other' instead of in 'All' where I'm sure 90% of the app are not the one I seek for.
- Perhaps auto-selecting Internet as default category would be good. I mean, it is what most people use (but not necessarily what typical cairo users would of course). I just thought that opening by default on 'All' is not nice, the list is pretty long. I feel a bit overwhelmed, perhaps the list height is a bit too much compared to it's width. It is no more tall than native start menu, but perhaps the impression is because the text is more compact.

**Comment by mdmk** [comment]
@ dremin File explorer is uncategorized in task view (sorry, not the best place to report it)

**Comment by mdmk** [comment]
Notepad++ should be in dev tools, not accessory.

**Comment by dremin** [comment]
@mdmk -
- Uncategorized is hidden from Programs menu intentionally.
- Safe mode icons should be hidden in the next build.
- Notepad++ category will be Development by default in the next build.

**Comment by dremin** [comment]
The latest build includes the fixes mentioned above. Closing this issue as there are no more outstanding items that I plan on addressing. Thanks for providing the suggestions, this feature is much more complete with them implemented.

**Comment by mdmk** [comment]
I spotted a regression on M3.6557
This apps are no longer auto-selected, unlike before (it is working fine in M3.6555) :
- Calculator
- Sticky notes
- Edge
- Dropbox
As for OBS, it is now called `"OBS Studio (64bit)"` and `"OBS Studio (32bit)"`, not `"Open Broadcast Software"` like the legacy implementation that is discontinued.
So it is not selected by default. On 64bit OS the setup installs both 32 and 64bit versions.

**Comment by dremin** [comment]
The above items should be resolved in the next build.
