### ISSUE TITLE
Add shortcut to computer management

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#60]
I'm not sure of exact name of the [app](https://user-images.githubusercontent.com/32496803/33385408-ce0c7eec-d528-11e7-8f1f-5be93aded876.png) in english.
I think a hard coded shortcut [here](https://user-images.githubusercontent.com/32496803/33384883-7f84e8d2-d527-11e7-9888-e48c1b83448a.png) (sorry for the blattant painting) would be useful.

It would avoid the need to have multiple shortcuts for services console, disk management, task management, perfmon, resmon, windows logs, etc. and that would help to keep things uncluttered without losing functionality.

**Comment by dremin** [comment]
Computer Management can be added using App Grabber. Is it not appearing in yours?

**Comment by mdmk** [comment]
It is appearing of course, no problem in app grabber.
I just thougt it would be a better place on the orb menu.
I think of it like the right click on the native start orb, where Microsoft lists the system tools in one place.
As you list control panel and modern settings here, I thought it would be convenient and logical to also put it here, it would not clutter app grabber (note microsoft removed legacy control panel from this menu in a more or less recent update).
Just a thought though of course.
Don't hesistate to close the issue if you feel it is not relevant.

**Comment by dremin** [comment]
Since Computer Management is more or less an advanced tool, and can be added to the Programs menu via App Grabber, I am going to close this.
As a side note you should still be able to access the Start button right-click menu by using the WinKey-X shortcut.
