### ISSUE TITLE
"Open as administrator" launches UWP apps without elevated permissions

### ISSUE THREAD

**Issue by monster1612** [cairoshell/cairoshell#605]
**Describe the bug**
when using Cairo to launch a UWP app (such as Windows Terminal or PowerShell Preview) via right-click -> "Open as administrator", no UAC prompt appears and the app is launched without elevated permissions.

**Steps to reproduce**
1. install a UWP app (for example, [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)).
2. add a shortcut for the app to Cairo via App Grabber or Quick Launch.
3. right-click on the app shortcut, and then click "Open as administrator".
4. no UAC prompt appears, and the program does not indicate it is running as administrator.

**Expected behavior**
a UAC prompt should appear for the app.

**System information:**
 - Windows version: _Windows 11, Insider build 22000.51_
 - Cairo version: _0.4.133.47321_
 - 32-bit or 64-bit: _64-bit_
 - In Cairo Settings > Advanced, is Cairo set as shell?: _no._

**Additional context**
if launched via the dynamic desktop (or when the desktop is enabled in Cairo), the UAC prompt appears correctly when using right-click -> Run as administrator.

non-UWP apps, like DIscord, correctly trigger UAC prompts if launched via "Open as adminstrator".

**Screenshots**
N/A.

**Comment by dremin** [comment]
Hm, I don't think UWP apps can run elevated in any scenario. It probably makes sense to hide this option for UWP apps.

**Comment by monster1612** [comment]
(apologies for bumping this dormant issue thread; I've been pretty busy with school.)

I've been noticing that Windows Terminal can in fact be run as administrator when launched via the Start Menu, and it behaves pretty much like Command Prompt or PowerShell do when launched in an elevated fashion. (basically just PowerShell with tabs.)

the curious thing here is that using [PowerToys Run](https://docs.microsoft.com/en-us/windows/powertoys/run) (acts similar to Spotlight on a Mac), Windows Terminal can be directly executed as an administrator like it can in the Start Menu. the underlying file launched here is the WindowsTerminal.exe binary (see below screenshot), which I can't manually invoke with administrator permissions if I right-click on the file in File Explorer and then just choose "Run as administrator". (that throws an error, and I'm guessing Cairo programmatically is trying and failing to elevate it with that same approach.)

I did some digging around in the PowerToys repo to see if I could try to pick apart specific functions that handle the actual elevation request, and all I've found so far are files that [check whether programs can be elevated](https://github.com/microsoft/PowerToys/blob/main/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/ContextMenuLoader.cs) (via `CanFileBeRunAsAdmin`) and [attempt elevation](https://github.com/microsoft/PowerToys/blob/main/src/modules/launcher/Wox.Infrastructure/Helper.cs) (via `RunAsAdmin`?). 

I know this likely would involve some amount of work on your end, so no worries if you can't/aren't willing to look into it; I thought I should at least try to point in the right direction for a working example.

![WindowsTerminal - elevated through PowerToys Run](https://user-images.githubusercontent.com/3804289/140201734-e7561555-36e4-46a8-8200-9833ccdf5bd2.png)

**Comment by dremin** [comment]
Hm, this is intriguing. The above links show that PowerToys is running the app as admin in the exact same way we run win32 apps as admin. However, we launch UWP apps differently than win32 apps. I've had issues running UWP exe files directly in the past, but this shows it can work, so I'll need to do some testing to see what we can do in this scenario.

**Comment by dremin** [comment]
Ah, I've figured it out. Launching directly from shell:appsfolder seems to run as admin for apps that allow it. I'll need to check the app manifest for if the app allows running as admin.
