### ISSUE TITLE
Taskbar progress too small when "Show labels" is disabled

### ISSUE THREAD

**Issue by jonaskohl** [cairoshell/cairoshell#615]
**Describe the bug**
When the option *Show labels* is disabled, the taskbar progress gets this weird "margin" and does not fill the whole button. This makes the progress indicator really difficult to see.

**Steps to reproduce**
1. Run an application which shows some progress on the taskbar (e.g. download something in Chrome)
2. Disable *Show labels* inside of the Cairo settings

**Expected behavior**
The progress should fill the whole button as it does when *Show labels* is enabled.

**System information:**
 - Windows version: Windows 7 Ultimate SP1 x64
 - Cairo version: 0.4.133.47321 - Pre-release
 - 32-bit or 64-bit: 64 Bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  No

**Additional context**
-

**Screenshots**
![1](https://user-images.githubusercontent.com/23175424/131685888-915edce0-bae5-4e79-88bb-95a72aa76443.PNG)
![2](https://user-images.githubusercontent.com/23175424/131685900-0edda0dc-9444-42ff-a6de-cb2bd32589ad.PNG)

**Comment by dremin** [comment]
This is resolved in the latest release.
