### ISSUE TITLE
Typing text extremely slow and laggy in Win7

### ISSUE THREAD

**Issue by stubkan** [cairoshell/cairoshell#62]
Running win7, on a panasonic toughbook CF19

When I type text in a browser window field, (ie on discord) or in notepad, etc.. 

It is really slow, as if enormous processing power was required for each letter, maybe 500ms lag for each letter, but after I type maybe 5 or 6 words, then it speeds up in spurts, to complete a few words, then goes back to incredibly slow laggy typing...

Obviously, this means I can't use this shell.  Would love help fixing this!

**Comment by dremin** [comment]
@stubkan Thanks for the report. Does this happen the entire duration that you have Cairo open or does it only occur after certain actions? Could you please post a screenshot of Cairo in Task Manager during slowness?

**Comment by stubkan** [comment]
yeah it seems to be a permanent - always active 'slowness'  ugh.. im typing this in cairo at hte moment,.


every thing that needs to be typed, has the terrible input lag ...


in task manager, resource monitor.. cairo seems to have no discernable resource hogging, other processes take up the resources, such as notepad (when i test) and firefox, .. total resource and cpu used doesnt go above 20%


RAM only 2gb out of 8 used.. staying constant


well, anything that needs a keystroke is lagged.  including windows functions such as alt-tabbing


perhaps it just doesnt like my keyboard


mouse speedy, no lag...  only key inputs are affected.




________________________________

**Comment by mdmk** [comment]
@stubkan  Can you scan your system with [mbam free](https://malwarebytes.com/) just to be sure you do not have some kind of keylogger that would interfere with Cairo?

**Comment by stubkan** [comment]
oh boy i sure hope not.


installing and scanning now...

also getting AVG antivirus to check as well


It's just odd... typing is great, then I start cairo, then it goes out the window... quit cairo, back to normal!


malware found 9 potentials..  8 registry keys and 1 firefox thing...  quarantined the lot



________________________________

**Comment by stubkan** [comment]
AVG also found nothing..


i tried cairo again,


I noticed that after I type a few words, it sort of freezes, and my mouse movement also slows down and clicks dont register...


Any other ideas, what I can try checking?


________________________________

**Comment by mdmk** [comment]
So no active threat, just leftovers.

Can you check [this](https://support.microsoft.com/en-us/help/894040/adjust-long-delay-in-keystrokes-appearing-due-to-windows-filterkeys)? It concerns native shell and should not affect Cairo, or at least should affect native shell first I think, but better check it out just in case.

I also think of an igp bottleneck. Can you check gpu usage with [process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)? Click on the top right graph, it will show gpu usage. If any graph is topping 100% let us know.

**Comment by mdmk** [comment]
Also, did you try with antivirus disabled ?

**Comment by stubkan** [comment]
Hi, thanksk for those suggestions..


I've got process explorere open now..  watching the general screen with all the graphs..


(antiviruses are all off, I keep the task bar icons empty aswell, of all running processes and programs.. I like my system speedy)


filter keys was off, i turned on and off again just in case..


Only thing I notice is..  when I start typing..  there is a spike in I/O in the general graphs.. will have a look and see if I can see what's causing that . Looks like firefox, when I started typing.  But it isn't spiking anymore, onl short while, when I began to type this email.


GPU engine graph seems to hold around 1-2.5%


I can't seem to findany anomalies...


________________________________

**Comment by dremin** [comment]
I'm wondering if this is a graphics driver issue. I'll add a software rendering mode to the next build to see if this helps your issue.

**Comment by dremin** [comment]
Please try the latest build. Once updated and Cairo is running, navigate to Cairo menu > Cairo Settings. Select the "Force software rendering (advanced)" option, then click the orange Restart button that appears.

After Cairo restarts, please let me know if this helps.

**Comment by stubkan** [comment]
Thank you for that!


Yeah, I think I'm running in the software rendering now...  Hwoever, the issue of typing lag persists...  :(


For some reason, this new update means I get intermittent brief bursts of smooth typing- but more than not it's lagged.


I'm running on top of explorer. I will restart and replace explorer with cairo and see..  if there is an improvement I'll write another email




________________________________

**Comment by dremin** [comment]
@stubkan - did replacing Explorer improve this for you? I also wonder if using a fresh user account would help. Another thing to try would be disabling parts of Cairo (desktop, taskbar, etc) to see if a certain component is causing the issue.

**Comment by mdmk** [comment]
@stubkan You could also try lauching Windows in failsafe mode, then using Cairo. In this mode, there should not be any unpredictable software conflicts.
By the way, does the problem appear with a USB keyboard, not just the internal one?

**Comment by stubkan** [comment]
Nah, replacing explorer it didn't fix it.  I tried turning on/off various cairo features - though there didn't seem to be many.  Also the issue persists with both the USB keyboard and the laptop keyboard.


I'll try the new user thing now.   Also will try starting in safemode.


Where does the hook for the system to start cairo instead of explorer occur?  I'd like to manually edit it to assist my testing and switching back and forth from explorer/cairo...


If it all fails, I might reinstall windows..  I have 3gb of toughbook drivers to install though - these proprietry drivers are a pain.  I could then install cairo right off the bat and see if the problem begins after a particular driver has been installed, but I'd like to leave that as a last resort!



________________________________

**Comment by dremin** [comment]
If you choose Exit Cairo from the Cairo menu, Explorer will restart.
The switch is in the registry: `HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinLogon\Shell`. This is also reverted by the uninstaller.

**Comment by stubkan** [comment]
It does not seem to restart for me..  (when using just cairo, without explorer running at all) It might be a little wonky because I was also playing with Litestep (which seems to have frozen in development from win98 days)


I have new tests to report :


Safe mode - absolutely no key lag...  it in fact seemed to have less of an input delay than normal windows


debug mode - has the spontaneous key lag 😞


making a new blank user did not seem to help.


I'm afraid that I might have to go with a reinstall ....  I really want to use cairo, it looks sweet.

________________________________

**Comment by mdmk** [comment]
@stubkan In safe mode there is no lag?
If you don't want to do a clean install from scratch, I suggest you try to fiddle a bit with `msconfig `(start options) to identify the culprit.
You can find it by typing `msconfig `in the start menu search bar,
You can proceed through the steps below, step by step, with a reboot between each step.
I'm on Windows 10 in french so names will be a bit different some times.

1. Tab Start (fourth tab), untick everything (antivirus will often retick itself after reboot, don't be surprised)
2. Tab Services (third tab), tick hide every Microsoft services, then click button desactivate all (it will then desactivate all but Microsoft ones)
3. At this step, Cairo should not lag, if it lags, please stop and report back, it is probably a core component (Microsoft service or driver or antivirus that is not disabled by the previous steps).
4. If it does not lag, please continue the procedure.
5. In tab Services, retick entry by entry, with reboots between each (you can tick 2 or 3 at the same time, but don't try to go too fast, often, ticking a thing lauches unticked items without you knowing it, so it can quickly false your diagnosis).
6. In tab Start, retick every entry progressively in the same manner.
7. When Cairo lags again, you found the culprit, or at least an entry that lauches the culprit, so please report back.

If you choose to do a clean install and it does resolve the issue, please report back so we can close the issue.
Thanks.

**Comment by dremin** [comment]
Closing due to lack of response.. feel free to update this if you are able to isolate the issue!
