### ISSUE TITLE
Program categories not localized

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#64]
The default categories are not localized even though they have translations.

**Comment by mdmk** [comment]
You did not include categories strings in the cairoshell dictionaries in / Cairo Desktop / CairoDesktop.Localization / Language.cs
Perhaps not related, sorry if it is the case.

**Comment by dremin** [comment]
I included the "All" "Uncategorized" and "Quick Launch" but forgot to add the new ones. Good catch, those will need to be added to the list.

Unrelated but I also noticed truncations in the shut down/restart/log off dialogs, I will fix these as well.

**Comment by mdmk** [comment]
It seems the strings of the setup and the check update utility are separate from the rest of the program.
Will you do something about this ?
Also, any projects to localize the website?
