### ISSUE TITLE
Really strange error when running WaveEdit only through Cairo despite not happening if launched other ways

### ISSUE THREAD

**Issue by Someone65** [cairoshell/cairoshell#640]
**Describe the bug**
Running WaveEdit through Cairo only will throw MinGW Runtime Assertion errors like this one on application launch: 
![image](https://user-images.githubusercontent.com/5289161/143806238-e09216a5-f665-4564-9f91-91181856e82d.png)

Launching it outside of Cairo doesn't cause these issues.

EDIT: Adding it as a shortcut instead works as a workaround. Also, other programs have broken for me before in similar ways if launching the executables directly imported as a shortcut into Cairo or through the desktop browser.

**Steps to reproduce**
1. Download and add the shortcut to Cairo for [WaveEdit](https://synthtech.com/waveedit/) (in my case, I added it by dragging and dropping the executable into the Programs list and also tried to launch it by adding the folder to the top bar and launching it through there)
2. Run WaveEdit through Cairo
3. Test again by launching WaveEdit through other means (Windows Explorer, explorer alternatives, etc)

**Expected behavior**

**System information:**
 - Windows version: Windows 10 20H2 build 19042.1288
 - Cairo version: Version 0.4.158.53003 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: no

**Comment by dremin** [comment]
It looks like we are not setting the working directly when invoking IContextMenu commands.

**Comment by dremin** [comment]
@Someone65 I have a fix for WaveEdit. You mentioned other programs have broken in the same way--do you remember what those are? I'd like to see if this fixes those too.

**Comment by Someone65** [comment]
Sorry, was on a vacation. I also noticed [Pedalboard2](http://www.niallmoody.com/work/pedalboard2/) crashing with a simple "has stopped working" error when launched from Cairo. I'll try finding more software on my pc that does this but I doubt they aren't fixed by the fix you merged.

**Comment by dremin** [comment]
@Someone65 I wasn't able to reproduce that issue with Pedalboard2 before or after the fix- were you doing anything other than double-clicking the exe?

**Comment by dremin** [comment]
Side note- the fix is currently available in [this build](https://github.com/cairoshell/cairoshell/suites/4555399182/artifacts/122351141) if you'd like to test it (GitHub login required for that link to work)

**Comment by Someone65** [comment]
I restarted my PC since I reported the Pedalboard2 issue and I can't reproduce it anymore, either.

Also, with the new build from your reply, I can't find anything that crashes anymore as a result of launching from Cairo.

**Comment by Someone65** [comment]
I'm having a similar issue again but with [Virtual ANS](https://warmplace.ru/soft/ans/). It launches fine through the folder but boots up as Pixilang instead of what its supposed to when launched through Cairo. It's supposed to read boot.pixicode by default but you have to load it up manually when launching through Cairo.

**Comment by dremin** [comment]
> I'm having a similar issue again but with [Virtual ANS](https://warmplace.ru/soft/ans/). It launches fine through the folder but boots up as Pixilang instead of what it's supposed to when launched through Cairo. It's supposed to read boot.pixicode by default but you have to load it up manually when launching through Cairo.

I downloaded this, and opened it from both File Explorer and from Cairo, and the app looked the same to me in each scenario. However, I don't know how to use it! What steps are you performing within the app that shows the problem?
