### ISSUE TITLE
Crash when launching a game through Steam

### ISSUE THREAD

**Issue by Someone65** [cairoshell/cairoshell#645]
Got a crash while launching a LOVE2D engine game on Steam (it's not consistent at all. First time this has happened to me).

**System information:**
 - Windows version: Windows 10 20H2
 - Cairo version: Version 0.4.164.51285 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: no
EDIT: forgot to include system info. sorry

**Screenshots**
![Screenshot](https://cdn.discordapp.com/attachments/584019391235227648/918340978501357568/unknown.png)

**Comment by dremin** [comment]
Did a specific game cause this, or is it any game created with that engine?

**Comment by Someone65** [comment]
It's not consistent at all and I had the same error happen again while searching for something through Everything through Tablacus. The game that caused that crash on launch was Mud and Blood and it hasn't happened since (except for the aforementioned one with Everything).

**Comment by Someone65** [comment]
Another crash running REAPER DAW when opening an LV2 plugin that brought up an error Window because I accidentally built the lv2 for linux instead of windows and this popped up in the background:

![screenshot](https://cdn.discordapp.com/attachments/523177407805390880/921073463169523742/unknown.png)

**Comment by dremin** [comment]
In Cairo Settings > Taskbar, what is your "group taskbar by" setting set to?

**Comment by Someone65** [comment]
Application (Combined)

**Comment by dremin** [comment]
Thanks! Are you able to confirm if using any of the other grouping options avoids crashing in the same scenarios?

**Comment by Someone65** [comment]
I'll try the other two for a day or two and see if it crashes. It seems to happen most with REAPER for some reason which doesn't even create multiple items in the taskbar.

**Comment by Someone65** [comment]
No crashes from either of the other two modes.

**Comment by dremin** [comment]
Thank you for testing! This confirms that the fix I am working on should address your issue.

**Comment by Someone65** [comment]
Using Version 0.4.174.64607 - Pre-release for two days, no crashes so far with the combined mode despite using all the software that usually cause these issues.

**Comment by dremin** [comment]
Awesome, thanks for confirming!
