### ISSUE TITLE
fix right click crashes

### ISSUE THREAD

**Issue by TopGamerPro16** [cairoshell/cairoshell#646]
**Describe the bug**
When Cario is open, right clicking causes most apps, or Cario to crash. 

**Steps to reproduce**
1. Have my windows-related issues (Additional context)
2. open any app (it happens on Cario too) besides notepad++ and browsers
3. keep right clicking anywhere on that app until it crashes (about 3x)
I know for a fact that this is a Cario (+my issue, excuse me) related issue because  my apps don't crash when I right click when the desktop is empty (no shell is running)
**Expected behavior**
Apps don't crash.

**System information:**
Cario 0.4.1588.53003 pr on Windows 11 1H2 Build 2000.318 (shell disabled)

**Additional context**
[Post I made for some reason on MS-Docs](https://docs.microsoft.com/en-us/answers/questions/638616/windows-is-broken.html)

**Comment by monster1612** [comment]
based off of the thread you linked in, it sounds like the Windows Explorer shell isn't properly initializing on login. given that, I think you may want to try the following:

1. open Cairo Settings, and under Advanced, note which shell is currently set as "your shell" (usually either Cairo or Windows Explorer).
2. if Cairo's set as the shell, click "Set Windows Explorer as Shell" and then log out/log in when prompted to have it take effect.
3. if Windows Explorer is set as the shell, click "Set Cairo as Shell", log out/in, and then reopen Cairo Settings to reset it to Windows Explorer via step 2.

hope this helps.

**Comment by TopGamerPro16** [comment]
Thank you for trying, but I've already reset my pc. 
I had to reset twice for the same issue, but it turns out that explorer decided to stop working, just once more. but, fortunately, resetting my pc fixed part of the issue. right clicking is fixed, and thanks to the new update, I can now access notifications and the other little menu containing connections, and (I'm guessing a windows update, when explorer decides it wants to start up successfully, it simply shown a black screen before. I had no access to touchpad gestures) when I use a gesture, the shortcut activates. and I missed the volume bar in the top left.

but settings still refuse to start. so...........
