### ISSUE TITLE
Missing capital letter in calendar popup

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#66]
An non-issue here; the first letter should be uppercase (I know, I'm a bit picky).

![screenshot46](https://user-images.githubusercontent.com/32496803/33951238-bcea469c-e02e-11e7-973a-0afc91552173.png)

**Comment by dremin** [comment]
I believe the calendar popup is using the region settings from the operating system. With my system set to en_US, these are capitalized. If you open Control Panel > Language > "Change date, time, or number formats" the system should show you an example of the formats its using.

**Comment by mdmk** [comment]
In fact, the calendar is in french even if Cairo is set to english.
Hum, that means it's a feature and not a bug...

It comes from french default parameters on the Windows level.

![screenshot48](https://user-images.githubusercontent.com/32496803/33952577-898ce08a-e032-11e7-9642-10fc1c6cb139.png)

It should be "Mercredi 13 décembre 2017", with a capital on the first word.
In the first [picture](https://user-images.githubusercontent.com/32496803/33951238-bcea469c-e02e-11e7-973a-0afc91552173.png) upper in the thread, I think only the end of the string is truncated and shown, so the month becomes the first word and Cairo should ideally display "Décembre 2017" with a capital letter.

On the other hand english is correct because everything is capitalized, which is convenient;

![screenshot49](https://user-images.githubusercontent.com/32496803/33952591-92eeacb2-e032-11e7-9535-16d3bfcb3a5f.png)


I checked spanish and italian, no capitalization.
On the other hand, deutsh is capitalized.

If possible, a fix to force an initial capital letter would be nice.
But I understand it is in no way a critical issue for sure, it is just that most of the users will not correct their windows parameters to correct display in Cairo...

**Comment by mdmk** [comment]
An other problem of capitalization.
"Logiciel" should have a lowercase first letter.

![screenshot50](https://user-images.githubusercontent.com/32496803/33953180-6c9c644e-e034-11e7-9373-d66b4239ed93.png)

**Comment by dremin** [comment]
How does Windows display the date in the taskbar calendar flyout?

Regarding the updates window capitalization issue, I would suggest [opening an issue with WinSparkle's GitHub](https://github.com/vslavik/winsparkle/issues) to have this resolved in the library.

I would like to get the installer and website localized as well at some point-- I will open a separate issue for those and make updates as I have strings available.

**Comment by dremin** [comment]
Closing as this appears to be working correctly depending on locale settings.
