### ISSUE TITLE
Localizable installer and website

### ISSUE THREAD

**Issue by dremin** [cairoshell/cairoshell#67]
The installer and website need to be localizable, and strings need to be generated.

**Comment by dremin** [comment]
@mdmk Could you please help localize the installer strings?

**Comment by dremin** [comment]
@mdmk Could you please help localize the installer strings?

"This installer will guide you through the installation of Cairo.\r\n\r\nBefore installing, please ensure .NET Framework 4.5.2 or higher is installed, and that any running instance of Cairo is ended.\r\n\r\nClick Next to continue."
"Start Cairo Desktop Environment"
"Please be sure that you have closed Cairo before uninstalling to ensure that all files are removed."
"Cairo is currently running. Please exit Cairo from the Cairo menu and run this installer again."
"Cairo requires Microsoft .NET Framework 4.5.2 or higher. Please install this from the Microsoft web site and install Cairo again."
"Cairo Desktop (required)"
"Run at startup (current user)"
"Advanced users only: Replace Explorer (current user)"
"Installs Cairo and its required components."
"Makes Cairo start up when you log in."
"Run Cairo instead of Windows Explorer. Note this also disables many new features in Windows."

**Comment by mdmk** [comment]
Sure, I'm pleased to help:
```
"Cet installateur va vous guider au long de l'installation de Cairo.\r\n\r\nAvant d'installer, veuillez vous assurer que le .NET Framework 4.5.2 ou plus récent est installé, et que vous avez quitté toute instance de Cairo encore en cours de fonctionnement.\r\n\r\nCliquez sur Suivant pour continuer."
"Démarrer l'environnement de bureau Cairo"
"Veuillez vérifier que vous avez fermé Cairo avant de le désinstaller pour assurer que tous les fichiers soient supprimés."
"Cairo est en cours de fonctionnement. Veuillez quitter Cairo depuis le menu Cairo et lancer de nouveau cet installateur."
"Cairo nécessite le Microsoft .NET Framework 4.5.2 ou plus récent. Veuillez l'installer depuis le site web de Microsoft et installer de nouveau Cairo."
"Bureau Cairo (requis)"
"Lancer au démarrage (utilisateur actuel)"
"Utilisateurs avancés uniquement : remplacer l'Explorateur Windows (utilisateur actuel)"
"Installer Cairo et ses composants requis."
"Démarrer Cairo lorsque vous vous connectez."
"Lancer Cairo au lieu de l'Explorateur Windows. Notez que cela désactive également de nombreuses fonctionnalités nouvelles dans Windows."
```

I think you missed quite a lot of strings, at least the buttons, but there's more in term of agreement and component selection pages, unless you're changing the previous dialogs in the process (I took a look at the current milestone setup file):
```
"Next" > "Suivant"
"Cancel" > "Annuler"
"I Agree" > "J'accepte"
```

Bonus: the last string you added to the dictionnary :
`{ "sError_CantOpenAppWiz", "Impossible d'ouvrir le panneau Programmes et fonctionnalités." },`

**Comment by mdmk** [comment]
About the website, can you tell me more about what you think is possible?
Do you wish to keep it on github pages hosting?
In this case, the localization is only possible with javascript (no PHP or such server side languages).
Or plain HTML with hyperlinks, one page for each language.

There is not much to translate on the page so I think I could quickly translate the 4 paragraphs or so.

**Comment by dremin** [comment]
Thanks for the translations! I have incorporated them.
The other installer strings should be covered by NSIS already.

The website is not hosted on GitHub so I have quite a few options, but I haven't thought about them much yet. I will probably write a PHP solution.

**Comment by mdmk** [comment]
@dremin Do you have any project for a more user-friendly way of contributing translations?
Transifex is free for open source projects for example.

**Comment by dremin** [comment]
@mdmk I have not but will need to when Cairo supports more languages. It's not worth it at the moment until there are more translation contributors.

Also, I have made the decision to not localize the web site at the moment, as I won't be able to help troubleshoot Cairo issues with users who don't have some English knowledge. I wouldn't be surprised if this changes in the future but I will need a larger contributor base to make full localization work out.

I'll be closing this issue since the installer has been localized for a few builds now.
