### ISSUE TITLE
windows 11 quick settings are cut off at the top

### ISSUE THREAD

**Issue by linux-leo** [cairoshell/cairoshell#679]
**Describe the bug**
Windows 11 quick settings are cut off at the top.

**Steps to reproduce**
1. Open Quick Settings (press the volume or wifi icon)

**System information:**
 - Windows version: Windows 11 21H2
 - Cairo version: 0.4.198.3828
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Comment by dremin** [comment]
I believe this is a Windows bug. I am not seeing this issue on insider builds, so hopefully it should be fixed when 22H2 releases.

**Comment by dremin** [comment]
Windows 11 22H2 fixes this.
