### ISSUE TITLE
Windows 7 UX style Core

### ISSUE THREAD

**Issue by Spiral-zz** [cairoshell/cairoshell#7]
Hello,
First of all I really what you are doing and I would like to help if I knew programming.  The issue I'm having is that both cairo and windows explorer are running at the same time.  I still have my taskbar and start menu as well as the cairo interface.  I think this is because UXstyle core theme changing program is working with the same files or something.  I just wanted to let you know.
Take care,
Spiral

**Comment by cairoshell** [comment]
This has been fixed; please download the latest version from [cairodesktop.com](http://cairodesktop.com). Thanks!
