### ISSUE TITLE
Default places not localized when added to stacks

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#70]
They are okay in the Places menu, but once on they are added to the bar as stacks they are in english.

![screenshot1](https://user-images.githubusercontent.com/32496803/34001969-b72eb9cc-e0f1-11e7-9ffe-8c78ddd5db5f.png)

**Comment by dremin** [comment]
(this fix should also localize program names in the App Grabber as a bonus)

**Comment by mdmk** [comment]
Works great, well done!
The issue can be closed.
