### ISSUE TITLE
Unattended Setup

### ISSUE THREAD

**Issue by Niklas20114552** [cairoshell/cairoshell#700]
I'm trying to make a custom Windows 11 Version, that's installs Cairo Shell automatically. But the Setup contains no support for arguments.

I want it to be possible to put the setup in silent mode with for example /silent, /passive or something similar. In addition. I need also the option of setting Cairoshell as the standard shell with an argument.

There can also be an MSI version that selects all features by default.

Does something like this already exist and am I just too stupid to notice it?

**Comment by dremin** [comment]
Adding the `/S` argument to the installer will trigger silent setup. The update mechanism uses this when installing an update.

**Comment by Niklas20114552** [comment]
Thank you for your response.
Is it possible to specify with an argument that cairo shell is the default shell?

**Comment by dremin** [comment]
There is not, here is a .reg file which does the same thing.
[cairo_as_shell.zip](https://github.com/cairoshell/cairoshell/files/9330040/cairo_as_shell.zip)
