### ISSUE TITLE
Website not working because SSL certificate has expired

### ISSUE THREAD

**Issue by markski1** [cairoshell/cairoshell#701]
Standard bug report format not relevant.

Cairodesktop and Cairoshell domains are currently not working. Because the Let's Encrypt certificates expired on August 9, and the sites are set up with strict transport policy so they won't allow non-SSL connections. Please renew the certificates so that the website works again, cheers

**Comment by ScottRFrost** [comment]
It looks like the public webserver is running nginx.  Here's how to set up Let's Encrypt with auto-renew via certbot on Nginx https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

**Comment by dremin** [comment]
Oops, I thought I fixed reload after renewal last time, apparently I did not. Thanks for the note, I've fixed the issue!
