### ISSUE TITLE
No ARM release of WinSparkle.

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#705]
Can we setup a simple updater just for ARM? Whats the application? Just server and hosted processes?

From:
The ARM64 build works, but is currently without WinSparkle updater support, as there is no ARM release of WinSparkle.

__Originally posted by @dremin in https://github.com/cairoshell/cairoshell/pull/703#issuecomment-1214296180__

**Comment by dremin** [comment]
WinSparkle is reading [this Sparkle RSS feed](https://github.com/cairoshell/cairoshell.github.com/blob/master/appdescriptor.rss).

We have a few options:
- Use another Sparkle-compatible library
- Write our own logic for parsing the RSS and downloading the file
- Switch to another updater solution entirely

**Comment by dremin** [comment]
I'm currently prototyping a [NetSparkle](https://github.com/NetSparkleUpdater/NetSparkle) implementation.

**Comment by lostmsu** [comment]
Have you guys considered MSIX packaging with self-updaters?

**Comment by josuave** [comment]
I will review some the guidance here: https://learn.microsoft.com/en-us/windows/msix/app-installer/auto-update-and-repair--overview

**Comment by dremin** [comment]
Fixed by #812.
