### ISSUE TITLE
Detected as malware

### ISSUE THREAD

**Issue by chris-zh-ch** [cairoshell/cairoshell#732]
Hi

I checked CairoSetup_64bit.exe with VirusTotal which returns:

Bkav Pro: W32.AIDetect.malware2
Cynet: Malicious (score: 100)
McAfee-GW-Edition: BehavesLike.Win32.Dropper.wc
SecureAge: Malicious

I didn't install. Nobody else concerning about this?

**Comment by fq0e** [comment]
cairo shell isnt malware, ive been using it for around 2 months now with no issues

**Comment by chris-zh-ch** [comment]
Thanks
