### ISSUE TITLE
Cairo cant open uwp programs with windows as shell

### ISSUE THREAD

**Issue by O5-3TheKid** [cairoshell/cairoshell#734]
when opening MS Edge webpages installed as apps Cairo throws a permission or does not exist error whats odd is they worked for months prior

I unless this is happening for everyone with win 11 and the latest patch i have no idea

**Expected behavior**
it should launch the program
**System information:**
 - Windows version: Win 11 Pro 21H2
 - Cairo version: Version 0.4.245.61259 
 - 64-bit: 
 - windows shell

**Additional context**

**Screenshots**

**Comment by Blastd** [comment]
It is a known issue
as referenced on [MSDN](https://social.msdn.microsoft.com/Forums/lync/en-US/08ff69f6-4f7a-4944-8585-4f1de7c44e80/explorerexe-required-to-run-universal-apps?forum=windowsuidevelopment) []

**Comment by ENDERZOMBI102** [comment]
could this be useful for a workaround? https://learn.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher
basically, launch windows in a sort-of kiosk mode, which could launch cairo as shell, via the `customshellhost.exe` method

**Comment by themerror** [comment]
> It is a known issue as referenced on [MSDN](https://social.msdn.microsoft.com/Forums/lync/en-US/08ff69f6-4f7a-4944-8585-4f1de7c44e80/explorerexe-required-to-run-universal-apps?forum=windowsuidevelopment) No workaround has been found, though. It seems like a lazy approach by MS to make people stick to their integrated shell.

According to Start Is All Back, Windows is testing a new feature called `ImmersiveShellInShellAppRuntime`. After I enable this feature on my virtual machine(Windows Dev), I find that UWP apps are able to run without `explorer.exe`. I suppose that `ShellAppRuntime.exe` has replaced some functions of `explorer.exe`.

**Comment by MishaProductions** [comment]
I have reverse engineered the private COM class that is used to start UWP, however that class uses another private api that intentionally requires the exe to be signed by Microsoft and have a .imrsrv PE section.

**Comment by O5-3TheKid** [comment]
That's interesting if that's the cause it must have been a change recent to
my posting of the error as I had been using uwp programs through Cairo
before that

**Comment by MishaProductions** [comment]
In newer versions of windows 11, microsoft moved the code to some other process I am pretty sure.

**Comment by O5-3TheKid** [comment]
Probably well guess I won't be using the install this site as a app button
anymore XD not a huge loss

**Comment by O5-3TheKid** [comment]
I love Cairo though UI is so much better than the window one been running
it on my systems for over a year now with only minor hiccups like this one.
the only thing I don't like is Cairo's replacement for file explorer but
you guys are awesome and made it optional so I just stick to the original
one.

**Comment by josuave** [comment]
@themerror Do you have a link to your reference? We are very interested in any information that will allow us to better support using Cairo as a full shell replacement.

**Comment by josuave** [comment]
Another reference: https://www.windowslatest.com/2022/12/22/microsoft-wants-to-make-windows-11-faster-by-decoupling-features-from-explorer-exe/

**Comment by theotheroracle** [comment]
ok, so i'm on windows 10 and i'd rather not update to 11, the MSDN articles say you can simply start explorer.exe, and then the UWP app will run, but even with exlporer.exe open, i just get the class not registered error when i try to open settings ? am i doing something wrong here ?

**Comment by josuave** [comment]
> ok, so i'm on windows 10 and i'd rather not update to 11, the MSDN articles say you can simply start explorer.exe, and then the UWP app will run, but even with exlporer.exe open, i just get the class not registered error when i try to open settings ? am i doing something wrong here ?
> 
> is there some other way to modify system settings if i can't use the settings app ?

Are you running with Cairo as shell? If so, that scenario isn't supported at the moment.

**Comment by theotheroracle** [comment]
alright, i installed windows 11, but i wasn't able to find the immersiveshellinshellappruntime feature though, i do however have the shellappruntime application, but it doesn't seem to work the way i expect it to, at least, when i run it, i still can't launch the settings app for example, so i'm not sure what's wrong

**Comment by theotheroracle** [comment]
https://github.com/cairoshell/cairoshell/issues/734#issuecomment-1326425262
i'm wondering if this could be used as a workaround though, it seems promising ?

**Comment by dremin** [comment]
Good news, I have MS Edge apps and other non-sandboxed packaged apps (Notepad, Paint, Terminal, and others such as Spotify) working when Cairo is running as shell. The packaged versions of these apps have been broken for some time.

Unfortunately I have not had any luck with the shell launcher or the insider features mentioned above for running sandboxed apps such as Calculator.

**Comment by theotheroracle** [comment]
the biggest issue for me is not being able to open the settings app
