### ISSUE TITLE
everytime i launch cairo this happens

### ISSUE THREAD

**Issue by maxox** [cairoshell/cairoshell#735]
**Describe the bug**
idk

**Steps to reproduce**
1. everytime i launch cairo

**Expected behavior**
if i click yes cairo crash without restarting, if i click no cairo continues and it seems fine

**System information:**
 - Windows version: windows 7
 - Cairo version: Version 0.4.245.61259 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: no

**Additional context**
nope

**Screenshots**
![2022-10-13_10-12-36_Cairo_Desktop_Error](https://user-images.githubusercontent.com/7052069/195490656-0dfef76a-5a66-4d37-9d67-327b0e9f5271.png)

**Comment by maxox** [comment]
btw i just realise that the window class of cairo is randomly generated, kinda weird to me considering assigning hotkey to specific class would be inconvenient as each one of them looks almost the same.

**Comment by dremin** [comment]
Interesting, what version of .NET Framework do you have installed? I'm not able to reproduce this on my Windows 7 machine.

**Comment by maxox** [comment]
the version of .NET Framework installed is 4.8.03761

**Comment by maxox** [comment]
i don't know if this is related to the issue, there are 40+ collapsible icons and 24 pinned icons in my notification area icons, my screen resolution is 1080p, some of collapsible icons are extended outside the menu bar i can't even click them. imo its better to have another option choosing to hide those additional collapsible icons

**Comment by maxox** [comment]
idk why the error window its just gone now

**Comment by dremin** [comment]
Interesting, by chance did you uninstall/stop running some software, or some other change has happened?

**Comment by maxox** [comment]
nope just the same running software as usual, maybe it's about the settings i changed in cairo. ill try reproducing it and find out why
