### ISSUE TITLE
Menu bar suggestions. Auto hide. Change side.

### ISSUE THREAD

**Issue by relt-1** [cairoshell/cairoshell#742]
It is very annoying to move fullscreen windows because the menu bar is the topmost thing on the screen. Which means that you cant just move your mouse to the top and drag down to quickly unmaxmimize. 

The best option (and the first thing that i would like to be implemented from this suggestion) would be the ability to change its side on the screen, perhaps even combining it with the taskbar if it's on the same side as it (toggleable).

Auto hide would also be great, along with a pressure detection to open when the cursor is slowly pushing against the side it's on.

Along with that, maybe an option that makes the menu bar not fill the whole screen, so there would be two elements in the corners. Which maybe you could even customize what corner each of them are in.
And if the task bar combine option is enabled, only one of the elements would combine while the other would be in a different place, or even in the same corner with one combined and the other one not.

**Comment by dremin** [comment]
The latest release added the ability to change the edge the menu bar is on, as well as auto hide for the menu bar with configurable delay.
