### ISSUE TITLE
Cairo Shell sometimes randomly clicks

### ISSUE THREAD

**Issue by Hacker1245** [cairoshell/cairoshell#75]
As I said, the shell randomly clicks. You can see it when you type in a text field or while navigating through menus.

**Comment by dremin** [comment]
Could you please clarify what you mean by random clicks? I am aware of certain apps stealing focus due to Cairo’s notification area. Try this: open Cairo Settings > Menu Bar and deselect the periodic re-hook option at the bottom, then restart Cairo.

**Comment by dremin** [comment]
@Hacker1245 have you been able to confirm if that setting change fixed the issue?

**Comment by dremin** [comment]
Closing due to lack of response.
