### ISSUE TITLE
Cairo shell bars disappeared if you turn off and on screen

### ISSUE THREAD

**Issue by IntinteDAO** [cairoshell/cairoshell#779]
**Describe the bug**

In general, Cairo Shell does not cope with dynamically turning screens off and on.

In short, I have a monitor connected to an HDMI Switch (but you can unplug and plug in the cable) so I can switch between computers, while the computers see it as a physical unplugging of the HDMI cable.

Cairo Shell, in theory, should detect screen changes and adjust to the current screen, but it seems to crash, as the bars disappear and the WIN + Shift + Z shortcut is unresponsive.

**Steps to reproduce**
1. Use only monitor (mine has 2048x1152 resolution - maybe it's an issue, or scale change)
2. Disconnect HDMI cable
3. Cairo works on laptop screen, without dock
4. Connect cable
5. Cairo works on monitor, but without top bar
6. Disconnect cable
7. Cairo works on laptop screen but without all bars
8. Connect -> Only dock works

**Expected behavior**
Restart if monitor is disconnect or something like that.

**System information:**
 - Windows version: Win11 22H2 22621.2428
 - Cairo version: 0.4.285.19267 - Pre-release
 - 32-bit or 64-bit: 64
 - In Cairo Settings > Advanced, is Cairo set as shell?: Explorer

**Additional context**

**Screenshots**

Before disconnect on monitor:
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/d7618d9f-01d3-4ff5-8cb5-2673ed017759)

After, on laptop screen. Dock doesn't work
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/6ca66943-8296-4262-a704-54e8b27f6936)

Cable connect, not top bar, but dock is visible:
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/a5d09f71-c884-4cd3-983b-1e38c4bd02c8)

**Comment by dremin** [comment]
I'm having a hard time reproducing this--both the menubar and taskbar are showing reliably when I switch between an HDMI monitor and a scaled laptop monitor. Could you please share screenshots of your Cairo settings so I can see if a certain setting triggers this?

**Comment by IntinteDAO** [comment]
Maybe the issue is with different resolutions. The Cairo was executed on 1920x1080 and the dock is above bottom on 2048x1152
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/9c871c0d-3817-41b4-a5f8-8ce41708e2c9)

![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/b8dc1426-c0b7-48e9-8fba-e617337bd712)
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/c554f51b-fde7-4556-bf65-20a9f51fc118)
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/3868377f-5841-4f2e-8777-309a3002b5c7)
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/b735d9ba-4dfa-44de-8593-ee9812562d2b)
![obraz](https://github.com/cairoshell/cairoshell/assets/56807194/06402a19-83b0-49db-93ce-f466d4b5e2ee)

**Comment by dremin** [comment]
Is this still happening on the latest release?

**Comment by IntinteDAO** [comment]
Aw, I don't have Windows anymore :(

**Comment by dremin** [comment]
No worries!
