### ISSUE TITLE
Windows 10 native blur behind the Menu Bar

### ISSUE THREAD

**Issue by Annorexorcist** [cairoshell/cairoshell#78]
I'm not sure how hard it would be to implement this feature. I can already enable native blur behind it with the SetWindowCompositionAttribute.exe tool made by bigmuscle: 
![afx1iit](https://user-images.githubusercontent.com/7005143/34778444-55f57664-f5eb-11e7-994e-cf8de3a3a117.png)
It would just be nice to have it there as an option.

**Comment by dremin** [comment]
This is now implemented in the latest build. There is a new setting in the Menu Bar section of Cairo Settings to enable blur.
