### ISSUE TITLE
Make the tray icons open at the top of the screen

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#79]
Any way to have the EarTrumpet and native network tray on top by default instead of bottom?
Placing native taskbar to top, the tray menus are almost correctly placed (there is a gap of a few pixels, because native taskbar is taller than cairo menu bar).
Any way to auto-move taskbar to top and correct the reserved space to perfectly fit the cairo menu bar?

**Comment by dremin** [comment]
EarTrumpet should open at the top of the screen with a few tweaks I've already made to Cairo, in conjunction with a pull request I opened for EarTrumpet, if accepted.

With regards to the network flyout, that may be a separate issue. Cairo is in constant battle with Explorer on owning the notification area (hence the re-hook option) so I do not know if this is something I can fix but I will continue to look into it.

**Comment by dremin** [comment]
Cairo now provides apps with the information they need to appear in the correct place. It is up to the application to use this information appropriately.
