### ISSUE TITLE
When TaskBar in Hidden Mode, please create a short-time threshold for TaskBar to not appear super instantly when you position mouse at the bottom of the screen

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#797]
im using Cairoshell with the TaskBar mode = hidden

I really enjoy my workflow using this mode, because the screen is fully avalialbe for primar work. 
the real probem is only this : when you position your mouse at the bottom of the screen, for example you need to pick an element near that area, or there is a desired file in file explorer, whatever - the TaskBar instantly appears

so what Im suggesting to improve the global workflow using cairoshell for better  and more pleasing user experience :
⁜ add feature to adjust a short-time treshold before the TaskBar shows up , to help user with accident mouse moves.
for example from 0.5 sec to 3 sec. or a standard treshold parameter of 1.5 sec. 
this will improve the productivity level in many usage scenarios A LOT 

**UPD** :  I ve tested the most recent **builds #791** https://github.com/cairoshell/cairoshell/pull/791
[autohide-show-delay](https://github.com/cairoshell/cairoshell/tree/autohide-show-delay) **and #326** https://github.com/cairoshell/cairoshell/pull/791
[autohide-show-delay](https://github.com/cairoshell/cairoshell/tree/autohide-show-delay)
to see if the previous issue was investigated (to add treshold time for Menu Bar) 
but there is nothing changed devoted to this issue , and so for TaskBar

please I believe this will bring cairoshell up to the very new level of productivity and will add a strong effect of being much more polished for end-users and will help to engage more people to start using Cairoshell

_thank you for this amazing product anyway, it has a really nice impression after working in_

**Comment by ivan8994** [comment]
I would like to test a custom build too, I can provide detailed feedback afterwards

**Comment by dremin** [comment]
Hey @ivan8994– I see you tried the build that should already have this feature. If you open Cairo Settings > Advanced, there is an “auto-hide show delay” setting that should do what you’re looking for—increasing the number should increase the amount of time it takes for the taskbar to show.

**Comment by ivan8994** [comment]
> Hey @ivan8994– 

hi friend indeed this options exists. it works just amazing !! I tested this on both TaskBar and MenuBar elements, and it does the job ! amazing
 thank you very much this definitely should be in the release
