### ISSUE TITLE
Windows Action Center Act as Toggle, not button

### ISSUE THREAD

**Issue by pmikstacki** [cairoshell/cairoshell#80]
There is a problem with action center button. When you click it shows an action center, but when you want to hide it (clicking at the same button) it opens again. 
I managed to fix it by just adding this to begining of a MenuBar.xaml.cs
private bool IsActionCenterOpen = false;
and this to action center click
 IsActionCenterOpen = !IsActionCenterOpen;
            if(!IsActionCenterOpen)Shell.ShowActionCenter();
But it's not good enough (it doesn't work if you closed action center in another way)
Have you guys got any ideas how to fix it?

**Comment by dremin** [comment]
This will be fixed in the next build. The problem was because Cairo took focus when the icon was clicked, Action Center would disappear, and then when the mouse button was raised, it would appear again. I fixed this by preventing Cairo from taking focus when this button is clicked.

**Comment by dremin** [comment]
This is resolved in the latest build.
