### ISSUE TITLE
Taskbar is hidden in task view when no space reservation

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#81]
Taskbar is hidden in task view when no space reservation, it would be better to show it.
I hope it is possible to draw something on top of it by the way.

**Comment by dremin** [comment]
Taskbar is visible in Task View for me. Are you using the "Taskbar reserves space" option?

**Comment by dremin** [comment]
Okay, thanks for confirming the setting. Reserving the space is the only way to show the taskbar on Task View as it creates a full screen always on top window.
