### ISSUE TITLE
Tray icon of some programs (like Process Lasso) have no response clicking.

### ISSUE THREAD

**Issue by Kirbysfan** [cairoshell/cairoshell#813]
**Describe the bug**
The tray icon of some programs would show properly, but there's no response clicking them.
Currently I found 2 programs that have such issue:
Process Lasso, QQ (NTQQ)
**Steps to reproduce**
1.  Launch programs that has problem.
2.  Launch Cairo

**Expected behavior**
All function of the tray icon of the program should work properly, like what will happen when left/right click.

**System information:**
 - Windows version: Windows 11 23H2
 - Cairo version: 0.4.317.3477
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**

**Comment by dremin** [comment]
I just installed Process Lasso and it seems to be responding to clicks (left click opens the main window; right click opens the menu). I tried both with launching it before or after Cairo, but both scenarios seem to work here.

**Comment by Kirbysfan** [comment]
Wow, restarting the program solves the problem...
