### ISSUE TITLE
Add an option to bind a key to the cairo start menu

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#82]
For keyboard addicts.
But leave this as an option.
Leaving the choice of the key to bind would allow to override Win key, or set an other key to be able to use both start menus.

**Comment by dremin** [comment]
I agree Cairo needs keyboard shortcuts! I will probably add one for Search as well while I'm at it.

**Comment by dremin** [comment]
This will be Win+Shift+C for now but I want to add customization for hotkeys in the future.

**Comment by mdmk** [comment]
It is a good start, thanks 👍 
I notice we cannot exit the Cairo start menu with escape or Win+Shift+Z again.

**Comment by dremin** [comment]
Good catch, this will be fixed in the next build.

**Comment by dremin** [comment]
This is now available in the latest build.

**Comment by mdmk** [comment]
@dremin Win+Shift+Z works and closes Cairo start menu.
Escape does not work when using Win+Shift+Z to open first.
But Escape does work if I mouse click on button, or if I mouse click, then close and reopen with Win+Shift+Z.
