### ISSUE TITLE
Screen doesn't auto lock based on timeout in Power Settings

### ISSUE THREAD

**Issue by rapatel0** [cairoshell/cairoshell#83]
OS: Windows 10 Pro - OS build 16299.192

While Cairo desktop is enabled the screen will stay on despite a timeout in windows power settings. 

It's stupid but I need it for security compliance at work

**Comment by dremin** [comment]
I am aware of certain apps stealing focus due to Cairo’s notification area. I wonder if that is causing your problem. Try this: open Cairo Settings > Menu Bar and deselect the periodic re-hook option at the bottom, then restart Cairo.

**Comment by dremin** [comment]
Closing due to lack of response and reproduction
