### ISSUE TITLE
Silently crashes right after launch on Win10 Insiders build 17074.1002

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#84]
Whenever Cairo is launched on the latest Insiders build, it appears but dies before it can be interacted with.

**Comment by coldacid** [comment]
I don't get any error message from Windows or Cairo, but there are three related events in the Application log -- two errors (a .NET Runtime error and an Application Error) and a WER info event. Looks like a fault happens in d3d9.dll which turns into an unhandled exception which causes Cairo to die.


[Cairo crash event logs.zip](https://github.com/cairoshell/cairoshell/files/1653172/Cairo.crash.event.logs.zip)

**Comment by dremin** [comment]
Thanks for the logs. What other applications do you have running (including background apps)? Does the issue persist after a reboot?

**Comment by coldacid** [comment]
Yeah, it definitely persists after reboot.

Also running at all times are Discord, KeePass, Stardock Fences, Stardock Groupy, Steam, GOG, qBittorrent, Dropbox, Google Drive File Stream, Peercoin, and Alienware system stuff.

**Comment by dremin** [comment]
To help narrow things down.. The only item that stands out as potentially being problematic is the Alienware apps. If you close them does Cairo launch?

**Comment by coldacid** [comment]
All that changes is how long the app lives for before crashing again.

The Alienware apps are just the one for changing the case colours and Dell Update (which I'm only running in hopes that my system will get the Spectre firmware update).

**Comment by coldacid** [comment]
Nothing changed but it seems to work fine now. Maybe it was just some oddness with Windows post-update.

**Comment by dremin** [comment]
Weird, glad you have things working now! Feel free to update this if you are able to find a way to reproduce in the future.
