### ISSUE TITLE
Desktop icons hidden AFTER AND BEFORE UNINSTALL

### ISSUE THREAD

**Issue by Itsamejonah** [cairoshell/cairoshell#842]
System information:
 - Windows version: Windows 11 Home
 - Cairo version: idk
 - 32-bit or 64-bit: 64 bit
Removed my desktop icons. The files are still there, but the desktop won't show them. And it is uninstalled, please help. Screenshot:
![the desktop](https://github.com/user-attachments/assets/2ef585fb-baf4-46f1-9faf-3b058367bb19) desktop is above, if you were wondering.
Oh. and wallpapers are here. [https://www.minecraft.net/en-us/collectibles/minecraft-collection](url) Note: its the beach cabin wallpaper.

**Comment by dremin** [comment]
Right-click your desktop > View > select "Show desktop icons" and they should appear!
