### ISSUE TITLE
please create quick button to restart CairoShell (for immediate fix of some issues)

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#853]
**Describe the solution you'd like**
in Cairo Main context menu (Circle button on the top left corner) please create an option to restart CairoShell when needed.
 
for example, in the same section with "Exit Cairo"

**Comment by dremin** [comment]
In the Cairo menu > Exit Cairo window, you can shift-click the Exit Cairo button to restart.

**Comment by ivan8994** [comment]
> In the Cairo menu > Exit Cairo window, you can shift-click the Exit Cairo button to restart.

thanks i confirm this works 

but this is so not obvious for general users
