### ISSUE TITLE
Bug: MacType Tray crashes

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#86]
MacType is an alternative font rasterizer for Windows.
Launching MacType Tray is the easier way of using MacType font smoothing sytem wide.
Could you see if there is a way of making it work with Cairo?
It does report access violation, enabled or disabled from tray.
![screenshot7](https://user-images.githubusercontent.com/32496803/35641166-b5c37192-06bf-11e8-989a-c53d720d2e93.png)

By the way, if I disable font smoothing in Windows (without lauching MacType) will Cairo enforce font smoothing by himself? If so, It would be good to apply system settings instead if possible.

Note that I did not test running MacType as a service, I don't have testing environment at this time and don't want to freeze or something.
So the font smoothing by itself is perhaps not compatible at all.
The registry mode is buggy on Windows 10, you should avoid it by all cost for now.

**Comment by dremin** [comment]
WPF uses its own font rendering engine, so font smoothing is always 'on' in Cairo. However, I tried Cairo with MacType and noticed that MacType correctly changed the font rendering in Cairo (and honestly, it looks very nice).

As for the error with the tray application, I tested a large number of ways to send messages to this application but I was not able to find a way that did not throw an error. Unfortunately, the tray app is closed source so I can't easily dig in.

**Comment by dremin** [comment]
Closing due to third party issue.

**Comment by Gentle888** [comment]
This error is happening when you point your cursor on mactype icon. @mdmk can you confirm that?

I created issue thread in MacType repo: https://github.com/snowie2000/mactype/issues/408

**Comment by mdmk** [comment]
Yes.
The error is related to tray app itself, not mactype font smoothing.
Even with font smoothing deactivated, mactray crashes when hovering tray icon in Cairo notification zone.
This thread is closed, you should continue on the issue you opened in mactype repository

**Comment by mdmk** [comment]
snowie2000/mactype#408

**Comment by dremin** [comment]
This is fixed in the latest build.

**Comment by Gentle888** [comment]
Big thanks to you, @dremin, this is damn awesome
