### ISSUE TITLE
Some installers failing with Cairo running

### ISSUE THREAD

**Issue by jmhibben** [cairoshell/cairoshell#95]
I've been using Cairo for a few weeks now, and I've been really enjoying it. However, I recently noticed an issue: Programs relying on `Squirrel.Windows` for their installer seems to fail on Windows 10 as long as Cairo is open; I tried with Station, Rambox, and MailSpring; each of them failed to install, and left no stack-trace in the SquirrelLog file (located in `%APPDATA%/Local/SquirrelTemp`). The only solution I've been able to come up with is to close Cairo whenever trying to run one of these installers.

I haven't noticed any other installer frameworks with this issue, nor does it surface with apps that don't use an installer to begin with.

**Comment by dremin** [comment]
Squirrel installer has some interesting notification area handling code (but I need to spend some time to figure out what's causing this result).

In Cairo Settings > Menu Bar, disabling "Periodically re-establish notification area hook" seems to allow Squirrel installers to run.

**Comment by jmhibben** [comment]
Seems like an odd thing to halt an installer, but I can confirm that this allows the Station installer to run properly.

**Comment by dremin** [comment]
Interestingly, the latest version of the Station installer seems to work now.

**Comment by dremin** [comment]
This is fixed in the latest release.
