### ISSUE TITLE
Taskbar enabled when "Enable Taskbar" is turned off, but "Show Taskbar on multiple monitors" is turned on

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#96]
The "Show Taskbar on multiple monitors" option should be ignored if "Enable Taskbar" is off, as otherwise it conflicts with Explorer when its own taskbar is shown on multiple monitors and leads to unsightly and unusable desktop space between windows and Explorer taskbar on those additional monitors (with height about the same as the Cairo taskbar).

**Comment by dremin** [comment]
Whoops, thanks for pointing this out! It will be fixed in the next release.

**Comment by coldacid** [comment]
Thanks!

**Comment by dremin** [comment]
This is fixed in the latest release.
