### ISSUE TITLE
[Feature request] WinPE support

### ISSUE THREAD

**Issue by 1nsecure** [cairoshell/cairoshell#97]
I have tried to use Cairo in WinPE environment (Windows 10 (1709) based with Dotnet Framework addon) and it seems like it does not work.
No errors or anything, just silently exits after starting a process.

So,
1. Anyone have luck with using Cairo Shell with recent WinPEs?
2. Can we add support of it?

**Comment by dremin** [comment]
I haven't tried Cairo in WinPE yet, but I think it should be possible to get it working. Do you see any .NET exceptions in the Windows event log?

**Comment by 1nsecure** [comment]
Sadly, WinPE does not have eventlog.
Does Cairo writes logs by itself somewhere?

![cairo-winpe](https://user-images.githubusercontent.com/29379145/37202893-98d7a8fe-2394-11e8-8d08-b51c1c4f7d49.png)

**Comment by dremin** [comment]
I played around with this and I don't believe WinPE has the proper support for Cairo; what is available is very limited. Not a single line of Cairo code executes.

For what it's worth, Hyper-V Server or Core installations of Server 2016 support Cairo in a minimal environment.
