### ISSUE TITLE
menu bar issues

### ISSUE THREAD

**Issue by fadhlan43** [cairoshell/cairoshell#98]
window buttons like close and minimize go behind the menu bar and is impossible to click the buttons without exiting cairo

**Comment by fadhlan43** [comment]
![capture](https://user-images.githubusercontent.com/13182548/37205159-484d227e-23c6-11e8-8f23-cc9aaf717d39.PNG)

**Comment by mdmk** [comment]
What is your OS ?
Version of Windows and architecture (32 or 64bit) ?
You can check this via Win+Pause on your keyboard or right click > properties on 'My PC' icon on desktop or file explorer.

Do you use multiple monitors and what is the status (ticked/unticked) of the option "Show menu bar on multiple monitors" in Cairo ?

Please check you have the latest Cairo version. In Cairo menu, use check update. If no update available, compare version number to the latest milestone just to be sure.

Did you try to minimize then restore the window ?
You can do this first in native shell, then launch Cairo.
Or in Cairo you can do win + arrow down once then win + arrow up once.
It will minimize then maximize the window, without the use of the unreachable buttons.
After that, do the window still have wrong position (under Cairo menu bar) ?

**Comment by fadhlan43** [comment]
OS: Windows 10
Arcitrcture: 64 Bit
Monitor setup: 1 screen
I am using cairo for the sole
pourpose because my native shell isnt working.
I say unreachable buttons because in some windows you cannnot click the
button to the right of the minimize button
also called "grouping"
-Fadhlan

**Comment by mdmk** [comment]
I suggest you to repair your native shell first.
Unless @dremin want to investigate this wrong behavior further.
An easy way to repair your shell is to reinstall OS.
It is possible to do this without losing documents and third party applications.
To do so, follow this [procedure](http://www.intowindows.com/repair-windows-10-install-without-losing-apps-data/) carefully.

**Comment by fadhlan43** [comment]
ok thanks for your advice

-Fadhlan

**Comment by mdmk** [comment]
There are other ways to repair shell but not as straightforward.
After doing this, test Cairo again.
If bug is gone, problem come from wrong Windows installation.
If not, we'll take a look further.
Let us know how things turn out.

**Comment by fadhlan43** [comment]
ok

-Fadhlan

**Comment by fadhlan43** [comment]
my native shell i looked up the problem is that shcore.dll is somehow not
being loaded but i checked using dism that the file is ok
-Fadhlan

**Comment by mdmk** [comment]
Did you try all these [steps](https://answers.microsoft.com/en-us/windows/forum/windows_10-files/the-shellhistory-folder-crashes-explorerexe/f652ac3c-16ce-4590-8479-459d7faf3985) ?
You can also do them in failsafe mode if it does not work.

**Comment by fadhlan43** [comment]
i currently dont have access to my computer atm because exams

-Fadhlan

**Comment by mdmk** [comment]
No problem.
Come back when you have time.

**Comment by fadhlan43** [comment]
ill finish my exams on 16 Mar 2018

-Fadhlan

**Comment by fadhlan43** [comment]
ok, thanks!

-Fadhlan

**Comment by mdmk** [comment]
You're welcome.

**Comment by dremin** [comment]
When installing Cairo did you select the option to replace Explorer?

**Comment by fadhlan43** [comment]
hmm i wil check later

-Fadhlan

**Comment by fadhlan43** [comment]
ok so i seem to have found a solution which is to use a little program called always-on-top.exe
to make windows stay on top of other windows using Ctrl+Space

**Comment by dremin** [comment]
When the Windows shell is running (which it appears to be in your screenshot based on the presence of the Action Center button), Cairo sends it commands to reserve space on screen. I suspect since your Windows shell is broken, this isn't working correctly. If you reinstall Cairo with the option to replace Explorer, then log off/log on, I suspect you should see better results. If you're able to try this at some point, I'd be interested what happens.

**Comment by fadhlan43** [comment]
ok im trying that now

-Fadhlan

**Comment by fadhlan43** [comment]
but my explorer shell is still broken so i cant open coltrol panel

**Comment by fadhlan43** [comment]
but now window controls dont go behind the menu bar, which is great

**Comment by dremin** [comment]
Glad to hear it! I'll close this out.
